type D_UrlFormat=
	|"/channel_switcher"
	|"/upload"
	|"android-app://com.google.android.youtube/http/youtube.com/premium"
	|`/@${string}`
	|`/@${string}${ChannelSubUrlFormat}`
	|`/account_${G_AccountPageSettingsSections}`
	|`/account`
	|`/api/stats/ads?${string}`
	|`/channel/UC${string}`
	|`/embed/${string}`
	|`/feed/${D_BrowseEndpointPages}`
	|`/feed/trending?${string}`
	|`/gaming`
	|`/playlist?${D_PlaylistUrlParams}`
	|`/shorts/${string}`
	|`/v/${string}?version=3&autohide=1`
	|`/v/${string}`
	|`/watch?${string}`
	|`https://www.youtube.com/pagead/adview?${string}`
	|`https://www.youtube.com/watch?${string}`
	|`https://googleads.g.doubleclick.net/pagead/interaction/?${string}`
	|D_ApiPathFormat_1
	|D_MicroformatEmbed["flashSecureUrl"]
	|D_MicroformatEmbed["flashUrl"]
	|D_MicroformatEmbed["iframeUrl"]
	|D_PlayerMicroformat["ownerProfileUrl"]
	|D_ResultsPageUrl
	|DE_VE83769_Url_1["url"]
	|GM_VE3854["url"]
	|GU_ExternalUrl
	|GU_GoodPut_ProbeUrl
	|GU_VE3611_Url
	|GU_VE6827_Url
	|GU_VE6827_Url
	|GU_VE11487_Url
	|GU_YTExternalUrl
	|NonNullable<D_AdaptiveFormatItem["url"]>
	|NonNullable<D_Channel_MD["channelConversionUrl"]>
	|NonNullable<D_CommentsHeader["unicodeEmojisUrl"]>
	|NonNullable<D_FormatItem["url"]>
	|S_YtUrlHttp_Watch
	;
;
