type P_param_category=P_LogItems extends []? never:P_LogItems[number] extends `[${string}] [${infer U}]`? U:never;
type P_param_missing=Exclude<P_param_category,P_param_known>;
type P_param=Extract<P_param_category,`${string}.params.${string}`>;
type P_param_known_like=`${LP_LogItems_Str}.${P_param_known_like_paths}`;
type P_param_known_like_paths=[
	"f1.f1",
	"f1",
	"f2",
	"f3",
	"f4.f1",
	"f4.f2",
	"f4",
	"f5.f1",
	"f5.f2",
	"f5",
	"f6.f1",
	"f6.f2",
	"f6",
	"f7"
][number];
type P_param_known=
	|P_param_known_1
	|"get_transcript.params.f1"
	|"get_transcript.params.f2"
	|"get_transcript.params.f3"
	|"get_transcript.params.f5"
	|"get_transcript.params.f6"
	|"get_transcript.params.f7"
	|"get_transcript.params.f8"
	|"transcriptTrackSelection.serializedParams.f1"
	|"transcriptTrackSelection.serializedParams.f2"
	|"transcriptTrackSelection.serializedParams.f3"
	|"transcriptTrackSelection.serializedParams.f6"
	|"transcriptTrackSelection.serializedParams.f7"
	|"transcriptTrackSelection.serializedParams.f8"
	|"reel.player_params.f57"
	;
;
type P_param_known_service=
	|"service$create_playlist.f1"
	|"service$create_playlist"
	;
;
type P_param_other_known=P_param_known_service|P_param_tracking|P_param_known_like;
type P_param_tracking<T extends string="tracking">=[
	`${T}.parentTrackingParams`,
	`${T}.trackingParams.f1`,
	`${T}.trackingParams.f19.f1`,
	`${T}.trackingParams.f19.f2`,
	`${T}.trackingParams.f19`,
	`${T}.trackingParams.f2`,
	`${T}.trackingParams.f3`,
	`${T}.trackingParams.f4.f1`,
	`${T}.trackingParams.f4.f2`,
	`${T}.trackingParams.f4.f3`,
	`${T}.trackingParams.f4`,
	`${T}.trackingParams.f6.f12`,
	`${T}.trackingParams.f6.f13`,
	`${T}.trackingParams.f6`,
	`${T}.trackingParams.f9`,
	`${T}.trackingParams`
][number];
type P_param_known_1=
	|"AdServingDataEntry.f4"
	|"AdServingDataEntry.f5"
	|"AdServingDataEntry.f6"
	|"AdServingDataEntry.f7"
	|"AdServingDataEntry.f9.f1"
	|"AdServingDataEntry.f9.f2"
	|"AdServingDataEntry.f9.f3"
	|"AdServingDataEntry.f9"
	|"AdServingDataEntry.f10.f1"
	|"AdServingDataEntry.f10.f6"
	|"AdServingDataEntry.f10.f11"
	|"AdServingDataEntry.f10"
	|"AdServingDataEntry.f13"
	|"AdServingDataEntry.f14"
	|"browse$param.f84.f5"
	|"browse$param.f84"
	|"browse$param.f93.f1"
	|"browse$param.f93.f3"
	|"browse$param.f93"
	|"create_playlist.params.f84.f5"
	|"create_playlist.params.f84"
	|"createBackstagePost.params.f1"
	|"createBackstagePost.params.f2"
	|"get_report_form.f2"
	|"get_report_form.f8"
	|"get_report_form.f11"
	|"get_report_form.f14"
	|"get_report_form.f15"
	|"get_report_form.f18.f1.f2"
	|"get_report_form.f18.f1"
	|"get_report_form.f18"
	|"get_report_form.f25"
	|"get_report_form.f26"
	|"get_report_form.f27"
	|"get_report_form.f28.f1"
	|"get_report_form.f28"
	|"get_report_form.f29"
	|"get_transcript.params.f1"
	|"get_transcript.params.f6"
	|"GetNotificationMenu.ctoken.f1"
	|"record_notification_interactions.f2.f1"
	|"record_notification_interactions.f2.f14.f1.f1"
	|"record_notification_interactions.f2.f14.f1.f2"
	|"record_notification_interactions.f2.f14.f1"
	|"record_notification_interactions.f2.f14.f2"
	|"record_notification_interactions.f2.f14"
	|"record_notification_interactions.f2"
	|"record_notification_interactions.f5"
	|"reel.params.f1"
	|"reel.player_params.f30"
	|"reel.player_params.f71"
	|"reel.sequence_params.f1"
	|"get_report_form.f2"
	|"get_report_form.f8"
	|"get_report_form.f11"
	|"get_report_form.f15"
	|"get_report_form.f18.f1.f2"
	|"get_report_form.f18.f1"
	|"get_report_form.f18"
	|"get_report_form.f25"
	|"get_report_form.f26"
	|"get_report_form.f28.f1.f1.f1.f1.f4"
	|"get_report_form.f28.f1.f1.f1.f1"
	|"get_report_form.f28.f1.f1.f1"
	|"get_report_form.f28.f1.f1.f1[].f1.f4"
	|"get_report_form.f28.f1.f1.f1[].f1"
	|"get_report_form.f28.f1.f1.f1[]"
	|"get_report_form.f28.f1.f1"
	|"get_report_form.f28.f1.f3"
	|"get_report_form.f28.f1"
	|"get_report_form.f28.f1[].f1.f1"
	|"get_report_form.f28.f1[].f1.f1[].f1"
	|"get_report_form.f28.f1[].f1.f1[].f1"
	|"get_report_form.f28.f1[].f1.f1[]"
	|"get_report_form.f28.f1[].f1"
	|"get_report_form.f28.f1[].f3"
	|"get_report_form.f28.f1[]"
	|"get_report_form.f28"
	|"service$create_playlist.f1"
	|"slot_ad_serving_data_entry.f1.f1"
	|"slot_ad_serving_data_entry.f1.f2"
	|"slot_ad_serving_data_entry.f1.f3"
	|"slot_ad_serving_data_entry.f1"
	|"slot_ad_serving_data_entry.f3.f1"
	|"slot_ad_serving_data_entry.f3.f6"
	|"slot_ad_serving_data_entry.f3.f11"
	|"slot_ad_serving_data_entry.f3"
	|"slot_ad_serving_data_entry.f4"
	|"subscribe.params.f2.f1"
	|"subscribe.params.f2"
	|"subscribe.params.f3"
	|"subscribe.params.f4"
	|"tracking.trackingParams.f4.f2"
	|"tracking.trackingParams.f4.f3"
	|"tracking.trackingParams.f5"
	|"tracking.trackingParams.f7"
	|"tracking.trackingParams.f8"
	|"tracking.trackingParams.f10"
	|"tracking.trackingParams.f11"
	|"tracking.trackingParams.f16.f1"
	|"tracking.trackingParams.f16.f2"
	|"tracking.trackingParams.f16.f3"
	|"tracking.trackingParams.f16.f4.f1"
	|"tracking.trackingParams.f16.f4.f2"
	|"tracking.trackingParams.f16.f4.f3"
	|"tracking.trackingParams.f16.f4"
	|"tracking.trackingParams.f16"
	|"tracking.trackingParams.f16"
	|"tracking.trackingParams.f19.f3"
	|"transcript_target_id.param.f1"
	|"transcript_target_id.param.f2"
	|"transcript_target_id.param.f3"
	|"watch.params.f2"
	|"watch.params.f3"
	|"watch.params.f7"
	|"watch.params.f12"
	|"watch.params.f13"
	|"watch.params.f24"
	|"watch.params.f27.f1"
	|"watch.params.f27"
	|"watch.params.f33.f2"
	|"watch.params.f33.f3"
	|"watch.params.f33.f4"
	|"watch.params.f33.f5"
	|"watch.params.f33"
	|"watch.params.f39"
	|"watch.params.f56"
	|"watch.player_params.f8"
	|"watch.player_params.f9"
	|"watch.player_params.f12"
	|"watch.player_params.f25"
	|"watch.player_params.f40.f1.f2"
	|"watch.player_params.f40.f1.f3"
	|"watch.player_params.f40.f1"
	|"watch.player_params.f40"
	|"ypc_get_offers.params.f1.f1"
	|"ypc_get_offers.params.f1.f2"
	|"ypc_get_offers.params.f1"
	|"ypc_get_offers.params.f3"
	|"ypc_get_offers.params.f5.f1"
	|"ypc_get_offers.params.f5.f3"
	|"ypc_get_offers.params.f5.f5.f1"
	|"ypc_get_offers.params.f5.f5"
	|"ypc_get_offers.params.f5.f9"
	|"ypc_get_offers.params.f5"
	|`${"entity_key.subscribed"|"entity_key.normal"}.${"f2"|"f4"|"f5"}`
	;
;