import {MultiPageMenuNotificationSectionRendererData} from "./MultiPageMenuNotificationSectionRendererData";

export type MultiPageMenuNotificationSectionRenderer={
	multiPageMenuNotificationSectionRenderer: MultiPageMenuNotificationSectionRendererData;
};
