import {Accessibility} from "./Accessibility";
import {MenuRendererH} from "./MenuRendererH";
import {MetadataBadgeRenderers} from "./MetadataBadgeRenderers";
import {NavigationEndpoint} from "./NavigationEndpoint";
import {RichThumbnail} from "./RichThumbnail";
import {SimpleText} from "./SimpleText";
import {TextRuns} from "./TextRuns";
import {ThumbnailH} from "./ThumbnailH.js";
import {ThumbnailOverlay} from "./ThumbnailOverlay";
import {ThumbnailsH} from "./ThumbnailsH.js";
import {TrackingParams} from "./TrackingParams.js";

export interface CompactVideoRenderer extends TrackingParams {
	accessibility: Accessibility;
	badges?: MetadataBadgeRenderers[];
	channelThumbnail: ThumbnailsH;
	lengthText: SimpleText;
	longBylineText: TextRuns;
	menu: MenuRendererH;
	navigationEndpoint: NavigationEndpoint;
	publishedTimeText: SimpleText;
	richThumbnail?: RichThumbnail;
	shortBylineText: TextRuns;
	shortViewCountText: SimpleText;
	thumbnail: ThumbnailH;
	thumbnailOverlays: ThumbnailOverlay[];
	title: SimpleText;
	ownerBadges?: MetadataBadgeRenderers[];
	videoId: string;
	viewCountText: SimpleText;
};
