import {Prelude} from "./out_support.js"; export {Prelude};
import {Types} from "./out_support.js"; export {Types};
export namespace Gen {
	export type CF_Generated=
		|{n: Prelude.CF_DC_Generic_CTP; t: Types.CF_DC_Generic_CTP_; v: "D_CD_NextRadio";}
		|{n: Prelude.CF_DC_Generic_CTP; t: Types.CF_DC_Generic_CTP_; v: "D_CD_Reload";}
		|{n: Prelude.CF_D_Button; t: Types.CF_D_Button_; v: "D_Button:accessibility";}
		|{n: Prelude.CF_D_Button; t: Types.CF_D_Button_; v: "D_Button:accessibilityData";}
		|{n: Prelude.CF_D_Button; t: Types.CF_D_Button_; v: "D_Button:command";}
		|{n: Prelude.CF_D_Button; t: Types.CF_D_Button_; v: "D_Button:isDisabled";}
		|{n: Prelude.CF_D_Button; t: Types.CF_D_Button_; v: "D_Button:navigationEndpoint";}
		|{n: Prelude.CF_D_Button; t: Types.CF_D_Button_; v: "D_Button:size";}
		|{n: Prelude.CF_D_Button; t: Types.CF_D_Button_; v: "D_Button:style";}
		|{n: Prelude.CF_D_Button; t: Types.CF_D_Button_; v: "D_Button:text";}
		|{n: Prelude.CF_D_Button; t: Types.CF_D_Button_; v: "D_Button:trackingParams";}
		|{n: Prelude.CF_D_Button; t: Types.CF_D_Button_; v: "D_Button_OnIcon:serviceEndpoint";}
		|{n: Prelude.CF_D_Button; t: Types.CF_D_Button_; v: "D_Button_OnIcon:targetId";}
		|{n: Prelude.CF_D_Button; t: Types.CF_D_Button_; v: "D_Button_OnIcon:tooltip:accessibility";}
		|{n: Prelude.CF_D_Button; t: Types.CF_D_Button_; v: "D_Button_OnIcon:tooltip:command";}
		|{n: Prelude.CF_D_Button; t: Types.CF_D_Button_; v: "D_Button_OnIcon:tooltip:isDisabled";}
		|{n: Prelude.CF_D_Button; t: Types.CF_D_Button_; v: "D_Button_OnIcon:tooltip:serviceEndpoint";}
		|{n: Prelude.CF_D_Button; t: Types.CF_D_Button_; v: "D_Button_OnIcon:tooltip:targetId";}
		|{n: Prelude.CF_D_Button; t: Types.CF_D_Button_; v: "D_Button_OnIcon:tooltip:text";}
		|{n: Prelude.CF_D_Button; t: Types.CF_D_Button_; v: "D_Button_With_TargetId";}
		|{n: Prelude.CF_D_CaseGen; t: Types.CF_D_CaseGen_; v: "AD_ChangeEngagementPanelVisibility.targetId";}
		|{n: Prelude.CF_D_CaseGen; t: Types.CF_D_CaseGen_; v: "AD_ChangeEngagementPanelVisibility.visibility";}
		|{n: Prelude.CF_D_CaseGen; t: Types.CF_D_CaseGen_; v: "DE_SignalNavigation.signal";}
		|{n: Prelude.CF_D_CaseGen; t: Types.CF_D_CaseGen_; v: "D_Button_TargetId";}
		|{n: Prelude.CF_D_CaseGen; t: Types.CF_D_CaseGen_; v: "D_GuideEntry_TargetId";}
		|{n: Prelude.CF_D_CaseGen; t: Types.CF_D_CaseGen_; v: "D_ReelPlayerOverlay";}
		|{n: Prelude.CF_D_CaseGen; t: Types.CF_D_CaseGen_; v: "D_RichMetadata";}
		|{n: Prelude.CF_D_CaseGen; t: Types.CF_D_CaseGen_; v: "D_RichShelf.icon";}
		|{n: Prelude.CF_D_CaseGen; t: Types.CF_D_CaseGen_; v: "D_RichShelf.rowIndex";}
		|{n: Prelude.CF_D_CaseGen; t: Types.CF_D_CaseGen_; v: "D_TargetIdStr:targetId";}
		|{n: Prelude.CF_D_CaseGen; t: Types.CF_D_CaseGen_; v: "D_YtStudio_Url";}
		|{n: Prelude.CF_D_CaseGen; t: Types.CF_D_CaseGen_; v: "GM_WC_RootVe";}
		|{n: Prelude.CF_D_CaseGen; t: Types.CF_D_CaseGen_; v: "GU_YoutubeUrlRedirect.event";}
		|{n: Prelude.CF_D_ChipCloudChip_Omit; t: Types.CF_D_ChipCloudChip_Omit_; v: "D_ChipCloudChip";}
		|{n: Prelude.CF_D_CustomEmoji; t: Types.CF_D_CustomEmoji_; v: "D_CustomEmoji";}
		|{n: Prelude.CF_D_CustomEmoji; t: Types.CF_D_CustomEmoji_; v: "D_LiveChatEmoji";}
		|{n: Prelude.CF_D_GuideEntry; t: Types.CF_D_GuideEntry_; v: "D_GuideEntry";}
		|{n: Prelude.CF_D_GuideEntry; t: Types.CF_D_GuideEntry_; v: "D_GuideEntry_WithPrimary";}
		|{n: Prelude.CF_D_Link; t: Types.CF_D_Link_; v: "D_CompactLink";}
		|{n: Prelude.CF_D_Link; t: Types.CF_D_Link_; v: "D_CompactLink.Styled";}
		|{n: Prelude.CF_D_Menu_Omit; t: Types.CF_D_Menu_Omit_; v: "D_CompactRadio";}
		|{n: Prelude.CF_D_Menu_Omit; t: Types.CF_D_Menu_Omit_; v: "D_CompactVideo";}
		|{n: Prelude.CF_D_Menu_Omit; t: Types.CF_D_Menu_Omit_; v: "D_PlayerOverlayAutoplay";}
		|{n: Prelude.CF_D_Menu_Omit; t: Types.CF_D_Menu_Omit_; v: "D_PlaylistSidebarPrimaryInfo";}
		|{n: Prelude.CF_D_Menu_Omit; t: Types.CF_D_Menu_Omit_; v: "D_Radio";}
		|{n: Prelude.CF_D_Params; t: Types.CF_D_Params_; v: "DE_GetReportForm";}
		|{n: Prelude.CF_D_Params; t: Types.CF_D_Params_; v: "DE_GetTranscript";}
		|{n: Prelude.CF_D_Params; t: Types.CF_D_Params_; v: "DE_YpcGetOffers";}
		|{n: Prelude.CF_D_Params; t: Types.CF_D_Params_; v: "DE_YpcGetOfflineUpsell";}
		|{n: Prelude.CF_D_Playlist_Omit; t: Types.CF_D_Playlist_Omit_; v: "D_CompactPlaylist";}
		|{n: Prelude.CF_D_STR; t: Types.CF_D_STR_; v: "D_ChannelId";}
		|{n: Prelude.CF_D_STR; t: Types.CF_D_STR_; v: "D_RadioShareUrl";}
		|{n: Prelude.CF_D_STR; t: Types.CF_D_STR_; v: "D_YoutubeKidsUrl";}
		|{n: Prelude.CF_D_STR; t: Types.CF_D_STR_; v: "D_YoutubeUrl";}
		|{n: Prelude.CF_D_STR; t: Types.CF_D_STR_; v: "GU_YoutubeUrlRedirect";}
		|{n: Prelude.CF_D_ToggleButton; t: Types.CF_D_ToggleButton_; v: "D_ToggleButton:accessibility";}
		|{n: Prelude.CF_D_ToggleButton; t: Types.CF_D_ToggleButton_; v: "D_ToggleButton:accessibilityData";}
		|{n: Prelude.CF_D_ToggleButton; t: Types.CF_D_ToggleButton_; v: "D_ToggleButton:defaultText";}
		|{n: Prelude.CF_D_ToggleButton; t: Types.CF_D_ToggleButton_; v: "D_ToggleButton:toggledAccessibilityData";}
		|{n: Prelude.CF_D_Video_Handle; t: Types.CF_D_Video_Handle_; v: "D_Video_Other" | "D_Video_With:accessibility" | "D_Video_With:owner" | "D_Video_With:videoId" | "D_Video_With:videoId:topStandaloneBadge" | "D_Video_With:videoId:descriptionSnippet";}
		|{n: Prelude.CF_D_Video_Handle; t: Types.CF_D_Video_Handle_; v: "D_Video_Other:isWatched" | "D_Video_With:accessibility:isWatched" | "D_Video_With:owner:isWatched" | "D_Video_With:videoId:isWatched" | "D_Video_With:videoId:topStandaloneBadge:isWatched" | "D_Video_With:videoId:descriptionSnippet:isWatched";}
		|{n: Prelude.CF_GE_ResponseReceived; t: Types.CF_GE_ResponseReceived_; v: "RS_Next";}
		|{n: Prelude.CF_GE_ResponseReceived; t: Types.CF_GE_ResponseReceived_; v: "RS_Watch";}
		|{n: Prelude.CF_L_CTP_Params; t: Types.CF_L_CTP_Params_; v: "AU_EngagementPanel";}
		|{n: Prelude.CF_L_CTP_Params; t: Types.CF_L_CTP_Params_; v: "C_AdsControlFlowOpportunityReceived";}
		|{n: Prelude.CF_L_CTP_Params; t: Types.CF_L_CTP_Params_; v: "C_Executor";}
		|{n: Prelude.CF_L_CTP_Params; t: Types.CF_L_CTP_Params_; v: "C_GetSurvey";}
		|{n: Prelude.CF_L_CTP_Params; t: Types.CF_L_CTP_Params_; v: "C_ReloadContinuationItems";}
		|{n: Prelude.CF_L_CTP_Params; t: Types.CF_L_CTP_Params_; v: "C_ScrollToEngagementPanel";}
		|{n: Prelude.CF_L_CTP_Params; t: Types.CF_L_CTP_Params_; v: "C_ShowReloadUi";}
		|{n: Prelude.CF_L_CTP_Params; t: Types.CF_L_CTP_Params_; v: "E_SetSettingAutonavForDesktop";}
		|{n: Prelude.CF_L_CTP_Params; t: Types.CF_L_CTP_Params_; v: "RSG_SharePanel_Action";}
		|{n: Prelude.CF_L_CTP_Params; t: Types.CF_L_CTP_Params_; v: "RS_Subscribe_ActionItem_Action";}
		|{n: Prelude.CF_L_CTP_Params; t: Types.CF_L_CTP_Params_; v: "S_Client_Popup";}
		|{n: Prelude.CF_L_CTP_Params; t: Types.CF_L_CTP_Params_; v: "TE_SignalService_I_0";}
		|{n: Prelude.CF_L_Params; t: Types.CF_L_Params_; v: "DC_Timed";}
		|{n: Prelude.CF_L_Params; t: Types.CF_L_Params_; v: "DE_CreateBackstagePost.params";}
		|{n: Prelude.CF_L_Params; t: Types.CF_L_Params_; v: "DE_GetNotificationMenu";}
		|{n: Prelude.CF_L_Params; t: Types.CF_L_Params_; v: "DE_MutationItem";}
		|{n: Prelude.CF_L_Params; t: Types.CF_L_Params_; v: "DE_NotificationOptOut";}
		|{n: Prelude.CF_L_Params; t: Types.CF_L_Params_; v: "DE_RecordNotificationInteractions";}
		|{n: Prelude.CF_L_Params; t: Types.CF_L_Params_; v: "DE_Subscribe";}
		|{n: Prelude.CF_L_Params; t: Types.CF_L_Params_; v: "DE_VE3832:playlistSetVideoId:params";}
		|{n: Prelude.CF_L_Params; t: Types.CF_L_Params_; v: "DE_WatchPlaylist";}
		|{n: Prelude.CF_L_Params; t: Types.CF_L_Params_; v: "DE_YpcGetCart";}
		|{n: Prelude.CF_L_Params; t: Types.CF_L_Params_; v: "DS_CreatePlaylist";}
		|{n: Prelude.CF_L_Params; t: Types.CF_L_Params_; v: "DS_EY_PlaylistLoop.key";}
		|{n: Prelude.CF_L_Params; t: Types.CF_L_Params_; v: "DS_EY_Subscription";}
		|{n: Prelude.CF_L_Params; t: Types.CF_L_Params_; v: "DS_EY_TranscriptSearchBox.key";}
		|{n: Prelude.CF_L_Params; t: Types.CF_L_Params_; v: "DS_EY_TranscriptTrackSelection";}
		|{n: Prelude.CF_L_Params; t: Types.CF_L_Params_; v: "DS_EY_TranscriptTrackSelection.key";}
		|{n: Prelude.CF_L_Params; t: Types.CF_L_Params_; v: "D_AdLayoutLogging";}
		|{n: Prelude.CF_L_Params; t: Types.CF_L_Params_; v: "D_CommentSimplebox";}
		|{n: Prelude.CF_L_Params; t: Types.CF_L_Params_; v: "D_EY_Offlineability.key";}
		|{n: Prelude.CF_L_Params; t: Types.CF_L_Params_; v: "D_PlayabilityStatus";}
		|{n: Prelude.CF_L_Params; t: Types.CF_L_Params_; v: "D_PlaylistEdit";}
		|{n: Prelude.CF_L_Params; t: Types.CF_L_Params_; v: "D_ReelWatch";}
		|{n: Prelude.CF_L_Params; t: Types.CF_L_Params_; v: "D_SerializedSlotAdServingDataEntry";}
		|{n: Prelude.CF_L_Params; t: Types.CF_L_Params_; v: "D_SubscribeButton";}
		|{n: Prelude.CF_L_Params; t: Types.CF_L_Params_; v: "EY_MacroMarkersList.key";}
		|{n: Prelude.CF_L_Params; t: Types.CF_L_Params_; v: "E_LikeDislike";}
		|{n: Prelude.CF_L_Params; t: Types.CF_L_Params_; v: "E_LikeIndifferent";}
		|{n: Prelude.CF_L_Params; t: Types.CF_L_Params_; v: "E_LikeLike";}
		|{n: Prelude.CF_L_Params; t: Types.CF_L_Params_; v: "G_DE_Browse_VE";}
		|{n: Prelude.CF_L_Params; t: Types.CF_L_Params_; v: "MC_ResolveUrl";}
		|{n: Prelude.CF_L_Params; t: Types.CF_L_Params_; v: "RS_Next";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "AD_Notification";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "B_HrefUrl.url";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "DC_LiveChat";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "DC_SectionList_SearchFeed";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "DD_Streaming";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "DE_VE3832_Watch";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "DMD_Badge";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "DMD_RowContainer";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_ActionSetPlaylistVideoOrder";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_AdaptiveFormatItem";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_AutoplayContent";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_AutoplaySwitchButton";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_C4TabbedHeader";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_ChipCloud";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_ChipCloudChip";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_ClipCreation";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_Comment";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_CommentSimplebox";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_CommentsEntryPointHeader";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_CommentsEntryPointTeaser";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_CommentsHeader";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_CommonConfig.url";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_ConfirmDialog";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_DesktopTopbar";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_EndScreenPlaylist";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_EndScreenVideo";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_EngagementPanelTitleHeader";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_ExpandableSurveyResponse";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_FeaturedChannel";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_FeedFilterChipBar";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_FeedNudge";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_FusionSearchbox";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_GuideEntry";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_GuideSection";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_GuideSubscriptionsSection";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_HeroPlaylistThumbnail";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_Hint";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_HorizontalCardList";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_HotkeyDialog";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_InfoRow";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_InlineSurvey";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_LikeButton.rest";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_LoggingDirectives";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_MP_MenuNotificationSection";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_MacroMarkersList";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_MacroMarkersListItem";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_Menu:accessibility";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_Menu:flexibleItems";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_Menu:items";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_Menu:loggingDirectives:trackingParams";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_Menu:targetId";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_Menu:topLevelButtons";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_MenuNavigationItem";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_MenuServiceItem";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_MerchandiseItem";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_MerchandiseShelf";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_MusicCarouselShelf";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_MusicShelf";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_MusicThumbnail";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_NextContinuation";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_Notification";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_NotificationMenuPopupMenuItem";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_NotificationMenu_PopupItem";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_NotificationText";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_NotificationTopbarButton";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_PdgBuyFlow";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_PdgCommentChip";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_PivotButton";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_PlaylistAddToOption";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_PlaylistContent";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_PlaylistHeader";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_PlaylistPanel";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_PlaylistPanelVideo";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_PlaylistSidebar";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_PlaylistVideoThumbnail";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_ProductList";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_ProductListItem";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_ReelPlayerHeader";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_ReelPlayerOverlay";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_RichGrid";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_RichItem";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_RichListHeader";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_RichMetadataRow";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_RichMetadata_BoxArt";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_RichMetadata_Topic";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_RichSection";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_RichShelf";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_SearchBox";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_SectionList_BrowseFeed_Subscriptions";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_SegmentedLikeDislikeButton";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_SortFilterSubMenu";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_SourcePivotHeader";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_SubFeedOption";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_SubFeedSelector";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_SubscribeButton";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_SubscriptionNotificationToggleButton";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_SuperVodBuyFlowContent";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_Tab";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_Tab_R_MusicQueue";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_ThumbnailOverlayEndorsement";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_ThumbnailOverlayToggleButton";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_ThumbnailsList";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_ToggleMenuServiceItem";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_TopbarLogo";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_TopbarMenuButton";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_TopbarMenuButton_MenuItem";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_TopicLink";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_Transcript";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_TranscriptSearchPanel";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_TranscriptSegment";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_VideoOwner";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_VideoPrimaryInfo";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_VideoSecondaryInfo";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_WatchNextEndScreen";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_WatchResult_ResultsItem";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "GM_WC_Base";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "G_DC_SectionList";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "G_Watch_SecondaryResults_Results";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "MP_AccountMenu";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "RD_MenuServiceItem";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "RSB_EditPlaylist";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "RSG_NotificationMenu";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "RSG_PdgBuyFlow";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "RSG_SearchSuggestions";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "RSG_SharePanel";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "RSG_Survey";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "RSG_Transcript";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "RSM_ChannelPreference";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "RSW_ReelItem";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "RS_AccountMenu";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "RS_Browse";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "RS_Channel";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "RS_GetAddToPlaylist";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "RS_GetLiveChat";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "RS_Guide";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "RS_Next";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "RS_Page_Watch";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "RS_Player";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "RS_Playlist";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "RS_Reel";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "RS_ReelWatchSequence";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "RS_Search";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "RS_Settings";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "RS_Subscribe";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "RS_Unsubscribe";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "RS_Watch";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "R_WatchPage_VE3832";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "TD_ItemSection_2_CommentsEntryPoint";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "TD_ItemSection_3";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "T_Command_TP";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "AD_AccountItem";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "AD_AddChatItem";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "AD_AddToGuideSection";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "AD_ChangeEngagementPanelVisibility";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "AD_Notification";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "AD_ReplayChatItem";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "AD_SendFeedback";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "AD_ShowEngagementPanelScrim";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "AD_Signal";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "AD_SubscribeButton";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "AD_UpdateEngagementPanel";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "AD_UpdateNotificationsUnseenCount";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "AU_EngagementPanel";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "AU_ToggleButtonTextData";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "A_BrowseFeed";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "A_CommentsSectionContinuation";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "A_WatchNext";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "B_Hack";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "C_AdsControlFlowOpportunityReceived";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "C_Executor";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "C_GetSurvey";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "C_ReloadContinuationItems";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "C_ScrollToEngagementPanel";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "C_ShowReloadUi";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "CacheMetadata";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "CommentRepliesItem";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "DB_SI_EngagementPanel";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "DC_AddToPlaylist";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "DC_AdsControlFlowOpportunityReceived";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "DC_ChangeKeyedMarkersVisibility";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "DC_Continuation";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "DC_Generic_CTP";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "DC_LiveChat";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "DC_LoadMarkers";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "DC_RelatedChip";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "DC_ReloadContinuationItems";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "DC_ScrollToEngagementPanel";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "DC_SectionList_SearchFeed";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "DC_ShowReloadUi";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "DC_Timed";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "DC_UpdateToggleButtonState";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "DD_Streaming";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "DE_AddToPlaylistService";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "DE_Feedback";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "DE_GetNotificationMenu";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "DE_MutationItem";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "DE_NotificationOptOut";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "DE_PersistenceOption";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "DE_RecordNotificationInteractions";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "DE_ShareEntityService";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "DE_Subscribe";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "DE_SuperThanksSelectedTier";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "DE_UndoFeedback";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "DE_Url";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "DE_VE3832:playlistSetVideoId:params";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "DE_VE3832:videoId";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "DE_WatchPlaylist";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "DMD_AdSlot";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "DMD_Badge";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "DMD_RowContainer";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "DS_CreatePlaylist";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "DS_EY_PlaylistLoop";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "DS_EY_Subscription";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "DS_EY_TranscriptSearchBox";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "DS_EY_TranscriptTrackSelection";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_ActionSetPlaylistVideoOrder";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_AdLayoutMetadata";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_AdSlot";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_AdSlotAndLayoutItem";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_AdaptiveFormatItem";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_AddToPlaylist";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_AddToPlaylistCreate";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_AlertWithButton";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_AttBgChallenge";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_AutoplayContent";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_AutoplaySetItem";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_AutoplaySwitchButton";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_BrowserMediaSession";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_C4TabbedHeader";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_CarouselLockup";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_ChannelSwitcherHeader";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_ChannelSwitcherPage";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_ChannelThumbnailWithLink";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_Channel_MD";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_ChildVideo";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_ChipCloud";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_ChipCloudChip";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_CinematicContainer";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_ClipAdState";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_ClipCreation";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_ClipCreationScrubber";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_ClipCreationTextInput";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_Comment";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_CommentSimplebox";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_CommentsEntryPointHeader";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_CommentsEntryPointTeaser";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_CommentsHeader";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_CompactLink.Styled.icon";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_CompactLink.icon";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_ConfirmDialog";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_ContinuationItem";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_DarkColorPalette";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_DecoratedPlayerBar";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_DesktopTopbar";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_DisplayAd";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_Dropdown";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_EY_Offlineability";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_ElementResourceStatus";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_EmojiImage";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_EndScreenPlaylist";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_EndScreenVideo";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_EngagementPanelSectionList";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_EngagementPanelTitleHeader";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_EntityBatchUpdate";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_ExpandableSurveyResponse";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_ExpandableTab";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_ExpandableVideoDescriptionBody";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_ExternalChannelId";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_Factoid";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_FeaturedChannel";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_FeedFilterChipBar";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_FeedNudge";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_FeedTabbedHeader";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_FeedbackResponseProcessedStatus";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_FrameworkUpdates";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_FusionSearchbox";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_GetSurvey";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_GhostGrid";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_GuideCollapsibleEntry";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_GuideCollapsibleSectionEntry";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_GuideDownloadsEntry";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_GuideEntry";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_GuideEntryBadges";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_GuideEntryData";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_GuideEntry_WithIcon";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_GuideSection";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_GuideSubscriptionsSection";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_HeroPlaylistThumbnail";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_Hint";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_HorizontalCardList";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_HotkeyDialog";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_HotkeyDialogSection";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_HotkeyDialogSectionOption";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_InFeedAdLayout";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_InfoRow";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_InlineSurvey";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_LightColorPalette";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_LikeApi";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_LikeButton";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_LikeButton.dislike";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_LikeButton.like";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_LoggingDirectives";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_MP_MenuNotificationSection";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_MacroMarkersList";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_MacroMarkersListItem";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_Menu:accessibility";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_Menu:flexibleItems";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_Menu:items";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_Menu:loggingDirectives";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_Menu:loggingDirectives:trackingParams";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_Menu:targetId";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_Menu:topLevelButtons";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_MenuFlexibleItem";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_MenuNavigationItem";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_MenuServiceItem";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_MenuServiceItem_Omit";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_MerchandiseItem";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_MerchandiseShelf";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_Microformat.ios";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_Microformat.url";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_Microformat_Other";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_Miniplayer";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_ModifiedSetItem";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_MovingThumbnail";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_MovingThumbnail_Thumbnails";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_MusicCarouselShelf";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_MusicQueue";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_MusicShelf";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_MusicThumbnail";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_Notification";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_NotificationMenuPopupMenuItem";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_NotificationMenu_Popup";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_NotificationMenu_PopupItem";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_NotificationText";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_NotificationTopbarButton";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_PageTopAdLayout";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_PdgBuyFlow";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_PdgBuyFlowHeader";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_PdgColorSlider";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_PdgCommentChip";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_PdgCommentOption";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_PdgCommentPreview";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_PivotButton";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_PlayabilityStatus";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_PlayerAnnotationsExpanded";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_PlayerOverlay";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_PlayerOverlay:autoplay";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_PlayerOverlay:autoplay:decoratedPlayerBarRenderer";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_PlayerOverlay:decoratedPlayerBarRenderer";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_PlayerOverlayVideoDetails";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_PlaylistAddToOption";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_PlaylistContent";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_PlaylistEdit";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_PlaylistHeader";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_PlaylistLoopButton";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_PlaylistLoopButtonState";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_PlaylistPanel";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_PlaylistPanelVideo";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_PlaylistSidebar";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_PlaylistVideoThumbnail";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_Playlist_MD";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_PrefetchHintConfig";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_PrimaryLinkItem";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_PrivacyDropdownItem";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_ProductList";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_ProductListItem";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_ProfileColumnStatsEntry";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_ProfileColumnUserInfo";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_ProfilePageHeaderInformation";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_PromotedSparklesWeb";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_Radio";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_RadioShareUrl";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_Range";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_ReelPlayerHeader";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_ReelPlayerOverlay";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_ReelWatch";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_ResourceStatusInResponseCheckData";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_RichGrid";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_RichItem";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_RichListHeader";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_RichMetadataRow";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_RichMetadata_BoxArt";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_RichMetadata_Topic";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_RichSection";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_RichShelf";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_RunAttestation";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_SearchBox";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_SectionList_BrowseFeed_Subscriptions";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_SegmentedLikeDislikeButton";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_SerializedSlotAdServingDataEntry";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_SettingsSidebar";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_ShowEngagementPanel";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_SimpleMenuHeader";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_SortFilterSubMenu";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_SourcePivotHeader";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_SubFeedOption";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_SubFeedSelector";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_SubscribeButton";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_SubscribeButton.subscribe";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_SubscribeButton.subscribed";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_SubscribeButton.unsubscribe";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_SubscribeButton.unsubscribed";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_SubscriptionButton";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_SubscriptionNotificationToggleButton";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_SuperVodBuyFlowContent";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_Tab_R_MusicQueue";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_Tab_WhatToWatch";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_TemplateUpdate";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_TextInputFormField";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_Thumbnail";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_ThumbnailItem";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_ThumbnailOverlayEndorsement";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_ThumbnailOverlayHoverText";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_ThumbnailOverlaySidePanel";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_ThumbnailOverlayTimeStatus";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_ThumbnailOverlayToggleButton_ToggledPrefix";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_ThumbnailOverlayToggleButton_UntoggledPrefix_1";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_ThumbnailOverlayToggleButton_UntoggledPrefix_2";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_ThumbnailsList";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_TimestampWithNanos";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_ToggleMenuServiceItem";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_TopbarLogo";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_TopbarMenuButton";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_TopbarMenuButton_MenuItem";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_TopicLink";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_Transcript";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_TranscriptSearchPanel";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_TranscriptSegment";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_TranscriptSegmentList";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_TwoColumnBrowseResults";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_TwoColumnWatchNextResults";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_VideoDescriptionHeader";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_VideoDescriptionMusicSection";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_VideoOwner";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_VideoOwner:1";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_VideoPrimaryInfo";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_VideoSecondaryInfo";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_VideoViewCount";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_Video_Owner";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_VoiceSearchDialog";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_VssLoggingContext";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_WatchEndpointMusicConfig";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_WatchNextEndScreen";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_WatchNextTabbedResults";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_WatchResult_ResultsItem";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_WatchResults";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_WebPrefetch";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_WebSearchboxConfig";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "EY_MacroMarkersList";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "E_LikeDislike";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "E_LikeIndifferent";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "E_LikeLike";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "E_SetSettingAutonavForDesktop";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "GM_VE11487_WC";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "GM_VE23462_WC";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "GM_VE3611_WC";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "GM_VE37414_WC";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "GM_VE3832_WatchPlaylist" | "GM_VE3832_Watch";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "GM_VE3854_WC";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "GM_VE42352_WC";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "GM_VE4724_WC";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "GM_VE5754_WC";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "GM_VE6827_WC";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "GM_VE83769_WC";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "GM_VE96368_WC_browse";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "GM_WC";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "GM_WC_Base";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "G_Action_GetNotificationsMenu_Popup";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "G_DC_SectionList";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "G_DE_Browse_VE";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "G_Text";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "G_Watch_SecondaryResults_Contents";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "G_Watch_SecondaryResults_Results";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "MC_ResolveUrl";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "MG_AdLayout";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "MMD_AdLayout_TopImage";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "MP_AccountMenu";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "M_VE_Browse";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "NotchesItem";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "Popup_GetAccountMenu";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "RCA_RelevantStateTags";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "RC_ConsistencyTokenJar";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "RC_MainAppWebResponseContext";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "RC_ResponseContext";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "RC_WR_ContextExtension";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "RD_MenuServiceItem";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "REG_AccountSwitcher";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "REG_DatasyncIds";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "RSB_EditPlaylist";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "RSG_GetUnseenCount";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "RSG_NotificationMenu";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "RSG_PdgBuyFlow";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "RSG_SearchSuggestions";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "RSG_SharePanel";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "RSG_SharePanel_Action";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "RSG_Survey";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "RSG_Transcript";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "RSL_Dislike";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "RSL_Like";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "RSL_RemoveLike";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "RSM_ChannelPreference";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "RSU_M";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "RSW_ReelItem";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "RS_AccountMenu";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "RS_AccountsList";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "RS_AttGet";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "RS_Browse";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "RS_Channel";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "RS_Feedback";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "RS_GetAddToPlaylist";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "RS_GetLiveChat";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "RS_Guide";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "RS_Next";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "RS_Page_Browse";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "RS_Page_Watch";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "RS_Player";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "RS_Playlist";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "RS_Reel";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "RS_ReelWatchSequence";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "RS_Search";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "RS_SearchPage";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "RS_SetSetting";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "RS_Settings";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "RS_ShortsPage";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "RS_Subscribe";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "RS_Subscribe_ActionItem_Action";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "RS_Success";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "RS_Unsubscribe";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "RS_Watch";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "R_ChannelPage";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "R_PlaylistPage";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "R_SettingsPage";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "R_TextRun";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "R_WatchPage_VE3832";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "S_Client_Popup";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "S_GetAccountMenu";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "S_VoiceSearchPopup_Dialog";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "Settings_VE23462";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "Shorts_VE37414";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "Signal_GetNotificationsMenu";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "Signal_Omit";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "StateTag";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "TD_ItemSection_2_CommentsEntryPoint";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "TE_SignalService_I_0";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "TM_Visibility";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "T_Autoplay";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "T_Command_TP";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "T_DE_SettingItem.407";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "T_Playlist";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "T_SecondaryResults";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "T_ShortsSurfaceIdentifier";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "T_Types";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "T_UrlWrappedValue";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "ToggleButton.state";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "YTNavigateFinishDetail";}
		|{n: Prelude.CF_M_w; t: Types.CF_M_w_; v: "GM_UserFeedback";}
		|{n: Prelude.CF_M_w; t: Types.CF_M_w_; v: "GM_VE3832_Watch:omit";}
		|{n: Prelude.CF_M_w; t: Types.CF_M_w_; v: "G_AdditionalDataItem";}
		|{n: Prelude.CF_M_y; t: Types.CF_M_y_; v: "AD_HideEnclosing";}
		|{n: Prelude.CF_M_y; t: Types.CF_M_y_; v: "AD_HideEngagementPanelTargetId";}
		|{n: Prelude.CF_M_y; t: Types.CF_M_y_; v: "AU_ToggleButtonText";}
		|{n: Prelude.CF_M_y; t: Types.CF_M_y_; v: "AU_Viewership";}
		|{n: Prelude.CF_M_y; t: Types.CF_M_y_; v: "AU_ViewershipData";}
		|{n: Prelude.CF_M_y; t: Types.CF_M_y_; v: "B_HrefUrl";}
		|{n: Prelude.CF_M_y; t: Types.CF_M_y_; v: "CD_NextRadio";}
		|{n: Prelude.CF_M_y; t: Types.CF_M_y_; v: "CD_Reload";}
		|{n: Prelude.CF_M_y; t: Types.CF_M_y_; v: "DC_Continuation";}
		|{n: Prelude.CF_M_y; t: Types.CF_M_y_; v: "DC_Loop";}
		|{n: Prelude.CF_M_y; t: Types.CF_M_y_; v: "DE_CreateBackstagePost";}
		|{n: Prelude.CF_M_y; t: Types.CF_M_y_; v: "DE_PlaylistEditor";}
		|{n: Prelude.CF_M_y; t: Types.CF_M_y_; v: "DE_UserFeedback";}
		|{n: Prelude.CF_M_y; t: Types.CF_M_y_; v: "DE_YpcGetCart";}
		|{n: Prelude.CF_M_y; t: Types.CF_M_y_; v: "D_CanShare";}
		|{n: Prelude.CF_M_y; t: Types.CF_M_y_; v: "D_EditableDetails";}
		|{n: Prelude.CF_M_y; t: Types.CF_M_y_; v: "D_MenuNavigationItem";}
		|{n: Prelude.CF_M_y; t: Types.CF_M_y_; v: "D_PlaylistByline";}
		|{n: Prelude.CF_M_y; t: Types.CF_M_y_; v: "D_PlaylistPanelVideo";}
		|{n: Prelude.CF_M_y; t: Types.CF_M_y_; v: "D_ProfilePageHeaderTitle";}
		|{n: Prelude.CF_M_y; t: Types.CF_M_y_; v: "D_ProfilePageHeaderTitle_Content";}
		|{n: Prelude.CF_M_y; t: Types.CF_M_y_; v: "D_RelatedChipCloud";}
		|{n: Prelude.CF_M_y; t: Types.CF_M_y_; v: "D_Survey_Watch";}
		|{n: Prelude.CF_M_y; t: Types.CF_M_y_; v: "D_ThumbnailOverlayBottomPanel";}
		|{n: Prelude.CF_M_y; t: Types.CF_M_y_; v: "D_ThumbnailOverlayNowPlaying";}
		|{n: Prelude.CF_M_y; t: Types.CF_M_y_; v: "D_ThumbnailOverlayResumePlayback";}
		|{n: Prelude.CF_M_y; t: Types.CF_M_y_; v: "D_ToggleButtonIdData";}
		|{n: Prelude.CF_M_y; t: Types.CF_M_y_; v: "T_Item";}
		|{n: Prelude.CF_M_y; t: Types.CF_M_y_; v: "UA_DateText";}
		|{n: Prelude.CF_M_y; t: Types.CF_M_y_; v: "UA_DateTextData";}
		|{n: Prelude.CF_M_y; t: Types.CF_M_y_; v: "UA_Description";}
		|{n: Prelude.CF_M_y; t: Types.CF_M_y_; v: "UA_Title";}
		|{n: Prelude.CF_M_y; t: Types.CF_M_y_; v: "UA_TitleData";}
		|{n: Prelude.CF_M_zy; t: Types.CF_M_zy_; v: "D_ChannelHeaderLinks";}
		|{n: Prelude.CF_TA_OpenPopup; t: Types.CF_TA_OpenPopup_; v: "DE_ShareEntityService";}
		|{n: Prelude.CF_TA_OpenPopup; t: Types.CF_TA_OpenPopup_; v: "G_Action_GetNotificationsMenu";}
		|{n: Prelude.CF_TA_OpenPopup; t: Types.CF_TA_OpenPopup_; v: "RSG_NotificationMenu_Action";}
		|{n: Prelude.CF_TA_OpenPopup; t: Types.CF_TA_OpenPopup_; v: "TA_OpenPopup:R_PdgBuyFlow";}
		|{n: Prelude.CF_TA_OpenPopup; t: Types.CF_TA_OpenPopup_; v: "TA_OpenPopup_Empty";}
		|{n: Prelude.CF_TA_Page; t: Types.CF_TA_Page_; v: "AD_UpdateChannelSwitcherPage";}
		|{n: Prelude.CF_TD_ItemSection_3; t: Types.CF_TD_ItemSection_3_; v: "TD_ItemSection_3<\"comment-item-section\",\"comments-section\">";}
		|{n: Prelude.CF_TD_ItemSection_3; t: Types.CF_TD_ItemSection_3_; v: "TD_ItemSection_3<\"comment-item-section\",\"engagement-panel-comments-section\">";}
		|{n: Prelude.CF_TD_ItemSection_3; t: Types.CF_TD_ItemSection_3_; v: "TD_ItemSection_3<\"sid-wn-chips\",\"watch-next-feed\">";}
		|{n: Prelude.CF_TE_Endpoint_2; t: Types.CF_TE_Endpoint_2_; v: "AU_NotificationsUnseenCount";}
		|{n: Prelude.CF_TE_Endpoint_2; t: Types.CF_TE_Endpoint_2_; v: "A_AddChatItem";}
		|{n: Prelude.CF_TE_Endpoint_2; t: Types.CF_TE_Endpoint_2_; v: "A_AddToGuideSection";}
		|{n: Prelude.CF_TE_Endpoint_2; t: Types.CF_TE_Endpoint_2_; v: "A_AppendContinuationItems";}
		|{n: Prelude.CF_TE_Endpoint_2; t: Types.CF_TE_Endpoint_2_; v: "A_ChangeEngagementPanelVisibility";}
		|{n: Prelude.CF_TE_Endpoint_2; t: Types.CF_TE_Endpoint_2_; v: "A_HideEnclosing";}
		|{n: Prelude.CF_TE_Endpoint_2; t: Types.CF_TE_Endpoint_2_; v: "A_HideEngagementPanelScrim";}
		|{n: Prelude.CF_TE_Endpoint_2; t: Types.CF_TE_Endpoint_2_; v: "A_ReplaceEnclosing";}
		|{n: Prelude.CF_TE_Endpoint_2; t: Types.CF_TE_Endpoint_2_; v: "A_SendFeedback";}
		|{n: Prelude.CF_TE_Endpoint_2; t: Types.CF_TE_Endpoint_2_; v: "A_ShowEngagementPanelScrim";}
		|{n: Prelude.CF_TE_Endpoint_2; t: Types.CF_TE_Endpoint_2_; v: "A_Signal";}
		|{n: Prelude.CF_TE_Endpoint_2; t: Types.CF_TE_Endpoint_2_; v: "A_UndoFeedback";}
		|{n: Prelude.CF_TE_Endpoint_2; t: Types.CF_TE_Endpoint_2_; v: "C_AddToPlaylist";}
		|{n: Prelude.CF_TE_Endpoint_2; t: Types.CF_TE_Endpoint_2_; v: "C_CommandExecutor";}
		|{n: Prelude.CF_TE_Endpoint_2; t: Types.CF_TE_Endpoint_2_; v: "C_EngagementPanelHeaderShowNavigationButton";}
		|{n: Prelude.CF_TE_Endpoint_2; t: Types.CF_TE_Endpoint_2_; v: "C_EntityUpdate";}
		|{n: Prelude.CF_TE_Endpoint_2; t: Types.CF_TE_Endpoint_2_; v: "C_FollowUp";}
		|{n: Prelude.CF_TE_Endpoint_2; t: Types.CF_TE_Endpoint_2_; v: "C_Loop";}
		|{n: Prelude.CF_TE_Endpoint_2; t: Types.CF_TE_Endpoint_2_; v: "C_RefreshPlaylist";}
		|{n: Prelude.CF_TE_Endpoint_2; t: Types.CF_TE_Endpoint_2_; v: "C_RelatedChip";}
		|{n: Prelude.CF_TE_Endpoint_2; t: Types.CF_TE_Endpoint_2_; v: "C_RepeatChapter";}
		|{n: Prelude.CF_TE_Endpoint_2; t: Types.CF_TE_Endpoint_2_; v: "C_ResetChannelUnreadCount";}
		|{n: Prelude.CF_TE_Endpoint_2; t: Types.CF_TE_Endpoint_2_; v: "C_UpdateToggleButtonState";}
		|{n: Prelude.CF_TE_Endpoint_2; t: Types.CF_TE_Endpoint_2_; v: "E_ShowEngagementPanel";}
		|{n: Prelude.CF_TE_Endpoint_2; t: Types.CF_TE_Endpoint_2_; v: "E_YpcGetOfflineUpsell";}
		|{n: Prelude.CF_TE_Endpoint_3; t: Types.CF_TE_Endpoint_3_; v: "C_GetPdgBuyFlow";}
		|{n: Prelude.CF_TE_Endpoint_3; t: Types.CF_TE_Endpoint_3_; v: "E_AddToPlaylistService";}
		|{n: Prelude.CF_TE_Endpoint_3; t: Types.CF_TE_Endpoint_3_; v: "E_Browse";}
		|{n: Prelude.CF_TE_Endpoint_3; t: Types.CF_TE_Endpoint_3_; v: "E_CreateBackstagePost";}
		|{n: Prelude.CF_TE_Endpoint_3; t: Types.CF_TE_Endpoint_3_; v: "E_CreatePlaylistService";}
		|{n: Prelude.CF_TE_Endpoint_3; t: Types.CF_TE_Endpoint_3_; v: "E_GetNotificationMenu";}
		|{n: Prelude.CF_TE_Endpoint_3; t: Types.CF_TE_Endpoint_3_; v: "E_GetReportForm";}
		|{n: Prelude.CF_TE_Endpoint_3; t: Types.CF_TE_Endpoint_3_; v: "E_GetTranscript";}
		|{n: Prelude.CF_TE_Endpoint_3; t: Types.CF_TE_Endpoint_3_; v: "E_Like";}
		|{n: Prelude.CF_TE_Endpoint_3; t: Types.CF_TE_Endpoint_3_; v: "E_NotificationOptOut";}
		|{n: Prelude.CF_TE_Endpoint_3; t: Types.CF_TE_Endpoint_3_; v: "E_PlaylistEdit";}
		|{n: Prelude.CF_TE_Endpoint_3; t: Types.CF_TE_Endpoint_3_; v: "E_PlaylistEditor";}
		|{n: Prelude.CF_TE_Endpoint_3; t: Types.CF_TE_Endpoint_3_; v: "E_RecordNotificationInteractions";}
		|{n: Prelude.CF_TE_Endpoint_3; t: Types.CF_TE_Endpoint_3_; v: "E_ReelWatch";}
		|{n: Prelude.CF_TE_Endpoint_3; t: Types.CF_TE_Endpoint_3_; v: "E_Search";}
		|{n: Prelude.CF_TE_Endpoint_3; t: Types.CF_TE_Endpoint_3_; v: "E_ShareEntityService";}
		|{n: Prelude.CF_TE_Endpoint_3; t: Types.CF_TE_Endpoint_3_; v: "E_SignalNavigation";}
		|{n: Prelude.CF_TE_Endpoint_3; t: Types.CF_TE_Endpoint_3_; v: "E_Subscribe";}
		|{n: Prelude.CF_TE_Endpoint_3; t: Types.CF_TE_Endpoint_3_; v: "E_UndoFeedback";}
		|{n: Prelude.CF_TE_Endpoint_3; t: Types.CF_TE_Endpoint_3_; v: "E_Upload";}
		|{n: Prelude.CF_TE_Endpoint_3; t: Types.CF_TE_Endpoint_3_; v: "E_Url";}
		|{n: Prelude.CF_TE_Endpoint_3; t: Types.CF_TE_Endpoint_3_; v: "E_Watch";}
		|{n: Prelude.CF_TE_Endpoint_3; t: Types.CF_TE_Endpoint_3_; v: "E_WatchPlaylist";}
		|{n: Prelude.CF_TE_Endpoint_3; t: Types.CF_TE_Endpoint_3_; v: "E_YpcGetCart";}
		|{n: Prelude.CF_TE_Endpoint_3; t: Types.CF_TE_Endpoint_3_; v: "E_YpcGetOffers";}
		|{n: Prelude.CF_TE_Endpoint_Opt_3; t: Types.CF_TE_Endpoint_Opt_3_; v: "C_Continuation";}
		|{n: Prelude.CF_T_Commands; t: Types.CF_T_Commands_; v: "DC_CommandExecutor";}
		|{n: Prelude.CF_T_Commands; t: Types.CF_T_Commands_; v: "DC_Executor";}
		|{n: Prelude.CF_T_GM; t: Types.CF_T_GM_; v: "GM_AccountMenu";}
		|{n: Prelude.CF_T_GM; t: Types.CF_T_GM_; v: "GM_CreateBackstagePost";}
		|{n: Prelude.CF_T_GM; t: Types.CF_T_GM_; v: "GM_Dislike";}
		|{n: Prelude.CF_T_GM; t: Types.CF_T_GM_; v: "GM_EditPlaylist";}
		|{n: Prelude.CF_T_GM; t: Types.CF_T_GM_; v: "GM_FlagGetForm";}
		|{n: Prelude.CF_T_GM; t: Types.CF_T_GM_; v: "GM_GetNotificationMenu";}
		|{n: Prelude.CF_T_GM; t: Types.CF_T_GM_; v: "GM_GetSharePanel";}
		|{n: Prelude.CF_T_GM; t: Types.CF_T_GM_; v: "GM_GetTranscript";}
		|{n: Prelude.CF_T_GM; t: Types.CF_T_GM_; v: "GM_GetUnseenNotificationCount";}
		|{n: Prelude.CF_T_GM; t: Types.CF_T_GM_; v: "GM_LikeLike";}
		|{n: Prelude.CF_T_GM; t: Types.CF_T_GM_; v: "GM_Next";}
		|{n: Prelude.CF_T_GM; t: Types.CF_T_GM_; v: "GM_RemoveLike";}
		|{n: Prelude.CF_T_GM; t: Types.CF_T_GM_; v: "GM_Subscribe";}
		|{n: Prelude.CF_T_Icon; t: Types.CF_T_Icon_; v: "DMD_Badge_LiveNow";}
		|{n: Prelude.CF_T_Icon; t: Types.CF_T_Icon_; v: "DMD_Badge_Verified";}
		|{n: Prelude.CF_T_Icon; t: Types.CF_T_Icon_; v: "DMD_Badge_VerifiedArtist";}
		|{n: Prelude.CF_T_Icon; t: Types.CF_T_Icon_; v: "D_Guide_CollapseIcon";}
		|{n: Prelude.CF_T_Icon; t: Types.CF_T_Icon_; v: "D_Guide_ExpandIcon";}
		|{n: Prelude.CF_T_Icon; t: Types.CF_T_Icon_; v: "D_Icon:ADD_TO_QUEUE_TAIL";}
		|{n: Prelude.CF_T_Icon; t: Types.CF_T_Icon_; v: "D_Icon:PLAYLIST_ADD_CHECK";}
		|{n: Prelude.CF_T_Icon; t: Types.CF_T_Icon_; v: "D_Icon_Check";}
		|{n: Prelude.CF_T_Icon; t: Types.CF_T_Icon_; v: "D_Icon_Mix";}
		|{n: Prelude.CF_T_Icon; t: Types.CF_T_Icon_; v: "D_Icon_Search";}
		|{n: Prelude.CF_T_Icon; t: Types.CF_T_Icon_; v: "D_Icon_WatchLater";}
		|{n: Prelude.CF_T_Icon; t: Types.CF_T_Icon_; v: "D_Icon_YoutubeLogo";}
		|{n: Prelude.CF_T_Icon; t: Types.CF_T_Icon_; v: "D_RichMetadata_BoxArt";}
		|{n: Prelude.CF_T_Icon; t: Types.CF_T_Icon_; v: "D_RichMetadata_Topic";}
		|{n: Prelude.CF_T_Icon_Any; t: Types.CF_T_Icon_Any_; v: "D_GuideEntry_WithIcon:icon";}
		|{n: Prelude.CF_T_Icon_Any; t: Types.CF_T_Icon_Any_; v: "D_GuideEntry_WithNavEP:icon";}
		|{n: Prelude.CF_T_Icon_Any; t: Types.CF_T_Icon_Any_; v: "D_Icon_Button";}
		|{n: Prelude.CF_T_Icon_Any; t: Types.CF_T_Icon_Any_; v: "D_Icon_ThumbnailOverlaySidePanel";}
		|{n: Prelude.CF_T_Items; t: Types.CF_T_Items_; v: "D_ProfileColumn";}
		|{n: Prelude.CF_T_Items_TP; t: Types.CF_T_Items_TP_; v: "R_CompactLink_Items";}
		|{n: Prelude.CF_T_SE_Signal; t: Types.CF_T_SE_Signal_; v: "D_GuideEntry_WithIcon.SE_Signal";}
		|{n: Prelude.CF_T_SE_Signal; t: Types.CF_T_SE_Signal_; v: "D_NotificationTopbarButton.U_UnseenCount.T_SE_Signal";}
		|{n: Prelude.CF_T_SE_Signal; t: Types.CF_T_SE_Signal_; v: "D_NotificationTopbarButton.menuRequest.T_SE_Signal";}
		|{n: Prelude.CF_T_SE_Signal; t: Types.CF_T_SE_Signal_; v: "D_ThumbnailOverlayToggleButton_UntoggledPrefix_2";}
		|{n: Prelude.CF_T_SE_Signal; t: Types.CF_T_SE_Signal_; v: "D_TopbarMenuButton.SE_Signal";}
		|{n: Prelude.CF_T_SE_Signal; t: Types.CF_T_SE_Signal_; v: "E_SignalService_SendPost";}
		|{n: Prelude.CF_T_SE_Signal; t: Types.CF_T_SE_Signal_; v: "GC_Button.SE_Signal";}
		|{n: Prelude.CF_T_WCM; t: Types.CF_T_WCM_; v: "M_AccountMenu";}
		|{n: Prelude.CF_T_WCM; t: Types.CF_T_WCM_; v: "M_AddToPlaylistService";}
		|{n: Prelude.CF_T_WCM; t: Types.CF_T_WCM_; v: "M_CreateBackstagePost";}
		|{n: Prelude.CF_T_WCM; t: Types.CF_T_WCM_; v: "M_CreatePlaylist";}
		|{n: Prelude.CF_T_WCM; t: Types.CF_T_WCM_; v: "M_EditPlaylist";}
		|{n: Prelude.CF_T_WCM; t: Types.CF_T_WCM_; v: "M_Feedback";}
		|{n: Prelude.CF_T_WCM; t: Types.CF_T_WCM_; v: "M_FlagGetForm";}
		|{n: Prelude.CF_T_WCM; t: Types.CF_T_WCM_; v: "M_GetNotificationMenu";}
		|{n: Prelude.CF_T_WCM; t: Types.CF_T_WCM_; v: "M_GetSharePanel";}
		|{n: Prelude.CF_T_WCM; t: Types.CF_T_WCM_; v: "M_GetTranscript";}
		|{n: Prelude.CF_T_WCM; t: Types.CF_T_WCM_; v: "M_GetUnseenNotificationCount";}
		|{n: Prelude.CF_T_WCM; t: Types.CF_T_WCM_; v: "M_Like";}
		|{n: Prelude.CF_T_WCM; t: Types.CF_T_WCM_; v: "M_Next";}
		|{n: Prelude.CF_T_WCM; t: Types.CF_T_WCM_; v: "M_RecordInteractions";}
		|{n: Prelude.CF_T_WCM; t: Types.CF_T_WCM_; v: "M_SendPost";}
		|{n: Prelude.CF_T_WCM; t: Types.CF_T_WCM_; v: "M_SetSetting";}
		|{n: Prelude.CF_T_WCM; t: Types.CF_T_WCM_; v: "M_Subscribe";}
		|{n: Prelude.CF_T_WCM; t: Types.CF_T_WCM_; v: "M_UserFeedback";}
		|{n: Prelude.CF_T_WCM; t: Types.CF_T_WCM_; v: "M_VE37414";}
		|{n: Prelude.CF_T_WCM; t: Types.CF_T_WCM_; v: "M_VE3832_Watch";}
		|{n: Prelude.CF_T_WCM; t: Types.CF_T_WCM_; v: "M_VE3832_WatchPlaylist";}
		|{n: Prelude.CF_T_WCM; t: Types.CF_T_WCM_; v: "M_VE4724";}
		|{n: Prelude.CF_T_WCM; t: Types.CF_T_WCM_; v: "M_VE83769";}
		|{n: Prelude.CF_T_WCM; t: Types.CF_T_WCM_; v: "M_YpcGetCart";}
		|{n: Prelude.CF_T_WCM_Unpack; t: Types.CF_T_WCM_Unpack_; v: "MG_Survey_CMD";}
		|{n: Prelude.CF_onMissingIcon; t: Types.CF_onMissingIcon_; v: "D_GuideEntry_WithIcon";}
		|{n: Prelude.CF_onMissingIcon; t: Types.CF_onMissingIcon_; v: "D_GuideEntry_WithNavEP";}
		|{n: Prelude.CF_onMissingIcon; t: Types.CF_onMissingIcon_; v: "D_ThumbnailOverlaySidePanel";}
		|{n: Prelude.CF_parse_identifier; t: Types.CF_parse_identifier_; v: "D_EngagementPanelSectionList";}
		;
}
