import {GenNS} from "./out_support.js"; export {GenNS};
export namespace Gen {
	export type CF_Generated=
		|{n: "CF_D_CaseGen"; t: CF_D_CaseGen; v: "AD_ChangeEngagementPanelVisibility.visibility";}
		|{n: "CF_D_CaseGen"; t: CF_D_CaseGen; v: "DE_SignalNavigation.signal";}
		|{n: "CF_D_CaseGen"; t: CF_D_CaseGen; v: "D_EngagementPanelTargetId:AD_ChangeEngagementPanelVisibility.targetId";}
		|{n: "CF_D_CaseGen"; t: CF_D_CaseGen; v: "D_GuideEntry_TargetId";}
		|{n: "CF_D_CaseGen"; t: CF_D_CaseGen; v: "D_PlayabilityStatus.reason";}
		|{n: "CF_D_CaseGen"; t: CF_D_CaseGen; v: "D_ReelPlayerOverlay";}
		|{n: "CF_D_CaseGen"; t: CF_D_CaseGen; v: "D_RichMetadata";}
		|{n: "CF_D_CaseGen"; t: CF_D_CaseGen; v: "D_RichShelf.icon";}
		|{n: "CF_D_CaseGen"; t: CF_D_CaseGen; v: "D_RichShelf.rowIndex";}
		|{n: "CF_D_CaseGen"; t: CF_D_CaseGen; v: "D_TargetIdStr:targetId";}
		|{n: "CF_D_CaseGen"; t: CF_D_CaseGen; v: "D_TargetIdStr:targetId:EngagementPanel";}
		|{n: "CF_D_CaseGen"; t: CF_D_CaseGen; v: "D_TargetIdStr:targetId:EngagementPanel:MacroMarkers";}
		|{n: "CF_D_CaseGen"; t: CF_D_CaseGen; v: "D_YtStudio_Url";}
		|{n: "CF_D_CaseGen"; t: CF_D_CaseGen; v: "S_VideoGoodPutShape.sparams";}
		|{n: "CF_D_CaseGen"; t: CF_D_CaseGen; v: "g_case:google_video:host_partition";}
		|{n: "CF_D_CaseGen"; t: CF_D_CaseGen; v: "js_gen_case:log_videoplayback:D_VideoPlaybackShape_LS_Params.mn.host_partition";}
		|{n: "CF_D_ChipCloudChip_Omit"; t: CF_D_ChipCloudChip_Omit; v: "D_ChipCloudChip_WithSelection";}
		|{n: "CF_D_CustomEmoji"; t: CF_D_CustomEmoji; v: "D_CustomEmoji";}
		|{n: "CF_D_CustomEmoji"; t: CF_D_CustomEmoji; v: "D_LiveChatEmoji";}
		|{n: "CF_D_GuideEntry"; t: CF_D_GuideEntry; v: "D_GuideEntry";}
		|{n: "CF_D_GuideEntry"; t: CF_D_GuideEntry; v: "D_GuideEntry_WithIcon";}
		|{n: "CF_D_GuideEntry"; t: CF_D_GuideEntry; v: "D_GuideEntry_WithPrimary";}
		|{n: "CF_D_Link"; t: CF_D_Link; v: "D_CompactLink";}
		|{n: "CF_D_Link"; t: CF_D_Link; v: "D_CompactLink.Styled";}
		|{n: "CF_D_Menu_Omit"; t: CF_D_Menu_Omit; v: "D_CompactRadio";}
		|{n: "CF_D_Menu_Omit"; t: CF_D_Menu_Omit; v: "D_CompactVideo";}
		|{n: "CF_D_Menu_Omit"; t: CF_D_Menu_Omit; v: "D_PlayerOverlayAutoplay";}
		|{n: "CF_D_Menu_Omit"; t: CF_D_Menu_Omit; v: "D_PlaylistSidebarPrimaryInfo";}
		|{n: "CF_D_Menu_Omit"; t: CF_D_Menu_Omit; v: "D_Radio";}
		|{n: "CF_D_Params"; t: CF_D_Params; v: "DE_AddUpcomingEventReminder";}
		|{n: "CF_D_Params"; t: CF_D_Params; v: "DE_GetReportForm";}
		|{n: "CF_D_Params"; t: CF_D_Params; v: "DE_GetTranscript";}
		|{n: "CF_D_Params"; t: CF_D_Params; v: "DE_RemoveUpcomingEventReminder";}
		|{n: "CF_D_Params"; t: CF_D_Params; v: "DE_YpcGetOffers";}
		|{n: "CF_D_Params"; t: CF_D_Params; v: "DE_YpcGetOfflineUpsell";}
		|{n: "CF_D_Playlist_Omit"; t: CF_D_Playlist_Omit; v: "D_CompactPlaylist";}
		|{n: "CF_D_STR"; t: CF_D_STR; v: "D_ChannelId";}
		|{n: "CF_D_STR"; t: CF_D_STR; v: "D_RadioShareUrl";}
		|{n: "CF_D_STR"; t: CF_D_STR; v: "D_YoutubeKidsUrl";}
		|{n: "CF_D_STR"; t: CF_D_STR; v: "GU_YoutubeUrlRedirect";}
		|{n: "CF_D_Video_Handle"; t: CF_D_Video_Handle; v: "D_Video_Other";}
		|{n: "CF_D_Video_Handle"; t: CF_D_Video_Handle; v: "D_Video_Other:isWatched";}
		|{n: "CF_D_Video_Handle"; t: CF_D_Video_Handle; v: "D_Video_With:accessibility";}
		|{n: "CF_D_Video_Handle"; t: CF_D_Video_Handle; v: "D_Video_With:accessibility:isWatched";}
		|{n: "CF_D_Video_Handle"; t: CF_D_Video_Handle; v: "D_Video_With:owner";}
		|{n: "CF_D_Video_Handle"; t: CF_D_Video_Handle; v: "D_Video_With:owner:isWatched";}
		|{n: "CF_D_Video_Handle"; t: CF_D_Video_Handle; v: "D_Video_With:videoId";}
		|{n: "CF_D_Video_Handle"; t: CF_D_Video_Handle; v: "D_Video_With:videoId:descriptionSnippet";}
		|{n: "CF_D_Video_Handle"; t: CF_D_Video_Handle; v: "D_Video_With:videoId:descriptionSnippet:isWatched";}
		|{n: "CF_D_Video_Handle"; t: CF_D_Video_Handle; v: "D_Video_With:videoId:isWatched";}
		|{n: "CF_D_Video_Handle"; t: CF_D_Video_Handle; v: "D_Video_With:videoId:topStandaloneBadge";}
		|{n: "CF_D_Video_Handle"; t: CF_D_Video_Handle; v: "D_Video_With:videoId:topStandaloneBadge:isWatched";}
		|{n: "CF_GE_ResponseReceived"; t: CF_GE_ResponseReceived; v: "RS_Browse";}
		|{n: "CF_GE_ResponseReceived"; t: CF_GE_ResponseReceived; v: "RS_Next";}
		|{n: "CF_GE_ResponseReceived"; t: CF_GE_ResponseReceived; v: "RS_Watch";}
		|{n: "CF_L_TP_Params"; t: CF_L_TP_Params; v: "B_HrefUrl.url";}
		|{n: "CF_L_TP_Params"; t: CF_L_TP_Params; v: "DD_Streaming";}
		|{n: "CF_L_TP_Params"; t: CF_L_TP_Params; v: "D_AboutThisAd";}
		|{n: "CF_L_TP_Params"; t: CF_L_TP_Params; v: "D_AdaptiveFormatItem";}
		|{n: "CF_L_TP_Params"; t: CF_L_TP_Params; v: "D_AdaptiveFormatItem:signatureCipher";}
		|{n: "CF_L_TP_Params"; t: CF_L_TP_Params; v: "D_CardCollection";}
		|{n: "CF_L_TP_Params"; t: CF_L_TP_Params; v: "D_Channel_MD.channelConversionUrl";}
		|{n: "CF_L_TP_Params"; t: CF_L_TP_Params; v: "D_ClientForecastingAd.impressionUrl";}
		|{n: "CF_L_TP_Params"; t: CF_L_TP_Params; v: "D_CommentsHeader";}
		|{n: "CF_L_TP_Params"; t: CF_L_TP_Params; v: "D_CommonConfig.url";}
		|{n: "CF_L_TP_Params"; t: CF_L_TP_Params; v: "D_FormatItem";}
		|{n: "CF_L_TP_Params"; t: CF_L_TP_Params; v: "D_FormatItem:signatureCipher";}
		|{n: "CF_L_TP_Params"; t: CF_L_TP_Params; v: "D_ImpressionCommand:LoggingUrlItem";}
		|{n: "CF_L_TP_Params"; t: CF_L_TP_Params; v: "D_PlayerMicroformat";}
		|{n: "CF_L_TP_Params"; t: CF_L_TP_Params; v: "GU_Url";}
		|{n: "CF_L_TP_Params"; t: CF_L_TP_Params; v: "RS_Page_Watch";}
		|{n: "CF_L_TP_Params"; t: CF_L_TP_Params; v: "R_WatchPage_VE3832";}
		|{n: "CF_M_s"; t: CF_M_s; v: "AD_AccountItem";}
		|{n: "CF_M_s"; t: CF_M_s; v: "AD_AddChatItem";}
		|{n: "CF_M_s"; t: CF_M_s; v: "AD_AddToGuideSection";}
		|{n: "CF_M_s"; t: CF_M_s; v: "AD_ChangeEngagementPanelVisibility";}
		|{n: "CF_M_s"; t: CF_M_s; v: "AD_Description";}
		|{n: "CF_M_s"; t: CF_M_s; v: "AD_Notification";}
		|{n: "CF_M_s"; t: CF_M_s; v: "AD_ReplayChatItem";}
		|{n: "CF_M_s"; t: CF_M_s; v: "AD_SendFeedback";}
		|{n: "CF_M_s"; t: CF_M_s; v: "AD_SetActivePanelItem";}
		|{n: "CF_M_s"; t: CF_M_s; v: "AD_ShowEngagementPanelScrim";}
		|{n: "CF_M_s"; t: CF_M_s; v: "AD_Signal";}
		|{n: "CF_M_s"; t: CF_M_s; v: "AD_SubscribeButton";}
		|{n: "CF_M_s"; t: CF_M_s; v: "AD_UpdateCommentVote";}
		|{n: "CF_M_s"; t: CF_M_s; v: "AD_UpdateEngagementPanel";}
		|{n: "CF_M_s"; t: CF_M_s; v: "AD_UpdateNotificationsUnseenCount";}
		|{n: "CF_M_s"; t: CF_M_s; v: "AS_PlaylistDescription";}
		|{n: "CF_M_s"; t: CF_M_s; v: "AS_PlaylistName";}
		|{n: "CF_M_s"; t: CF_M_s; v: "AS_PlaylistPrivacy";}
		|{n: "CF_M_s"; t: CF_M_s; v: "AS_PlaylistVideoOrder";}
		|{n: "CF_M_s"; t: CF_M_s; v: "AU_EngagementPanel";}
		|{n: "CF_M_s"; t: CF_M_s; v: "AU_ToggleButtonTextData";}
		|{n: "CF_M_s"; t: CF_M_s; v: "A_AddVideo";}
		|{n: "CF_M_s"; t: CF_M_s; v: "A_BrowseFeed";}
		|{n: "CF_M_s"; t: CF_M_s; v: "A_CommentsSectionContinuation";}
		|{n: "CF_M_s"; t: CF_M_s; v: "A_CopyFromPlaylist";}
		|{n: "CF_M_s"; t: CF_M_s; v: "A_RemoveVideoByVideoId";}
		|{n: "CF_M_s"; t: CF_M_s; v: "A_WatchNext";}
		|{n: "CF_M_s"; t: CF_M_s; v: "B_Hack";}
		|{n: "CF_M_s"; t: CF_M_s; v: "B_TagObj";}
		|{n: "CF_M_s"; t: CF_M_s; v: "CF_H_a";}
		|{n: "CF_M_s"; t: CF_M_s; v: "CF_RS_Page_Browse";}
		|{n: "CF_M_s"; t: CF_M_s; v: "CF_T_Attachment";}
		|{n: "CF_M_s"; t: CF_M_s; v: "C_Executor";}
		|{n: "CF_M_s"; t: CF_M_s; v: "C_GetSurvey";}
		|{n: "CF_M_s"; t: CF_M_s; v: "C_ScrollToEngagementPanel";}
		|{n: "CF_M_s"; t: CF_M_s; v: "C_ShowReloadUi";}
		|{n: "CF_M_s"; t: CF_M_s; v: "DB_SI_EngagementPanel";}
		|{n: "CF_M_s"; t: CF_M_s; v: "DC_AddFollowUpSurvey";}
		|{n: "CF_M_s"; t: CF_M_s; v: "DC_AddToPlaylist";}
		|{n: "CF_M_s"; t: CF_M_s; v: "DC_AdsControlFlowOpportunityReceived";}
		|{n: "CF_M_s"; t: CF_M_s; v: "DC_ChangeKeyedMarkersVisibility";}
		|{n: "CF_M_s"; t: CF_M_s; v: "DC_ChangeMarkersVisibility";}
		|{n: "CF_M_s"; t: CF_M_s; v: "DC_Continuation";}
		|{n: "CF_M_s"; t: CF_M_s; v: "DC_Continuation_Browse";}
		|{n: "CF_M_s"; t: CF_M_s; v: "DC_Continuation_ReelWatchSeq";}
		|{n: "CF_M_s"; t: CF_M_s; v: "DC_Continuation_WatchNext";}
		|{n: "CF_M_s"; t: CF_M_s; v: "DC_EngagementPanelHeaderShowNavigationButton";}
		|{n: "CF_M_s"; t: CF_M_s; v: "DC_Generic_CTP";}
		|{n: "CF_M_s"; t: CF_M_s; v: "DC_GetPdgBuyFlow";}
		|{n: "CF_M_s"; t: CF_M_s; v: "DC_Invalidation";}
		|{n: "CF_M_s"; t: CF_M_s; v: "DC_LiveChat";}
		|{n: "CF_M_s"; t: CF_M_s; v: "DC_LiveChatReplay";}
		|{n: "CF_M_s"; t: CF_M_s; v: "DC_LoadMarkers";}
		|{n: "CF_M_s"; t: CF_M_s; v: "DC_RelatedChip";}
		|{n: "CF_M_s"; t: CF_M_s; v: "DC_ReloadContinuationItems";}
		|{n: "CF_M_s"; t: CF_M_s; v: "DC_RepeatChapter";}
		|{n: "CF_M_s"; t: CF_M_s; v: "DC_ResetChannelUnreadCount";}
		|{n: "CF_M_s"; t: CF_M_s; v: "DC_ScrollToEngagementPanel";}
		|{n: "CF_M_s"; t: CF_M_s; v: "DC_SectionList_SearchFeed";}
		|{n: "CF_M_s"; t: CF_M_s; v: "DC_Timed";}
		|{n: "CF_M_s"; t: CF_M_s; v: "DC_UpdateToggleButtonState";}
		|{n: "CF_M_s"; t: CF_M_s; v: "DD_Streaming";}
		|{n: "CF_M_s"; t: CF_M_s; v: "DE_AddToPlaylistService";}
		|{n: "CF_M_s"; t: CF_M_s; v: "DE_CreateCommentReplyDialog";}
		|{n: "CF_M_s"; t: CF_M_s; v: "DE_Feedback";}
		|{n: "CF_M_s"; t: CF_M_s; v: "DE_GetNotificationMenu";}
		|{n: "CF_M_s"; t: CF_M_s; v: "DE_MutationDelete";}
		|{n: "CF_M_s"; t: CF_M_s; v: "DE_NotificationOptOut";}
		|{n: "CF_M_s"; t: CF_M_s; v: "DE_PerformCommentAction";}
		|{n: "CF_M_s"; t: CF_M_s; v: "DE_RecordNotificationInteractions";}
		|{n: "CF_M_s"; t: CF_M_s; v: "DE_Search";}
		|{n: "CF_M_s"; t: CF_M_s; v: "DE_ShareEntityService";}
		|{n: "CF_M_s"; t: CF_M_s; v: "DE_Subscribe";}
		|{n: "CF_M_s"; t: CF_M_s; v: "DE_SuperThanksSelectedTier";}
		|{n: "CF_M_s"; t: CF_M_s; v: "DE_UndoFeedback";}
		|{n: "CF_M_s"; t: CF_M_s; v: "DE_Unsubscribe";}
		|{n: "CF_M_s"; t: CF_M_s; v: "DE_UserFeedback";}
		|{n: "CF_M_s"; t: CF_M_s; v: "DE_VE11487";}
		|{n: "CF_M_s"; t: CF_M_s; v: "DE_VE23462";}
		|{n: "CF_M_s"; t: CF_M_s; v: "DE_VE3611";}
		|{n: "CF_M_s"; t: CF_M_s; v: "DE_VE37414_ReelWatch";}
		|{n: "CF_M_s"; t: CF_M_s; v: "DE_VE3832_Watch";}
		|{n: "CF_M_s"; t: CF_M_s; v: "DE_VE3854";}
		|{n: "CF_M_s"; t: CF_M_s; v: "DE_VE42352";}
		|{n: "CF_M_s"; t: CF_M_s; v: "DE_VE5754";}
		|{n: "CF_M_s"; t: CF_M_s; v: "DE_VE6827";}
		|{n: "CF_M_s"; t: CF_M_s; v: "DE_VE83769_Url";}
		|{n: "CF_M_s"; t: CF_M_s; v: "DE_VE96368";}
		|{n: "CF_M_s"; t: CF_M_s; v: "DE_WatchPlaylist";}
		|{n: "CF_M_s"; t: CF_M_s; v: "DMD_AdSlot";}
		|{n: "CF_M_s"; t: CF_M_s; v: "DMD_Badge";}
		|{n: "CF_M_s"; t: CF_M_s; v: "DMD_RowContainer";}
		|{n: "CF_M_s"; t: CF_M_s; v: "DR_DC_EntityBatchUpdate";}
		|{n: "CF_M_s"; t: CF_M_s; v: "DS_CreatePlaylist";}
		|{n: "CF_M_s"; t: CF_M_s; v: "DS_EY_MacroMarkersList";}
		|{n: "CF_M_s"; t: CF_M_s; v: "DS_EY_PlaylistLoop";}
		|{n: "CF_M_s"; t: CF_M_s; v: "DS_EY_Subscription";}
		|{n: "CF_M_s"; t: CF_M_s; v: "DS_EY_TranscriptSearchBox";}
		|{n: "CF_M_s"; t: CF_M_s; v: "DS_EY_TranscriptTrackSelection";}
		|{n: "CF_M_s"; t: CF_M_s; v: "DU_BaseUrl";}
		|{n: "CF_M_s"; t: CF_M_s; v: "DU_MutationDelete";}
		|{n: "CF_M_s"; t: CF_M_s; v: "DU_MutationReplace";}
		|{n: "CF_M_s"; t: CF_M_s; v: "DU_UrlParams";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_AboutThisAd";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_ActionSetPlaylistVideoOrder";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_ActiveAccountHeader";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_ActiveView";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_AdBreakService";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_AdPlacement";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_AdPlacementConfig";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_AdSlot";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_AdSlotAndLayoutItem";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_AdTimeOffset";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_AdaptiveFormatItem";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_AddToPlaylist";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_AddToPlaylistCreate";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_AlertWithButton";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_AttBgChallenge";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_AttachmentElement";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_AudioConfig";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_AudioTrack";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_AudioTrackItem";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_AuthorCommentBadge";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_AutoplayContent";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_AutoplaySetItem";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_AutoplaySwitchButton";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_Botguard";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_BrowserMediaSession";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_Button";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_C4TabbedHeader";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_Cache_MD";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_CaptionTrackItem";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_Card";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_CardCollection";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_CarouselLockup";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_ChannelHeaderLinks";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_ChannelSwitcherHeader";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_ChannelSwitcherPage";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_ChannelThumbnailWithLink";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_Channel_MD";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_ChildVideo";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_ChipCloud";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_ChipCloudChip_WithNav";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_ChipCloudChip_WithSelection";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_ChipUniqueId";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_CinematicAnimationConfig";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_CinematicConfig";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_CinematicContainer";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_ClickLocationTarget";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_ClientForecastingAd";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_ClipAdState";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_ClipCreation";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_ClipCreationScrubber";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_ClipCreationTextInput";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_CommandRunItem";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_Comment";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_CommentActionButtons";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_CommentReplies";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_CommentReplyDialog";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_CommentSimplebox";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_CommentThread";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_CommentsEntryPointHeader";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_CommentsEntryPointTeaser";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_CommentsHeader";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_CommentsSimplebox";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_CompactLink.Styled.icon";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_CompactLink.Styled:omit";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_CompactLink.icon";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_ConfirmDialog";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_Continuation";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_ContinuationItem";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_CueRangeItem";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_DarkColorPalette:D_MacroMarkersListItem:dark";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_DarkColorPalette:D_PlaylistPanelVideo:dark";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_DarkColorPalette:D_Thumbnail:dark";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_DecoratedPlayerBar";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_DesktopTopbar";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_DesktopWatchAds";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_DismissalFollowUp";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_DismissalReasonText";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_DisplayAd";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_Dropdown";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_DropdownFormField";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_DynamicReadaheadConfig";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_EY_Offlineability";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_ElementResourceStatus";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_Emoji";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_EmojiImage";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_EmojiPicker";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_EmojiPickerCategory";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_EmojiPickerCategory:Global";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_EmojiPickerCategoryButton";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_EmojiPickerCategoryButton:ForChannel";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_EmojiPickerCategoryButton:targetId";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_EndScreenPlaylist";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_EndScreenVideo";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_Endscreen";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_EndscreenElement";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_EngagementPanelTitleHeader";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_ExpandableSurveyResponse";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_ExpandableTab";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_ExpandableVideoDescriptionBody";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_ExternalChannelId";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_Factoid";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_FancyDismissibleDialog";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_FeaturedChannel";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_FeedFilterChipBar";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_FeedNudge";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_FeedTabbedHeader";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_FeedbackResponseProcessedStatus";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_FormatItem";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_FrameworkUpdates";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_FusionSearchbox";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_GetSurvey";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_GhostGrid";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_GraftedVeItem";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_GuideCollapsibleEntry";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_GuideCollapsibleSectionEntry";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_GuideDownloadsEntry";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_GuideEntry";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_GuideEntryData";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_GuideEntry_WithIcon";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_GuideSection";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_GuideSubscriptionsSection";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_HeartbeatParams";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_HeroPlaylistThumbnail";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_Hint";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_HorizontalCardList";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_HotkeyDialog";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_HotkeyDialogSection";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_HotkeyDialogSectionOption";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_ImpressionCommand";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_InFeedAdLayout";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_InfoRow";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_InlineForm";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_InlineSurvey";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_InstreamVideoAd";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_InvalidationId";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_LayoutProperties";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_LearningResource";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_LightColorPalette:D_MacroMarkersListItem:light";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_LightColorPalette:D_PlaylistPanelVideo:light";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_LightColorPalette:D_Thumbnail:light";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_LikeApi";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_LikeButton";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_LikeButton.dislike";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_LikeButton.like";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_LinearAdSequence";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_LiveBroadcastDetails";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_LiveBroadcastingBadge";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_LiveChat";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_LiveChatHeader";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_LiveChatPlaceholderItem";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_LiveChatTextMessage";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_LiveChatViewerEngagementMessage";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_LivePlayerConfig";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_LiveStreamability";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_LoggingContext";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_LoggingDirectives";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_MP_MenuNotificationSection";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_MacroMarkersList";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_MacroMarkersListItem";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_MarkerItem";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_MarkersList";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_Menu";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_MenuFlexibleItem";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_MenuNavigationItem";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_MenuServiceItem";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_MenuServiceItem_Omit";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_Menu_WithItems";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_Menu_WithTargetId";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_MerchandiseItem";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_MerchandiseShelf";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_Message";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_MetadataRow";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_Microformat.ios";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_Microformat.url";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_Microformat_Other";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_Miniplayer";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_ModifiedSetItem";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_MovingThumbnail";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_MovingThumbnail_Thumbnails";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_MusicCarouselShelf";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_MusicQueue";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_MusicShelf";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_MusicThumbnail";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_Notification";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_NotificationMenu";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_NotificationMenuPopupMenuItem";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_NotificationMenu_Popup";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_NotificationMenu_PopupItem";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_NotificationText";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_NotificationTopbarButton";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_PageTopAdLayout";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_PaidContentOverlay";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_PdgBuyFlow";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_PdgBuyFlowHeader";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_PdgColorSlider";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_PdgCommentChip";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_PdgCommentOption";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_PdgCommentPreview";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_PivotButton";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_PlayabilityStatus";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_PlayerAnnotationsExpanded";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_PlayerAttestation";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_PlayerCaptionsTracklist";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_PlayerConfig";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_PlayerMicroformat";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_PlayerOverlay";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_PlayerOverlay:autoplay";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_PlayerOverlay:autoplay:decoratedPlayerBarRenderer";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_PlayerOverlay:decoratedPlayerBarRenderer";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_PlayerOverlayVideoDetails";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_PlaylistAddToOption";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_PlaylistContent";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_PlaylistEdit";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_PlaylistHeader";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_PlaylistLoopButton";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_PlaylistLoopButtonState";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_PlaylistPanel";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_PlaylistPanelVideo";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_PlaylistSidebar";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_PlaylistVideoThumbnail";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_Playlist_MD";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_PrimaryLinkItem";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_PrivacyDropdownItem";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_ProductList";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_ProductListItem";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_ProfileColumnStatsEntry";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_ProfileColumnUserInfo";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_ProfilePageHeaderInformation";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_PromotedSparklesWeb";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_QoeLoggingContext";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_Radio";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_RadioShareUrl";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_Range";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_ReelMultimixAttributionLabel";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_ReelPlayerHeader";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_ReelPlayerOverlay";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_ReloadContinuationData";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_RemarketingPing";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_ResourceStatusInResponseCheckData";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_RichGrid";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_RichItem";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_RichListHeader";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_RichMetadataRow";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_RichMetadata_BoxArt";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_RichMetadata_Topic";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_RichSection";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_RichShelf";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_RunAttestation";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_SearchBox";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_SectionList_BrowseFeed_History";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_SectionList_BrowseFeed_Subscriptions";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_SegmentedLikeDislikeButton";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_SerializedSlotAdServingDataEntry";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_SettingsSidebar";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_ShowEngagementPanel";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_SimpleCardContent";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_SimpleCardTeaser";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_SimpleMenuHeader";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_SortFilterSubMenu";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_SortFilterSubMenu_WithTargetId";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_SortFilterSubMenu_WithTargetId.MenuItem";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_SourcePivotHeader";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_Sources.sources[]";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_SponsorCommentBadge";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_StyleRunItem";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_SubFeedOption";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_SubFeedSelector";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_SubscribeButton";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_SubscribeButton_SubscribePrefix";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_SubscribeButton_SubscribedPrefix";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_SubscribeButton_UnsubscribePrefix.unsubscribe";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_SubscribeButton_UnsubscribedPrefix";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_SubscriptionButton";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_SubscriptionNotificationToggleButton";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_SuperVodBuyFlowContent";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_Tab_History";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_Tab_R_MusicQueue";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_Tab_Subscriptions";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_Tab_WhatToWatch";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_Tab_WithEndpoint";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_TemplateUpdate";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_TextHeader";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_TextInputFormField";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_TextRun";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_Thumbnail";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_ThumbnailItem";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_ThumbnailOverlayEndorsement";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_ThumbnailOverlayHoverText";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_ThumbnailOverlayInlineUnplayable";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_ThumbnailOverlaySidePanel";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_ThumbnailOverlayTimeStatus";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_ThumbnailOverlayToggleButton_ToggledPrefix";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_ThumbnailOverlayToggleButton_UntoggledPrefix_1";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_ThumbnailOverlayToggleButton_UntoggledPrefix_2";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_ThumbnailsList";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_TimedTextApi";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_TimestampWithNanos";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_ToggleButton";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_ToggleMenuServiceItem";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_TopbarLogo";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_TopbarMenuButton";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_TopbarMenuButton_MenuItem";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_TopicLink";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_Transcript";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_TranscriptSearchPanel";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_TranscriptSegment";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_TranscriptSegmentList";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_TranslationLanguage";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_TriggerCriteria";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_TwoColumnBrowseResults";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_TwoColumnWatchNextResults";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_UnifiedSharePanel";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_UrlAndElapsedMediaTime";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_VideoDescriptionHeader";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_VideoDescriptionMusicSection";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_VideoDetails";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_VideoInfoCardContent";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_VideoOwner";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_VideoOwner:1";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_VideoPlaybackShape";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_VideoPlaybackShape_LS_Params";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_VideoPlaybackShape_Other";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_VideoPlaybackShape_S_Params";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_VideoPrimaryInfo";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_VideoQualityPromo";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_VideoSecondaryInfo";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_VideoViewCount";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_Video_Owner";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_ViewCountFactoid";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_VoiceSearchDialog";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_VssLoggingContext";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_WatchEndpointMusicConfig";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_WatchNextEndScreen";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_WatchNextTabbedResults";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_WatchResults";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_WebPlayerActionsPorting";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_WebPlayerConfig";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_WebPrefetch";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_WebSearchboxConfig";}
		|{n: "CF_M_s"; t: CF_M_s; v: "D_YtConfig";}
		|{n: "CF_M_s"; t: CF_M_s; v: "E_LikeDislike";}
		|{n: "CF_M_s"; t: CF_M_s; v: "E_LikeIndifferent";}
		|{n: "CF_M_s"; t: CF_M_s; v: "E_LikeLike";}
		|{n: "CF_M_s"; t: CF_M_s; v: "E_Pinging";}
		|{n: "CF_M_s"; t: CF_M_s; v: "E_SetSettingAutonavForDesktop";}
		|{n: "CF_M_s"; t: CF_M_s; v: "E_Watch";}
		|{n: "CF_M_s"; t: CF_M_s; v: "GA_Continuation_CommentRepliesItem";}
		|{n: "CF_M_s"; t: CF_M_s; v: "GD_RC_SectionList";}
		|{n: "CF_M_s"; t: CF_M_s; v: "GD_RC_SectionList_p2";}
		|{n: "CF_M_s"; t: CF_M_s; v: "GM_Search";}
		|{n: "CF_M_s"; t: CF_M_s; v: "GM_Url";}
		|{n: "CF_M_s"; t: CF_M_s; v: "GM_VE11487";}
		|{n: "CF_M_s"; t: CF_M_s; v: "GM_VE12924";}
		|{n: "CF_M_s"; t: CF_M_s; v: "GM_VE23462";}
		|{n: "CF_M_s"; t: CF_M_s; v: "GM_VE3611";}
		|{n: "CF_M_s"; t: CF_M_s; v: "GM_VE37414";}
		|{n: "CF_M_s"; t: CF_M_s; v: "GM_VE3832";}
		|{n: "CF_M_s"; t: CF_M_s; v: "GM_VE3854";}
		|{n: "CF_M_s"; t: CF_M_s; v: "GM_VE42352";}
		|{n: "CF_M_s"; t: CF_M_s; v: "GM_VE4724";}
		|{n: "CF_M_s"; t: CF_M_s; v: "GM_VE5754";}
		|{n: "CF_M_s"; t: CF_M_s; v: "GM_VE6827";}
		|{n: "CF_M_s"; t: CF_M_s; v: "GM_VE83769";}
		|{n: "CF_M_s"; t: CF_M_s; v: "GM_VE96368";}
		|{n: "CF_M_s"; t: CF_M_s; v: "GT_ShortsSurfaceIdentifier";}
		|{n: "CF_M_s"; t: CF_M_s; v: "G_Action_GetNotificationsMenu_Popup";}
		|{n: "CF_M_s"; t: CF_M_s; v: "G_ClientSignal";}
		|{n: "CF_M_s"; t: CF_M_s; v: "G_PR_TrackingObj_f16";}
		|{n: "CF_M_s"; t: CF_M_s; v: "G_Text";}
		|{n: "CF_M_s"; t: CF_M_s; v: "G_Watch_ResultsItem";}
		|{n: "CF_M_s"; t: CF_M_s; v: "G_Watch_SecondaryResults_Contents";}
		|{n: "CF_M_s"; t: CF_M_s; v: "G_Watch_SecondaryResults_Results";}
		|{n: "CF_M_s"; t: CF_M_s; v: "H_TrackingObj";}
		|{n: "CF_M_s"; t: CF_M_s; v: "MG_AdLayout";}
		|{n: "CF_M_s"; t: CF_M_s; v: "MP_AccountMenu";}
		|{n: "CF_M_s"; t: CF_M_s; v: "MP_SystemMenu";}
		|{n: "CF_M_s"; t: CF_M_s; v: "M_ResolveUrlCommand";}
		|{n: "CF_M_s"; t: CF_M_s; v: "M_VE3611";}
		|{n: "CF_M_s"; t: CF_M_s; v: "M_VE3854";}
		|{n: "CF_M_s"; t: CF_M_s; v: "NotchesItem";}
		|{n: "CF_M_s"; t: CF_M_s; v: "O_DU_Persistence";}
		|{n: "CF_M_s"; t: CF_M_s; v: "PD_continuation_params";}
		|{n: "CF_M_s"; t: CF_M_s; v: "PD_continuation_params.f11";}
		|{n: "CF_M_s"; t: CF_M_s; v: "PD_continuation_params.f14";}
		|{n: "CF_M_s"; t: CF_M_s; v: "PD_continuation_params.f3";}
		|{n: "CF_M_s"; t: CF_M_s; v: "PD_continuation_params_1";}
		|{n: "CF_M_s"; t: CF_M_s; v: "PD_continuation_params_2";}
		|{n: "CF_M_s"; t: CF_M_s; v: "PD_continuation_request_browse_token";}
		|{n: "CF_M_s"; t: CF_M_s; v: "PD_event_info";}
		|{n: "CF_M_s"; t: CF_M_s; v: "PD_invalidation_continuation";}
		|{n: "CF_M_s"; t: CF_M_s; v: "PD_invalidation_continuation.f9";}
		|{n: "CF_M_s"; t: CF_M_s; v: "PD_timed_continuation";}
		|{n: "CF_M_s"; t: CF_M_s; v: "PD_timed_continuation_f3";}
		|{n: "CF_M_s"; t: CF_M_s; v: "PD_watch_bin";}
		|{n: "CF_M_s"; t: CF_M_s; v: "PF_23n24n";}
		|{n: "CF_M_s"; t: CF_M_s; v: "PK_f1";}
		|{n: "CF_M_s"; t: CF_M_s; v: "PR_continuation_params";}
		|{n: "CF_M_s"; t: CF_M_s; v: "PR_continuation_request_browse_token";}
		|{n: "CF_M_s"; t: CF_M_s; v: "PR_watch_bin";}
		|{n: "CF_M_s"; t: CF_M_s; v: "PT_f1";}
		|{n: "CF_M_s"; t: CF_M_s; v: "PX_ad_data_info";}
		|{n: "CF_M_s"; t: CF_M_s; v: "PX_buy_flow_params";}
		|{n: "CF_M_s"; t: CF_M_s; v: "PX_upcoming_event_reminder_info";}
		|{n: "CF_M_s"; t: CF_M_s; v: "PX_watch_bin";}
		|{n: "CF_M_s"; t: CF_M_s; v: "PX_watch_next_token.f9";}
		|{n: "CF_M_s"; t: CF_M_s; v: "PX_watch_next_token_1";}
		|{n: "CF_M_s"; t: CF_M_s; v: "PX_watch_next_token_2";}
		|{n: "CF_M_s"; t: CF_M_s; v: "PX_watch_next_token_3";}
		|{n: "CF_M_s"; t: CF_M_s; v: "PX_watch_next_token_3.f1";}
		|{n: "CF_M_s"; t: CF_M_s; v: "PX_watch_next_token_4";}
		|{n: "CF_M_s"; t: CF_M_s; v: "PX_watch_next_token_5";}
		|{n: "CF_M_s"; t: CF_M_s; v: "PX_watch_next_token_6";}
		|{n: "CF_M_s"; t: CF_M_s; v: "PX_watch_next_token_f2";}
		|{n: "CF_M_s"; t: CF_M_s; v: "PX_watch_next_token_info";}
		|{n: "CF_M_s"; t: CF_M_s; v: "PX_watch_next_token_item";}
		|{n: "CF_M_s"; t: CF_M_s; v: "PX_watch_sequence_info";}
		|{n: "CF_M_s"; t: CF_M_s; v: "P_PX_watch_next_token_2_f37";}
		|{n: "CF_M_s"; t: CF_M_s; v: "P_ad_layout_ad_serving_data_entry";}
		|{n: "CF_M_s"; t: CF_M_s; v: "P_ad_slot_logging_data_serialized_slot_ad_serving_data_entry";}
		|{n: "CF_M_s"; t: CF_M_s; v: "P_bin_params_1";}
		|{n: "CF_M_s"; t: CF_M_s; v: "P_bin_params_1.f1";}
		|{n: "CF_M_s"; t: CF_M_s; v: "P_continuation_request_reel_watch_sequence_token";}
		|{n: "CF_M_s"; t: CF_M_s; v: "P_continuation_request_watch_next_token";}
		|{n: "CF_M_s"; t: CF_M_s; v: "P_create_backstage_post_params";}
		|{n: "CF_M_s"; t: CF_M_s; v: "P_create_comment_params";}
		|{n: "CF_M_s"; t: CF_M_s; v: "P_create_playlist_params";}
		|{n: "CF_M_s"; t: CF_M_s; v: "P_create_reply_params";}
		|{n: "CF_M_s"; t: CF_M_s; v: "P_dislike_params";}
		|{n: "CF_M_s"; t: CF_M_s; v: "P_dislike_params.f1";}
		|{n: "CF_M_s"; t: CF_M_s; v: "P_f3_PD_continuation_params";}
		|{n: "CF_M_s"; t: CF_M_s; v: "P_format_item_xtags";}
		|{n: "CF_M_s"; t: CF_M_s; v: "P_format_item_xtags.f1";}
		|{n: "CF_M_s"; t: CF_M_s; v: "P_get_notification_menu_ctoken";}
		|{n: "CF_M_s"; t: CF_M_s; v: "P_get_pdg_buy_flow_params";}
		|{n: "CF_M_s"; t: CF_M_s; v: "P_get_report_form_params";}
		|{n: "CF_M_s"; t: CF_M_s; v: "P_get_transcript_params";}
		|{n: "CF_M_s"; t: CF_M_s; v: "P_invalidation_continuation";}
		|{n: "CF_M_s"; t: CF_M_s; v: "P_like_params";}
		|{n: "CF_M_s"; t: CF_M_s; v: "P_logging_context_serialized_context_data";}
		|{n: "CF_M_s"; t: CF_M_s; v: "P_logging_context_serialized_context_data.f1";}
		|{n: "CF_M_s"; t: CF_M_s; v: "P_notification_add_upcoming_event_reminder_params";}
		|{n: "CF_M_s"; t: CF_M_s; v: "P_notification_opt_out";}
		|{n: "CF_M_s"; t: CF_M_s; v: "P_notification_record_interactions";}
		|{n: "CF_M_s"; t: CF_M_s; v: "P_notification_remove_upcoming_event_reminder_params";}
		|{n: "CF_M_s"; t: CF_M_s; v: "P_perform_comment_action";}
		|{n: "CF_M_s"; t: CF_M_s; v: "P_playability_status_context_params";}
		|{n: "CF_M_s"; t: CF_M_s; v: "P_playlist_edit_params";}
		|{n: "CF_M_s"; t: CF_M_s; v: "P_reel_params";}
		|{n: "CF_M_s"; t: CF_M_s; v: "P_reel_player_params";}
		|{n: "CF_M_s"; t: CF_M_s; v: "P_reel_sequence_params";}
		|{n: "CF_M_s"; t: CF_M_s; v: "P_remove_like_params";}
		|{n: "CF_M_s"; t: CF_M_s; v: "P_search_params";}
		|{n: "CF_M_s"; t: CF_M_s; v: "P_shorts_source_bp";}
		|{n: "CF_M_s"; t: CF_M_s; v: "P_subscribe_params";}
		|{n: "CF_M_s"; t: CF_M_s; v: "P_subscription_state_key";}
		|{n: "CF_M_s"; t: CF_M_s; v: "P_timed_continuation_data";}
		|{n: "CF_M_s"; t: CF_M_s; v: "P_transcript_params";}
		|{n: "CF_M_s"; t: CF_M_s; v: "P_transcript_track_selection_serialized_params";}
		|{n: "CF_M_s"; t: CF_M_s; v: "P_trending_bp";}
		|{n: "CF_M_s"; t: CF_M_s; v: "P_unsubscribe_params";}
		|{n: "CF_M_s"; t: CF_M_s; v: "P_ve_3611_params";}
		|{n: "CF_M_s"; t: CF_M_s; v: "P_ve_6827_params";}
		|{n: "CF_M_s"; t: CF_M_s; v: "P_watch_params";}
		|{n: "CF_M_s"; t: CF_M_s; v: "P_watch_player_params";}
		|{n: "CF_M_s"; t: CF_M_s; v: "P_watch_playlist_params";}
		|{n: "CF_M_s"; t: CF_M_s; v: "P_ypc_get_offers_params";}
		|{n: "CF_M_s"; t: CF_M_s; v: "Popup_DL_AboutThisAd";}
		|{n: "CF_M_s"; t: CF_M_s; v: "Popup_DL_DismissibleDialog";}
		|{n: "CF_M_s"; t: CF_M_s; v: "Popup_DL_MenuNavigation";}
		|{n: "CF_M_s"; t: CF_M_s; v: "Popup_GetAccountMenu";}
		|{n: "CF_M_s"; t: CF_M_s; v: "Popup_ShareEntityService";}
		|{n: "CF_M_s"; t: CF_M_s; v: "RCA_RelevantStateTags";}
		|{n: "CF_M_s"; t: CF_M_s; v: "RC_ConsistencyTokenJar";}
		|{n: "CF_M_s"; t: CF_M_s; v: "RC_MainAppWebResponseContext";}
		|{n: "CF_M_s"; t: CF_M_s; v: "RC_ResponseContext";}
		|{n: "CF_M_s"; t: CF_M_s; v: "RC_WR_ContextExtension";}
		|{n: "CF_M_s"; t: CF_M_s; v: "RD_MenuServiceItem";}
		|{n: "CF_M_s"; t: CF_M_s; v: "REG_AccountSwitcher";}
		|{n: "CF_M_s"; t: CF_M_s; v: "REG_DatasyncIds";}
		|{n: "CF_M_s"; t: CF_M_s; v: "RSB_EditPlaylist";}
		|{n: "CF_M_s"; t: CF_M_s; v: "RSG_GetUnseenCount";}
		|{n: "CF_M_s"; t: CF_M_s; v: "RSG_NotificationMenu";}
		|{n: "CF_M_s"; t: CF_M_s; v: "RSG_PdgBuyFlow";}
		|{n: "CF_M_s"; t: CF_M_s; v: "RSG_SearchSuggestions";}
		|{n: "CF_M_s"; t: CF_M_s; v: "RSG_SharePanel";}
		|{n: "CF_M_s"; t: CF_M_s; v: "RSG_SharePanel_Action";}
		|{n: "CF_M_s"; t: CF_M_s; v: "RSG_Survey";}
		|{n: "CF_M_s"; t: CF_M_s; v: "RSG_Transcript";}
		|{n: "CF_M_s"; t: CF_M_s; v: "RSL_Dislike";}
		|{n: "CF_M_s"; t: CF_M_s; v: "RSL_Like";}
		|{n: "CF_M_s"; t: CF_M_s; v: "RSL_RemoveLike";}
		|{n: "CF_M_s"; t: CF_M_s; v: "RSM_ChannelPreference";}
		|{n: "CF_M_s"; t: CF_M_s; v: "RS_AccountMenu";}
		|{n: "CF_M_s"; t: CF_M_s; v: "RS_AccountsList";}
		|{n: "CF_M_s"; t: CF_M_s; v: "RS_AttGet";}
		|{n: "CF_M_s"; t: CF_M_s; v: "RS_Browse";}
		|{n: "CF_M_s"; t: CF_M_s; v: "RS_Channel";}
		|{n: "CF_M_s"; t: CF_M_s; v: "RS_Feedback";}
		|{n: "CF_M_s"; t: CF_M_s; v: "RS_GetAddToPlaylist";}
		|{n: "CF_M_s"; t: CF_M_s; v: "RS_GetLiveChat";}
		|{n: "CF_M_s"; t: CF_M_s; v: "RS_Guide";}
		|{n: "CF_M_s"; t: CF_M_s; v: "RS_Next";}
		|{n: "CF_M_s"; t: CF_M_s; v: "RS_Page_Browse";}
		|{n: "CF_M_s"; t: CF_M_s; v: "RS_Page_Watch";}
		|{n: "CF_M_s"; t: CF_M_s; v: "RS_Player";}
		|{n: "CF_M_s"; t: CF_M_s; v: "RS_Playlist";}
		|{n: "CF_M_s"; t: CF_M_s; v: "RS_Reel";}
		|{n: "CF_M_s"; t: CF_M_s; v: "RS_ReelWatchSequence";}
		|{n: "CF_M_s"; t: CF_M_s; v: "RS_Search";}
		|{n: "CF_M_s"; t: CF_M_s; v: "RS_SearchPage";}
		|{n: "CF_M_s"; t: CF_M_s; v: "RS_SetSetting";}
		|{n: "CF_M_s"; t: CF_M_s; v: "RS_Settings";}
		|{n: "CF_M_s"; t: CF_M_s; v: "RS_ShortsPage";}
		|{n: "CF_M_s"; t: CF_M_s; v: "RS_Subscribe";}
		|{n: "CF_M_s"; t: CF_M_s; v: "RS_Subscribe_ActionItem_Action";}
		|{n: "CF_M_s"; t: CF_M_s; v: "RS_Success";}
		|{n: "CF_M_s"; t: CF_M_s; v: "RS_Unsubscribe";}
		|{n: "CF_M_s"; t: CF_M_s; v: "RS_UpdateMetadata";}
		|{n: "CF_M_s"; t: CF_M_s; v: "RS_Watch";}
		|{n: "CF_M_s"; t: CF_M_s; v: "RS_WatchReelItem";}
		|{n: "CF_M_s"; t: CF_M_s; v: "R_Obj_f19";}
		|{n: "CF_M_s"; t: CF_M_s; v: "R_PageTypeBrowse";}
		|{n: "CF_M_s"; t: CF_M_s; v: "R_PageTypeBrowse_Response";}
		|{n: "CF_M_s"; t: CF_M_s; v: "R_PageTypeChannel";}
		|{n: "CF_M_s"; t: CF_M_s; v: "R_PageTypePlaylist";}
		|{n: "CF_M_s"; t: CF_M_s; v: "R_PageTypeSearch";}
		|{n: "CF_M_s"; t: CF_M_s; v: "R_PageTypeSettings";}
		|{n: "CF_M_s"; t: CF_M_s; v: "R_PageTypeShorts";}
		|{n: "CF_M_s"; t: CF_M_s; v: "R_PageTypeWatch";}
		|{n: "CF_M_s"; t: CF_M_s; v: "R_PlaylistPage";}
		|{n: "CF_M_s"; t: CF_M_s; v: "R_SettingsPage";}
		|{n: "CF_M_s"; t: CF_M_s; v: "R_WatchPage_VE3832";}
		|{n: "CF_M_s"; t: CF_M_s; v: "SI_DB_EngagementPanel_Ads";}
		|{n: "CF_M_s"; t: CF_M_s; v: "SI_VE124975_EngagementPanel";}
		|{n: "CF_M_s"; t: CF_M_s; v: "SI_VE126250_EngagementPanel";}
		|{n: "CF_M_s"; t: CF_M_s; v: "SI_VE139722_EngagementPanel";}
		|{n: "CF_M_s"; t: CF_M_s; v: "SI_VE76278_EngagementPanel";}
		|{n: "CF_M_s"; t: CF_M_s; v: "SI_VE99999_EngagementPanel";}
		|{n: "CF_M_s"; t: CF_M_s; v: "S_Client_Popup";}
		|{n: "CF_M_s"; t: CF_M_s; v: "S_GetAccountMenu";}
		|{n: "CF_M_s"; t: CF_M_s; v: "S_VideoGoodPutShape";}
		|{n: "CF_M_s"; t: CF_M_s; v: "S_VoiceSearchPopup_Dialog";}
		|{n: "CF_M_s"; t: CF_M_s; v: "Settings_VE23462";}
		|{n: "CF_M_s"; t: CF_M_s; v: "Shorts_VE37414";}
		|{n: "CF_M_s"; t: CF_M_s; v: "Signal_GetNotificationsMenu";}
		|{n: "CF_M_s"; t: CF_M_s; v: "StateTag";}
		|{n: "CF_M_s"; t: CF_M_s; v: "TD_ItemSection_2_CommentsEntryPoint";}
		|{n: "CF_M_s"; t: CF_M_s; v: "TE_SignalService_I_0";}
		|{n: "CF_M_s"; t: CF_M_s; v: "TM_Visibility";}
		|{n: "CF_M_s"; t: CF_M_s; v: "TR_ItemSection";}
		|{n: "CF_M_s"; t: CF_M_s; v: "TX_sequence_info";}
		|{n: "CF_M_s"; t: CF_M_s; v: "T_Autoplay";}
		|{n: "CF_M_s"; t: CF_M_s; v: "T_BaseUrl";}
		|{n: "CF_M_s"; t: CF_M_s; v: "T_Command_TP";}
		|{n: "CF_M_s"; t: CF_M_s; v: "T_DE_SettingItem.407";}
		|{n: "CF_M_s"; t: CF_M_s; v: "T_OpenPopup_Toast";}
		|{n: "CF_M_s"; t: CF_M_s; v: "T_Playlist";}
		|{n: "CF_M_s"; t: CF_M_s; v: "T_SecondaryResults";}
		|{n: "CF_M_s"; t: CF_M_s; v: "T_Types";}
		|{n: "CF_M_s"; t: CF_M_s; v: "T_UrlWrappedValue";}
		|{n: "CF_M_s"; t: CF_M_s; v: "ToggleButton.state";}
		|{n: "CF_M_s"; t: CF_M_s; v: "V_BinaryTimestamp";}
		|{n: "CF_M_s"; t: CF_M_s; v: "V_ShortTimestamp";}
		|{n: "CF_M_s"; t: CF_M_s; v: "XP_EntityPayload_Any";}
		|{n: "CF_M_w"; t: CF_M_w; v: "D_ImpressionCap";}
		|{n: "CF_M_w"; t: CF_M_w; v: "GM_SendPost";}
		|{n: "CF_M_w"; t: CF_M_w; v: "GM_UserFeedback";}
		|{n: "CF_M_w"; t: CF_M_w; v: "G_AdditionalDataItem";}
		|{n: "CF_M_w"; t: CF_M_w; v: "G_EY_Entity_Any:G_EY_Entity";}
		|{n: "CF_M_w"; t: CF_M_w; v: "Unpack:T_WCM:CF_T_WCM_Unpack";}
		|{n: "CF_M_w"; t: CF_M_w; v: "Unpack:T_WCM:MG_Survey_CMD";}
		|{n: "CF_M_y"; t: CF_M_y; v: "AD_HideEnclosing";}
		|{n: "CF_M_y"; t: CF_M_y; v: "AD_HideEngagementPanelTargetId";}
		|{n: "CF_M_y"; t: CF_M_y; v: "AU_Description";}
		|{n: "CF_M_y"; t: CF_M_y; v: "AU_ToggleButtonText";}
		|{n: "CF_M_y"; t: CF_M_y; v: "AU_Viewership";}
		|{n: "CF_M_y"; t: CF_M_y; v: "AU_ViewershipData";}
		|{n: "CF_M_y"; t: CF_M_y; v: "B_HrefUrl";}
		|{n: "CF_M_y"; t: CF_M_y; v: "CD_Invalidation";}
		|{n: "CF_M_y"; t: CF_M_y; v: "CD_LiveChatReplay";}
		|{n: "CF_M_y"; t: CF_M_y; v: "CD_Next";}
		|{n: "CF_M_y"; t: CF_M_y; v: "CD_NextRadio";}
		|{n: "CF_M_y"; t: CF_M_y; v: "CD_PlayerSeek";}
		|{n: "CF_M_y"; t: CF_M_y; v: "CD_Reload";}
		|{n: "CF_M_y"; t: CF_M_y; v: "DC_Continuation";}
		|{n: "CF_M_y"; t: CF_M_y; v: "DC_Loop";}
		|{n: "CF_M_y"; t: CF_M_y; v: "DC_PlayerSeek";}
		|{n: "CF_M_y"; t: CF_M_y; v: "DC_ShowReelsCommentsOverlay";}
		|{n: "CF_M_y"; t: CF_M_y; v: "DC_ShowReloadUi";}
		|{n: "CF_M_y"; t: CF_M_y; v: "DE_CreateCommentReply";}
		|{n: "CF_M_y"; t: CF_M_y; v: "DE_PlaylistEditor";}
		|{n: "CF_M_y"; t: CF_M_y; v: "DE_VE5754";}
		|{n: "CF_M_y"; t: CF_M_y; v: "D_CanShare";}
		|{n: "CF_M_y"; t: CF_M_y; v: "D_EditableDetails";}
		|{n: "CF_M_y"; t: CF_M_y; v: "D_IgnoreNavigation";}
		|{n: "CF_M_y"; t: CF_M_y; v: "D_InfoCardIcon";}
		|{n: "CF_M_y"; t: CF_M_y; v: "D_MenuPopup";}
		|{n: "CF_M_y"; t: CF_M_y; v: "D_PlaylistByline";}
		|{n: "CF_M_y"; t: CF_M_y; v: "D_PlaylistPanelVideo";}
		|{n: "CF_M_y"; t: CF_M_y; v: "D_ProfilePageHeaderTitle";}
		|{n: "CF_M_y"; t: CF_M_y; v: "D_ProfilePageHeaderTitle_Content";}
		|{n: "CF_M_y"; t: CF_M_y; v: "D_RelatedChipCloud";}
		|{n: "CF_M_y"; t: CF_M_y; v: "D_StartSeconds";}
		|{n: "CF_M_y"; t: CF_M_y; v: "D_StreamSelectionConfig";}
		|{n: "CF_M_y"; t: CF_M_y; v: "D_StructuredDescriptionPlaylistLockup";}
		|{n: "CF_M_y"; t: CF_M_y; v: "D_Survey_Watch";}
		|{n: "CF_M_y"; t: CF_M_y; v: "D_ThumbnailOverlayBottomPanel";}
		|{n: "CF_M_y"; t: CF_M_y; v: "D_ThumbnailOverlayNowPlaying";}
		|{n: "CF_M_y"; t: CF_M_y; v: "D_ThumbnailOverlayResumePlayback";}
		|{n: "CF_M_y"; t: CF_M_y; v: "D_VideoId";}
		|{n: "CF_M_y"; t: CF_M_y; v: "R_ToggleButtonIdData";}
		|{n: "CF_M_y"; t: CF_M_y; v: "T_Item";}
		|{n: "CF_M_y"; t: CF_M_y; v: "UA_DateText";}
		|{n: "CF_M_y"; t: CF_M_y; v: "UA_DateTextData";}
		|{n: "CF_M_y"; t: CF_M_y; v: "UA_Title";}
		|{n: "CF_M_y"; t: CF_M_y; v: "UA_TitleData";}
		|{n: "CF_P_EntityKey"; t: CF_P_EntityKey; v: "P_aadc_guidelines_state_entity_key";}
		|{n: "CF_P_EntityKey"; t: CF_P_EntityKey; v: "P_change_markers_visibility_entity_key";}
		|{n: "CF_P_EntityKey"; t: CF_P_EntityKey; v: "P_entity_key";}
		|{n: "CF_P_EntityKey"; t: CF_P_EntityKey; v: "P_load_markers_entity_key";}
		|{n: "CF_P_EntityKey"; t: CF_P_EntityKey; v: "P_macro_marker_repeat_state_entity_key";}
		|{n: "CF_P_EntityKey"; t: CF_P_EntityKey; v: "P_macro_markers_list_entity_key";}
		|{n: "CF_P_EntityKey"; t: CF_P_EntityKey; v: "P_player_state_entity_key";}
		|{n: "CF_P_EntityKey"; t: CF_P_EntityKey; v: "P_playlist_loop_state_entity_key";}
		|{n: "CF_P_EntityKey"; t: CF_P_EntityKey; v: "P_subscribe_button_entity_key";}
		|{n: "CF_P_EntityKey"; t: CF_P_EntityKey; v: "P_transcript_track_selection_entity_key";}
		|{n: "CF_P_EntityKey"; t: CF_P_EntityKey; v: "P_view_count_entity_key";}
		|{n: "CF_RS_Page_Browse"; t: CF_RS_Page_Browse; v: "RS_Page_Browse";}
		|{n: "CF_RS_Page_Browse"; t: CF_RS_Page_Browse; v: "RS_VE3854_BrowsePage";}
		|{n: "CF_RS_Page_Browse"; t: CF_RS_Page_Browse; v: "RS_VE6827_BrowsePage";}
		|{n: "CF_RS_Page_Browse"; t: CF_RS_Page_Browse; v: "RS_VE96368_BrowsePage";}
		|{n: "CF_RS_Page_Type1"; t: CF_RS_Page_Type1; v: "RS_Page_Channel";}
		|{n: "CF_RS_Page_Type1"; t: CF_RS_Page_Type1; v: "R_PageTypeBrowse_Response";}
		|{n: "CF_TA_OpenPopup"; t: CF_TA_OpenPopup; v: "A_AboutThisAd";}
		|{n: "CF_TA_OpenPopup"; t: CF_TA_OpenPopup; v: "A_ConfirmDialog";}
		|{n: "CF_TA_OpenPopup"; t: CF_TA_OpenPopup; v: "A_FancyDismissibleDialog";}
		|{n: "CF_TA_OpenPopup"; t: CF_TA_OpenPopup; v: "A_GetAccountMenu";}
		|{n: "CF_TA_OpenPopup"; t: CF_TA_OpenPopup; v: "A_GetSystemMenu";}
		|{n: "CF_TA_OpenPopup"; t: CF_TA_OpenPopup; v: "DE_ShareEntityService";}
		|{n: "CF_TA_OpenPopup"; t: CF_TA_OpenPopup; v: "GA_MenuNavigationPopup";}
		|{n: "CF_TA_OpenPopup"; t: CF_TA_OpenPopup; v: "G_Action_GetNotificationsMenu";}
		|{n: "CF_TA_OpenPopup"; t: CF_TA_OpenPopup; v: "RSG_NotificationMenu_Action";}
		|{n: "CF_TA_OpenPopup"; t: CF_TA_OpenPopup; v: "RSM_ChannelPreference";}
		|{n: "CF_TA_OpenPopup"; t: CF_TA_OpenPopup; v: "TA_OpenPopup:R_PdgBuyFlow";}
		|{n: "CF_TA_OpenPopup"; t: CF_TA_OpenPopup; v: "TA_OpenPopup_Empty";}
		|{n: "CF_TA_Page"; t: CF_TA_Page; v: "AD_UpdateChannelSwitcherPage";}
		|{n: "CF_TD_ItemSection"; t: CF_TD_ItemSection; v: "TD_ItemSection_1<any>";}
		|{n: "CF_TD_ItemSection"; t: CF_TD_ItemSection; v: "TD_ItemSection_3<\"comment-item-section\",\"comments-section\">";}
		|{n: "CF_TD_ItemSection"; t: CF_TD_ItemSection; v: "TD_ItemSection_3<\"comment-item-section\",\"engagement-panel-comments-section\">";}
		|{n: "CF_TD_ItemSection"; t: CF_TD_ItemSection; v: "TD_ItemSection_3<\"sid-wn-chips\",\"watch-next-feed\">";}
		|{n: "CF_TD_Params"; t: CF_TD_Params; v: "DE_CreateBackstagePost";}
		|{n: "CF_TD_Params"; t: CF_TD_Params; v: "DE_CreateComment";}
		|{n: "CF_TD_Params"; t: CF_TD_Params; v: "DE_YpcGetCart";}
		|{n: "CF_TE_Endpoint_2"; t: CF_TE_Endpoint_2; v: "AU_NotificationsUnseenCount";}
		|{n: "CF_TE_Endpoint_2"; t: CF_TE_Endpoint_2; v: "A_AddChatItem";}
		|{n: "CF_TE_Endpoint_2"; t: CF_TE_Endpoint_2; v: "A_AddToGuideSection";}
		|{n: "CF_TE_Endpoint_2"; t: CF_TE_Endpoint_2; v: "A_AddToToast";}
		|{n: "CF_TE_Endpoint_2"; t: CF_TE_Endpoint_2; v: "A_AppendContinuationItems";}
		|{n: "CF_TE_Endpoint_2"; t: CF_TE_Endpoint_2; v: "A_ChangeEngagementPanelVisibility";}
		|{n: "CF_TE_Endpoint_2"; t: CF_TE_Endpoint_2; v: "A_HideEnclosing";}
		|{n: "CF_TE_Endpoint_2"; t: CF_TE_Endpoint_2; v: "A_HideEngagementPanelScrim";}
		|{n: "CF_TE_Endpoint_2"; t: CF_TE_Endpoint_2; v: "A_ReplaceEnclosing";}
		|{n: "CF_TE_Endpoint_2"; t: CF_TE_Endpoint_2; v: "A_SendFeedback";}
		|{n: "CF_TE_Endpoint_2"; t: CF_TE_Endpoint_2; v: "A_SetActivePanelItem";}
		|{n: "CF_TE_Endpoint_2"; t: CF_TE_Endpoint_2; v: "A_ShowEngagementPanelScrim";}
		|{n: "CF_TE_Endpoint_2"; t: CF_TE_Endpoint_2; v: "A_Signal";}
		|{n: "CF_TE_Endpoint_2"; t: CF_TE_Endpoint_2; v: "A_UndoFeedback";}
		|{n: "CF_TE_Endpoint_2"; t: CF_TE_Endpoint_2; v: "A_UpdateCommentVote";}
		|{n: "CF_TE_Endpoint_2"; t: CF_TE_Endpoint_2; v: "C_AddToPlaylist";}
		|{n: "CF_TE_Endpoint_2"; t: CF_TE_Endpoint_2; v: "C_AdsControlFlowOpportunityReceived";}
		|{n: "CF_TE_Endpoint_2"; t: CF_TE_Endpoint_2; v: "C_ChangeKeyedMarkersVisibility";}
		|{n: "CF_TE_Endpoint_2"; t: CF_TE_Endpoint_2; v: "C_ChangeMarkersVisibility";}
		|{n: "CF_TE_Endpoint_2"; t: CF_TE_Endpoint_2; v: "C_CommandExecutor";}
		|{n: "CF_TE_Endpoint_2"; t: CF_TE_Endpoint_2; v: "C_EngagementPanelHeaderShowNavigationButton";}
		|{n: "CF_TE_Endpoint_2"; t: CF_TE_Endpoint_2; v: "C_EntityUpdate";}
		|{n: "CF_TE_Endpoint_2"; t: CF_TE_Endpoint_2; v: "C_FilterChipTransform";}
		|{n: "CF_TE_Endpoint_2"; t: CF_TE_Endpoint_2; v: "C_FollowUp";}
		|{n: "CF_TE_Endpoint_2"; t: CF_TE_Endpoint_2; v: "C_LoadMarkers";}
		|{n: "CF_TE_Endpoint_2"; t: CF_TE_Endpoint_2; v: "C_Loop";}
		|{n: "CF_TE_Endpoint_2"; t: CF_TE_Endpoint_2; v: "C_RefreshPlaylist";}
		|{n: "CF_TE_Endpoint_2"; t: CF_TE_Endpoint_2; v: "C_RelatedChip";}
		|{n: "CF_TE_Endpoint_2"; t: CF_TE_Endpoint_2; v: "C_ReloadContinuationItems";}
		|{n: "CF_TE_Endpoint_2"; t: CF_TE_Endpoint_2; v: "C_RepeatChapter";}
		|{n: "CF_TE_Endpoint_2"; t: CF_TE_Endpoint_2; v: "C_ResetChannelUnreadCount";}
		|{n: "CF_TE_Endpoint_2"; t: CF_TE_Endpoint_2; v: "C_ShowReelsCommentsOverlay";}
		|{n: "CF_TE_Endpoint_2"; t: CF_TE_Endpoint_2; v: "C_UpdateToggleButtonState";}
		|{n: "CF_TE_Endpoint_2"; t: CF_TE_Endpoint_2; v: "E_ShowEngagementPanel";}
		|{n: "CF_TE_Endpoint_2"; t: CF_TE_Endpoint_2; v: "E_YpcGetOfflineUpsell";}
		|{n: "CF_TE_Endpoint_3"; t: CF_TE_Endpoint_3; v: "C_GetPdgBuyFlow";}
		|{n: "CF_TE_Endpoint_3"; t: CF_TE_Endpoint_3; v: "E_AddToPlaylistService";}
		|{n: "CF_TE_Endpoint_3"; t: CF_TE_Endpoint_3; v: "E_CreateBackstagePost";}
		|{n: "CF_TE_Endpoint_3"; t: CF_TE_Endpoint_3; v: "E_CreateComment";}
		|{n: "CF_TE_Endpoint_3"; t: CF_TE_Endpoint_3; v: "E_CreateCommentReplyDialog";}
		|{n: "CF_TE_Endpoint_3"; t: CF_TE_Endpoint_3; v: "E_CreatePlaylistService";}
		|{n: "CF_TE_Endpoint_3"; t: CF_TE_Endpoint_3; v: "E_GetNotificationMenu";}
		|{n: "CF_TE_Endpoint_3"; t: CF_TE_Endpoint_3; v: "E_GetReportForm";}
		|{n: "CF_TE_Endpoint_3"; t: CF_TE_Endpoint_3; v: "E_GetTranscript";}
		|{n: "CF_TE_Endpoint_3"; t: CF_TE_Endpoint_3; v: "E_Like";}
		|{n: "CF_TE_Endpoint_3"; t: CF_TE_Endpoint_3; v: "E_NotificationOptOut";}
		|{n: "CF_TE_Endpoint_3"; t: CF_TE_Endpoint_3; v: "E_PlaylistEdit";}
		|{n: "CF_TE_Endpoint_3"; t: CF_TE_Endpoint_3; v: "E_PlaylistEditor";}
		|{n: "CF_TE_Endpoint_3"; t: CF_TE_Endpoint_3; v: "E_RecordNotificationInteractions";}
		|{n: "CF_TE_Endpoint_3"; t: CF_TE_Endpoint_3; v: "E_Search";}
		|{n: "CF_TE_Endpoint_3"; t: CF_TE_Endpoint_3; v: "E_ShareEntityService";}
		|{n: "CF_TE_Endpoint_3"; t: CF_TE_Endpoint_3; v: "E_SignalNavigation";}
		|{n: "CF_TE_Endpoint_3"; t: CF_TE_Endpoint_3; v: "E_Subscribe";}
		|{n: "CF_TE_Endpoint_3"; t: CF_TE_Endpoint_3; v: "E_UndoFeedback";}
		|{n: "CF_TE_Endpoint_3"; t: CF_TE_Endpoint_3; v: "E_Unsubscribe";}
		|{n: "CF_TE_Endpoint_3"; t: CF_TE_Endpoint_3; v: "E_Url";}
		|{n: "CF_TE_Endpoint_3"; t: CF_TE_Endpoint_3; v: "E_UserFeedback";}
		|{n: "CF_TE_Endpoint_3"; t: CF_TE_Endpoint_3; v: "E_VE11487";}
		|{n: "CF_TE_Endpoint_3"; t: CF_TE_Endpoint_3; v: "E_VE23462";}
		|{n: "CF_TE_Endpoint_3"; t: CF_TE_Endpoint_3; v: "E_VE3611";}
		|{n: "CF_TE_Endpoint_3"; t: CF_TE_Endpoint_3; v: "E_VE37414_ReelWatch";}
		|{n: "CF_TE_Endpoint_3"; t: CF_TE_Endpoint_3; v: "E_VE42352";}
		|{n: "CF_TE_Endpoint_3"; t: CF_TE_Endpoint_3; v: "E_VE4724_Search";}
		|{n: "CF_TE_Endpoint_3"; t: CF_TE_Endpoint_3; v: "E_VE5754";}
		|{n: "CF_TE_Endpoint_3"; t: CF_TE_Endpoint_3; v: "E_VE83769_Upload";}
		|{n: "CF_TE_Endpoint_3"; t: CF_TE_Endpoint_3; v: "E_VE83769_Url";}
		|{n: "CF_TE_Endpoint_3"; t: CF_TE_Endpoint_3; v: "E_VE96368";}
		|{n: "CF_TE_Endpoint_3"; t: CF_TE_Endpoint_3; v: "E_Watch";}
		|{n: "CF_TE_Endpoint_3"; t: CF_TE_Endpoint_3; v: "E_WatchPlaylist";}
		|{n: "CF_TE_Endpoint_3"; t: CF_TE_Endpoint_3; v: "E_YpcGetCart";}
		|{n: "CF_TE_Endpoint_3"; t: CF_TE_Endpoint_3; v: "E_YpcGetOffers";}
		|{n: "CF_TE_Endpoint_Opt_3"; t: CF_TE_Endpoint_Opt_3; v: "C_Continuation";}
		|{n: "CF_TE_TrackedObj_2"; t: CF_TE_TrackedObj_2; v: "AD_ReelDismissal";}
		|{n: "CF_TR_MultiPageMenu"; t: CF_TR_MultiPageMenu; v: "D_NotificationMenu_PopupItemMenu";}
		|{n: "CF_TR_MultiPageMenu"; t: CF_TR_MultiPageMenu; v: "P_NotificationMenu_Popup";}
		|{n: "CF_TR_MultiPageMenu"; t: CF_TR_MultiPageMenu; v: "R_AccountMenu";}
		|{n: "CF_TR_MultiPageMenu"; t: CF_TR_MultiPageMenu; v: "R_SystemMenu";}
		|{n: "CF_TR_MultiPageMenu"; t: CF_TR_MultiPageMenu; v: "R_TopbarMenu";}
		|{n: "CF_TR_MultiPageMenu"; t: CF_TR_MultiPageMenu; v: "TR_MultiPageMenu_Empty";}
		|{n: "CF_T_Attachment"; t: CF_T_Attachment; v: "D_CommandRunItem";}
		|{n: "CF_T_Attachment"; t: CF_T_Attachment; v: "D_HighlightTextDecorator";}
		|{n: "CF_T_Attachment"; t: CF_T_Attachment; v: "D_StyleRunItem";}
		|{n: "CF_T_Attachment"; t: CF_T_Attachment; v: "D_VideoSecondaryInfo";}
		|{n: "CF_T_Commands"; t: CF_T_Commands; v: "DC_CommandExecutor";}
		|{n: "CF_T_GM"; t: CF_T_GM; v: "GM_AccountMenu";}
		|{n: "CF_T_GM"; t: CF_T_GM; v: "GM_AddToPlaylistService";}
		|{n: "CF_T_GM"; t: CF_T_GM; v: "GM_AddUpcomingEventReminder";}
		|{n: "CF_T_GM"; t: CF_T_GM; v: "GM_Browse";}
		|{n: "CF_T_GM"; t: CF_T_GM; v: "GM_CreateBackstagePost";}
		|{n: "CF_T_GM"; t: CF_T_GM; v: "GM_CreateComment";}
		|{n: "CF_T_GM"; t: CF_T_GM; v: "GM_CreateCommentReply";}
		|{n: "CF_T_GM"; t: CF_T_GM; v: "GM_CreatePlaylist";}
		|{n: "CF_T_GM"; t: CF_T_GM; v: "GM_Dislike";}
		|{n: "CF_T_GM"; t: CF_T_GM; v: "GM_EditPlaylist";}
		|{n: "CF_T_GM"; t: CF_T_GM; v: "GM_Feedback";}
		|{n: "CF_T_GM"; t: CF_T_GM; v: "GM_FlagGetForm";}
		|{n: "CF_T_GM"; t: CF_T_GM; v: "GM_GetNotificationMenu";}
		|{n: "CF_T_GM"; t: CF_T_GM; v: "GM_GetSettingsEditor";}
		|{n: "CF_T_GM"; t: CF_T_GM; v: "GM_GetSharePanel";}
		|{n: "CF_T_GM"; t: CF_T_GM; v: "GM_GetTranscript";}
		|{n: "CF_T_GM"; t: CF_T_GM; v: "GM_GetUnseenNotificationCount";}
		|{n: "CF_T_GM"; t: CF_T_GM; v: "GM_LikeLike";}
		|{n: "CF_T_GM"; t: CF_T_GM; v: "GM_Next";}
		|{n: "CF_T_GM"; t: CF_T_GM; v: "GM_NotificationOptOut";}
		|{n: "CF_T_GM"; t: CF_T_GM; v: "GM_PerformCommentAction";}
		|{n: "CF_T_GM"; t: CF_T_GM; v: "GM_PlaylistDelete";}
		|{n: "CF_T_GM"; t: CF_T_GM; v: "GM_RecordInteractions";}
		|{n: "CF_T_GM"; t: CF_T_GM; v: "GM_RemoveLike";}
		|{n: "CF_T_GM"; t: CF_T_GM; v: "GM_RemoveUpcomingEventReminder";}
		|{n: "CF_T_GM"; t: CF_T_GM; v: "GM_SetSetting";}
		|{n: "CF_T_GM"; t: CF_T_GM; v: "GM_Subscribe";}
		|{n: "CF_T_GM"; t: CF_T_GM; v: "GM_UpdatedMetadata";}
		|{n: "CF_T_GM"; t: CF_T_GM; v: "GM_YpcGetOffers";}
		|{n: "CF_T_Icon"; t: CF_T_Icon; v: "DMD_Badge_LiveNow";}
		|{n: "CF_T_Icon"; t: CF_T_Icon; v: "DMD_Badge_MediumGray";}
		|{n: "CF_T_Icon"; t: CF_T_Icon; v: "DMD_Badge_Verified";}
		|{n: "CF_T_Icon"; t: CF_T_Icon; v: "DMD_Badge_VerifiedArtist";}
		|{n: "CF_T_Icon"; t: CF_T_Icon; v: "D_Button.icon";}
		|{n: "CF_T_Icon"; t: CF_T_Icon; v: "D_EmojiPickerCategoryButton:ForChannel:icon";}
		|{n: "CF_T_Icon"; t: CF_T_Icon; v: "D_EmojiPickerCategoryButton:icon";}
		|{n: "CF_T_Icon"; t: CF_T_Icon; v: "D_EmojiPickerCategoryButton:targetId:icon";}
		|{n: "CF_T_Icon"; t: CF_T_Icon; v: "D_Guide_CollapseIcon";}
		|{n: "CF_T_Icon"; t: CF_T_Icon; v: "D_Guide_ExpandIcon";}
		|{n: "CF_T_Icon"; t: CF_T_Icon; v: "D_Icon_Search";}
		|{n: "CF_T_Icon"; t: CF_T_Icon; v: "D_LayoutProperties";}
		|{n: "CF_T_Icon"; t: CF_T_Icon; v: "D_MixIcon";}
		|{n: "CF_T_Icon"; t: CF_T_Icon; v: "D_PaidContentOverlay";}
		|{n: "CF_T_Icon"; t: CF_T_Icon; v: "D_PrivacyDropdownItem";}
		|{n: "CF_T_Icon"; t: CF_T_Icon; v: "D_PromotedSparklesWeb:icon";}
		|{n: "CF_T_Icon"; t: CF_T_Icon; v: "D_ReelMultimixAttributionLabel";}
		|{n: "CF_T_Icon"; t: CF_T_Icon; v: "D_RichMetadata_BoxArt:icon";}
		|{n: "CF_T_Icon"; t: CF_T_Icon; v: "D_RichMetadata_Topic:icon";}
		|{n: "CF_T_Icon"; t: CF_T_Icon; v: "D_ThumbnailOverlayToggleButton_ToggledPrefix:icon";}
		|{n: "CF_T_Icon"; t: CF_T_Icon; v: "D_ThumbnailOverlayToggleButton_UntoggledPrefix_1:icon";}
		|{n: "CF_T_Icon"; t: CF_T_Icon; v: "D_ThumbnailOverlayToggleButton_UntoggledPrefix_2:icon";}
		|{n: "CF_T_Icon"; t: CF_T_Icon; v: "D_TopbarLogo:iconImage";}
		|{n: "CF_T_Icon"; t: CF_T_Icon; v: "D_VideoPrimaryInfo";}
		|{n: "CF_T_Icon_Any"; t: CF_T_Icon_Any; v: "D_GuideEntry_Icon";}
		|{n: "CF_T_Icon_Any"; t: CF_T_Icon_Any; v: "D_GuideEntry_WithIcon:icon";}
		|{n: "CF_T_Icon_Any"; t: CF_T_Icon_Any; v: "D_GuideEntry_WithNavEP:icon";}
		|{n: "CF_T_Icon_Any"; t: CF_T_Icon_Any; v: "D_Icon_ThumbnailOverlaySidePanel";}
		|{n: "CF_T_Items"; t: CF_T_Items; v: "D_ProfileColumn";}
		|{n: "CF_T_Items_TP"; t: CF_T_Items_TP; v: "R_CompactLink_Items";}
		|{n: "CF_T_OpenPopup_Dropdown"; t: CF_T_OpenPopup_Dropdown; v: "Popup_DD_SystemMenu";}
		|{n: "CF_T_SE_Signal"; t: CF_T_SE_Signal; v: "D_GuideEntry_WithIcon.SE_Signal";}
		|{n: "CF_T_SE_Signal"; t: CF_T_SE_Signal; v: "D_NotificationTopbarButton.U_UnseenCount.T_SE_Signal";}
		|{n: "CF_T_SE_Signal"; t: CF_T_SE_Signal; v: "D_NotificationTopbarButton.menuRequest.T_SE_Signal";}
		|{n: "CF_T_SE_Signal"; t: CF_T_SE_Signal; v: "D_TopbarMenuButton.SE_Signal";}
		|{n: "CF_T_SE_Signal"; t: CF_T_SE_Signal; v: "E_SignalService_SendPost";}
		|{n: "CF_T_SE_Signal"; t: CF_T_SE_Signal; v: "GC_Button.SE_Signal";}
		|{n: "CF_T_Signal"; t: CF_T_Signal; v: "DE_SignalNavigation";}
		|{n: "CF_T_Signal"; t: CF_T_Signal; v: "DE_SubmitFeedback";}
		|{n: "CF_T_WCM"; t: CF_T_WCM; v: "M_AccountMenu";}
		|{n: "CF_T_WCM"; t: CF_T_WCM; v: "M_AddToPlaylistService";}
		|{n: "CF_T_WCM"; t: CF_T_WCM; v: "M_AddUpcomingEventReminder";}
		|{n: "CF_T_WCM"; t: CF_T_WCM; v: "M_Browse";}
		|{n: "CF_T_WCM"; t: CF_T_WCM; v: "M_CreateBackstagePost";}
		|{n: "CF_T_WCM"; t: CF_T_WCM; v: "M_CreateComment";}
		|{n: "CF_T_WCM"; t: CF_T_WCM; v: "M_CreateCommentReply";}
		|{n: "CF_T_WCM"; t: CF_T_WCM; v: "M_CreateCommentReplyDialog";}
		|{n: "CF_T_WCM"; t: CF_T_WCM; v: "M_CreatePlaylist";}
		|{n: "CF_T_WCM"; t: CF_T_WCM; v: "M_EditPlaylist";}
		|{n: "CF_T_WCM"; t: CF_T_WCM; v: "M_Feedback";}
		|{n: "CF_T_WCM"; t: CF_T_WCM; v: "M_FlagGetForm";}
		|{n: "CF_T_WCM"; t: CF_T_WCM; v: "M_GetNotificationMenu";}
		|{n: "CF_T_WCM"; t: CF_T_WCM; v: "M_GetPdgBuyFlow";}
		|{n: "CF_T_WCM"; t: CF_T_WCM; v: "M_GetSettingsEditor";}
		|{n: "CF_T_WCM"; t: CF_T_WCM; v: "M_GetSharePanel";}
		|{n: "CF_T_WCM"; t: CF_T_WCM; v: "M_GetTranscript";}
		|{n: "CF_T_WCM"; t: CF_T_WCM; v: "M_GetUnseenNotificationCount";}
		|{n: "CF_T_WCM"; t: CF_T_WCM; v: "M_Like";}
		|{n: "CF_T_WCM"; t: CF_T_WCM; v: "M_Next";}
		|{n: "CF_T_WCM"; t: CF_T_WCM; v: "M_NotificationOptOut";}
		|{n: "CF_T_WCM"; t: CF_T_WCM; v: "M_PerformCommentAction";}
		|{n: "CF_T_WCM"; t: CF_T_WCM; v: "M_PlaylistDelete";}
		|{n: "CF_T_WCM"; t: CF_T_WCM; v: "M_RecordInteractions";}
		|{n: "CF_T_WCM"; t: CF_T_WCM; v: "M_RemoveUpcomingEventReminder";}
		|{n: "CF_T_WCM"; t: CF_T_WCM; v: "M_Search";}
		|{n: "CF_T_WCM"; t: CF_T_WCM; v: "M_SendPost";}
		|{n: "CF_T_WCM"; t: CF_T_WCM; v: "M_SetSetting";}
		|{n: "CF_T_WCM"; t: CF_T_WCM; v: "M_Subscribe";}
		|{n: "CF_T_WCM"; t: CF_T_WCM; v: "M_Unsubscribe";}
		|{n: "CF_T_WCM"; t: CF_T_WCM; v: "M_UpdatedMetadata";}
		|{n: "CF_T_WCM"; t: CF_T_WCM; v: "M_Url";}
		|{n: "CF_T_WCM"; t: CF_T_WCM; v: "M_UserFeedback";}
		|{n: "CF_T_WCM"; t: CF_T_WCM; v: "M_VE11487";}
		|{n: "CF_T_WCM"; t: CF_T_WCM; v: "M_VE12924";}
		|{n: "CF_T_WCM"; t: CF_T_WCM; v: "M_VE23462";}
		|{n: "CF_T_WCM"; t: CF_T_WCM; v: "M_VE37414";}
		|{n: "CF_T_WCM"; t: CF_T_WCM; v: "M_VE3832";}
		|{n: "CF_T_WCM"; t: CF_T_WCM; v: "M_VE42352";}
		|{n: "CF_T_WCM"; t: CF_T_WCM; v: "M_VE4724";}
		|{n: "CF_T_WCM"; t: CF_T_WCM; v: "M_VE5754";}
		|{n: "CF_T_WCM"; t: CF_T_WCM; v: "M_VE6827";}
		|{n: "CF_T_WCM"; t: CF_T_WCM; v: "M_VE83769";}
		|{n: "CF_T_WCM"; t: CF_T_WCM; v: "M_VE96368";}
		|{n: "CF_T_WCM"; t: CF_T_WCM; v: "M_YpcGetCart";}
		|{n: "CF_T_WCM"; t: CF_T_WCM; v: "M_YpcGetOffers";}
		|{n: "CF_T_WCM_Unpack"; t: CF_T_WCM_Unpack; v: "MG_Survey_CMD";}
		|{n: "CF_add_string_to_map"; t: CF_add_string_to_map; v: "D_ToggleButton";}
		|{n: "CF_onMissingIcon"; t: CF_onMissingIcon; v: "D_GuideEntry_WithIcon";}
		|{n: "CF_onMissingIcon"; t: CF_onMissingIcon; v: "D_GuideEntry_WithNavEP";}
		|{n: "CF_onMissingIcon"; t: CF_onMissingIcon; v: "D_ThumbnailOverlaySidePanel";}
		|{n: "CF_parse_identifier"; t: CF_parse_identifier; v: "SI_VE126250_Identifier";}
		|{n: "CF_parse_identifier"; t: CF_parse_identifier; v: "SI_VE76278_Identifier";}
		|{n: "P_ParamParse"; t: P_ParamParse; v: "PD_continuation_params.f3";}
		|{n: "P_ParamParse"; t: P_ParamParse; v: "PX_watch_next_token_2.f37";}
		|{n: "P_ParamParse"; t: P_ParamParse; v: "aadc_guidelines_state.entity.key";}
		|{n: "P_ParamParse"; t: P_ParamParse; v: "ad_layout.ad_serving_data_entry";}
		|{n: "P_ParamParse"; t: P_ParamParse; v: "ad_slot_logging_data.serialized_slot_ad_serving_data_entry";}
		|{n: "P_ParamParse"; t: P_ParamParse; v: "adaptive_format_item.xtags";}
		|{n: "P_ParamParse"; t: P_ParamParse; v: "change_markers_visibility.entity.key";}
		|{n: "P_ParamParse"; t: P_ParamParse; v: "continuation.params";}
		|{n: "P_ParamParse"; t: P_ParamParse; v: "continuation_request.browse.token";}
		|{n: "P_ParamParse"; t: P_ParamParse; v: "continuation_request.reel_watch_sequence.token";}
		|{n: "P_ParamParse"; t: P_ParamParse; v: "continuation_request.watch_next.token";}
		|{n: "P_ParamParse"; t: P_ParamParse; v: "create_backstage_post.params";}
		|{n: "P_ParamParse"; t: P_ParamParse; v: "create_comment.params";}
		|{n: "P_ParamParse"; t: P_ParamParse; v: "create_playlist.params";}
		|{n: "P_ParamParse"; t: P_ParamParse; v: "create_reply.params";}
		|{n: "P_ParamParse"; t: P_ParamParse; v: "dislike.params";}
		|{n: "P_ParamParse"; t: P_ParamParse; v: "entity.key";}
		|{n: "P_ParamParse"; t: P_ParamParse; v: "feedbackToken";}
		|{n: "P_ParamParse"; t: P_ParamParse; v: "format_item.xtags";}
		|{n: "P_ParamParse"; t: P_ParamParse; v: "get_notification_menu.ctoken";}
		|{n: "P_ParamParse"; t: P_ParamParse; v: "get_pdg_buy_flow.params";}
		|{n: "P_ParamParse"; t: P_ParamParse; v: "get_report_form.params";}
		|{n: "P_ParamParse"; t: P_ParamParse; v: "get_transcript.params";}
		|{n: "P_ParamParse"; t: P_ParamParse; v: "instream_video_ad.player_vars";}
		|{n: "P_ParamParse"; t: P_ParamParse; v: "invalidation.continuation";}
		|{n: "P_ParamParse"; t: P_ParamParse; v: "like.params";}
		|{n: "P_ParamParse"; t: P_ParamParse; v: "live_chat_replay.continuation";}
		|{n: "P_ParamParse"; t: P_ParamParse; v: "load_markers.entity.key";}
		|{n: "P_ParamParse"; t: P_ParamParse; v: "logging_context.serialized_context_data";}
		|{n: "P_ParamParse"; t: P_ParamParse; v: "macro_marker_repeat_state.entity.key";}
		|{n: "P_ParamParse"; t: P_ParamParse; v: "macro_markers_list.entity.key";}
		|{n: "P_ParamParse"; t: P_ParamParse; v: "next.continuation";}
		|{n: "P_ParamParse"; t: P_ParamParse; v: "next.queue_context.params";}
		|{n: "P_ParamParse"; t: P_ParamParse; v: "next_radio.continuation";}
		|{n: "P_ParamParse"; t: P_ParamParse; v: "notification.opt_out";}
		|{n: "P_ParamParse"; t: P_ParamParse; v: "notification.record_interactions";}
		|{n: "P_ParamParse"; t: P_ParamParse; v: "notification_add_upcoming_event_reminder.params";}
		|{n: "P_ParamParse"; t: P_ParamParse; v: "notification_remove_upcoming_event_reminder.params";}
		|{n: "P_ParamParse"; t: P_ParamParse; v: "params.click_tracking";}
		|{n: "P_ParamParse"; t: P_ParamParse; v: "params.tracking";}
		|{n: "P_ParamParse"; t: P_ParamParse; v: "perform_comment.action";}
		|{n: "P_ParamParse"; t: P_ParamParse; v: "pf_23n24n.bin_params";}
		|{n: "P_ParamParse"; t: P_ParamParse; v: "playability_status.context_params";}
		|{n: "P_ParamParse"; t: P_ParamParse; v: "player_seek.continuation";}
		|{n: "P_ParamParse"; t: P_ParamParse; v: "player_state.entity.key";}
		|{n: "P_ParamParse"; t: P_ParamParse; v: "playlist_edit.params";}
		|{n: "P_ParamParse"; t: P_ParamParse; v: "playlist_loop_state.entity.key";}
		|{n: "P_ParamParse"; t: P_ParamParse; v: "reel.params";}
		|{n: "P_ParamParse"; t: P_ParamParse; v: "reel.player_params";}
		|{n: "P_ParamParse"; t: P_ParamParse; v: "reel.sequence_params";}
		|{n: "P_ParamParse"; t: P_ParamParse; v: "reload.continuation";}
		|{n: "P_ParamParse"; t: P_ParamParse; v: "remove_like.params";}
		|{n: "P_ParamParse"; t: P_ParamParse; v: "search.params";}
		|{n: "P_ParamParse"; t: P_ParamParse; v: "shorts.source.bp";}
		|{n: "P_ParamParse"; t: P_ParamParse; v: "subscribe.params";}
		|{n: "P_ParamParse"; t: P_ParamParse; v: "subscribe_button.entity.key";}
		|{n: "P_ParamParse"; t: P_ParamParse; v: "subscription_state.key";}
		|{n: "P_ParamParse"; t: P_ParamParse; v: "timed_continuation.data";}
		|{n: "P_ParamParse"; t: P_ParamParse; v: "transcript.params";}
		|{n: "P_ParamParse"; t: P_ParamParse; v: "transcript_track_selection.entity.key";}
		|{n: "P_ParamParse"; t: P_ParamParse; v: "transcript_track_selection.serialized_params";}
		|{n: "P_ParamParse"; t: P_ParamParse; v: "trending.bp";}
		|{n: "P_ParamParse"; t: P_ParamParse; v: "unsubscribe.params";}
		|{n: "P_ParamParse"; t: P_ParamParse; v: "ve_3611.params";}
		|{n: "P_ParamParse"; t: P_ParamParse; v: "ve_6827.params";}
		|{n: "P_ParamParse"; t: P_ParamParse; v: "video.params";}
		|{n: "P_ParamParse"; t: P_ParamParse; v: "view_count.entity.key";}
		|{n: "P_ParamParse"; t: P_ParamParse; v: "watch.params";}
		|{n: "P_ParamParse"; t: P_ParamParse; v: "watch.player_params";}
		|{n: "P_ParamParse"; t: P_ParamParse; v: "watch_next_token.f5.binary_token";}
		|{n: "P_ParamParse"; t: P_ParamParse; v: "watch_playlist.params";}
		|{n: "P_ParamParse"; t: P_ParamParse; v: "ypc_get_cart.transaction_params";}
		|{n: "P_ParamParse"; t: P_ParamParse; v: "ypc_get_offers.params";}
		|{n: "P_ParamParse"; t: P_ParamParse; v: "ypc_get_offline_upsell.params";}
		;
}
