import {Prelude} from "./out_support.js"; export {Prelude};
import {Types} from "./out_support.js"; export {Types};
export namespace Gen {
	export type CF_Generated=
		|{n: Prelude.CF_D_CaseGen; t: Types.CF_D_CaseGen_; v: "AD_ChangeEngagementPanelVisibility.visibility";}
		|{n: Prelude.CF_D_CaseGen; t: Types.CF_D_CaseGen_; v: "DE_SignalNavigation.signal";}
		|{n: Prelude.CF_D_CaseGen; t: Types.CF_D_CaseGen_; v: "D_EngagementPanelTargetId:AD_ChangeEngagementPanelVisibility.targetId";}
		|{n: Prelude.CF_D_CaseGen; t: Types.CF_D_CaseGen_; v: "D_GuideEntry_TargetId";}
		|{n: Prelude.CF_D_CaseGen; t: Types.CF_D_CaseGen_; v: "D_ReelPlayerOverlay";}
		|{n: Prelude.CF_D_CaseGen; t: Types.CF_D_CaseGen_; v: "D_RichMetadata";}
		|{n: Prelude.CF_D_CaseGen; t: Types.CF_D_CaseGen_; v: "D_RichShelf.icon";}
		|{n: Prelude.CF_D_CaseGen; t: Types.CF_D_CaseGen_; v: "D_RichShelf.rowIndex";}
		|{n: Prelude.CF_D_CaseGen; t: Types.CF_D_CaseGen_; v: "D_TargetIdStr:targetId";}
		|{n: Prelude.CF_D_CaseGen; t: Types.CF_D_CaseGen_; v: "D_TargetIdStr:targetId:EngagementPanel";}
		|{n: Prelude.CF_D_CaseGen; t: Types.CF_D_CaseGen_; v: "D_TargetIdStr:targetId:EngagementPanel:MacroMarkers";}
		|{n: Prelude.CF_D_CaseGen; t: Types.CF_D_CaseGen_; v: "D_YtStudio_Url";}
		|{n: Prelude.CF_D_CaseGen; t: Types.CF_D_CaseGen_; v: "RE_D_VE3832_PreconnectUrl.host_partition";}
		|{n: Prelude.CF_D_CaseGen; t: Types.CF_D_CaseGen_; v: "S_VideoGoodPutShape.sparams";}
		|{n: Prelude.CF_D_CaseGen; t: Types.CF_D_CaseGen_; v: "js_gen_case:log_googlevideo_host:host_partition";}
		|{n: Prelude.CF_D_CaseGen; t: Types.CF_D_CaseGen_; v: "js_gen_case:log_videoplayback:D_VideoPlaybackShape_LS_Params.mn.host_partition";}
		|{n: Prelude.CF_D_ChipCloudChip_Omit; t: Types.CF_D_ChipCloudChip_Omit_; v: "D_ChipCloudChip_WithSelection";}
		|{n: Prelude.CF_D_CustomEmoji; t: Types.CF_D_CustomEmoji_; v: "D_CustomEmoji";}
		|{n: Prelude.CF_D_CustomEmoji; t: Types.CF_D_CustomEmoji_; v: "D_LiveChatEmoji";}
		|{n: Prelude.CF_D_GuideEntry; t: Types.CF_D_GuideEntry_; v: "D_GuideEntry";}
		|{n: Prelude.CF_D_GuideEntry; t: Types.CF_D_GuideEntry_; v: "D_GuideEntry_WithPrimary";}
		|{n: Prelude.CF_D_Link; t: Types.CF_D_Link_; v: "D_CompactLink";}
		|{n: Prelude.CF_D_Link; t: Types.CF_D_Link_; v: "D_CompactLink.Styled";}
		|{n: Prelude.CF_D_Menu_Omit; t: Types.CF_D_Menu_Omit_; v: "D_CompactRadio";}
		|{n: Prelude.CF_D_Menu_Omit; t: Types.CF_D_Menu_Omit_; v: "D_CompactVideo";}
		|{n: Prelude.CF_D_Menu_Omit; t: Types.CF_D_Menu_Omit_; v: "D_PlayerOverlayAutoplay";}
		|{n: Prelude.CF_D_Menu_Omit; t: Types.CF_D_Menu_Omit_; v: "D_PlaylistSidebarPrimaryInfo";}
		|{n: Prelude.CF_D_Menu_Omit; t: Types.CF_D_Menu_Omit_; v: "D_Radio";}
		|{n: Prelude.CF_D_Params; t: Types.CF_D_Params_; v: "DE_AddUpcomingEventReminder";}
		|{n: Prelude.CF_D_Params; t: Types.CF_D_Params_; v: "DE_GetReportForm";}
		|{n: Prelude.CF_D_Params; t: Types.CF_D_Params_; v: "DE_GetTranscript";}
		|{n: Prelude.CF_D_Params; t: Types.CF_D_Params_; v: "DE_RemoveUpcomingEventReminder";}
		|{n: Prelude.CF_D_Params; t: Types.CF_D_Params_; v: "DE_YpcGetOffers";}
		|{n: Prelude.CF_D_Params; t: Types.CF_D_Params_; v: "DE_YpcGetOfflineUpsell";}
		|{n: Prelude.CF_D_Playlist_Omit; t: Types.CF_D_Playlist_Omit_; v: "D_CompactPlaylist";}
		|{n: Prelude.CF_D_STR; t: Types.CF_D_STR_; v: "D_ChannelId";}
		|{n: Prelude.CF_D_STR; t: Types.CF_D_STR_; v: "D_RadioShareUrl";}
		|{n: Prelude.CF_D_STR; t: Types.CF_D_STR_; v: "D_YoutubeKidsUrl";}
		|{n: Prelude.CF_D_STR; t: Types.CF_D_STR_; v: "GU_YoutubeUrlRedirect";}
		|{n: Prelude.CF_D_ToggleButton; t: Types.CF_D_ToggleButton_; v: "D_ToggleButton";}
		|{n: Prelude.CF_D_Video_Handle; t: Types.CF_D_Video_Handle_; v: "D_Video_Other";}
		|{n: Prelude.CF_D_Video_Handle; t: Types.CF_D_Video_Handle_; v: "D_Video_Other:isWatched";}
		|{n: Prelude.CF_D_Video_Handle; t: Types.CF_D_Video_Handle_; v: "D_Video_With:accessibility";}
		|{n: Prelude.CF_D_Video_Handle; t: Types.CF_D_Video_Handle_; v: "D_Video_With:accessibility:isWatched";}
		|{n: Prelude.CF_D_Video_Handle; t: Types.CF_D_Video_Handle_; v: "D_Video_With:owner";}
		|{n: Prelude.CF_D_Video_Handle; t: Types.CF_D_Video_Handle_; v: "D_Video_With:owner:isWatched";}
		|{n: Prelude.CF_D_Video_Handle; t: Types.CF_D_Video_Handle_; v: "D_Video_With:videoId";}
		|{n: Prelude.CF_D_Video_Handle; t: Types.CF_D_Video_Handle_; v: "D_Video_With:videoId:descriptionSnippet";}
		|{n: Prelude.CF_D_Video_Handle; t: Types.CF_D_Video_Handle_; v: "D_Video_With:videoId:descriptionSnippet:isWatched";}
		|{n: Prelude.CF_D_Video_Handle; t: Types.CF_D_Video_Handle_; v: "D_Video_With:videoId:isWatched";}
		|{n: Prelude.CF_D_Video_Handle; t: Types.CF_D_Video_Handle_; v: "D_Video_With:videoId:topStandaloneBadge";}
		|{n: Prelude.CF_D_Video_Handle; t: Types.CF_D_Video_Handle_; v: "D_Video_With:videoId:topStandaloneBadge:isWatched";}
		|{n: Prelude.CF_GE_ResponseReceived; t: Types.CF_GE_ResponseReceived_; v: "RS_Browse";}
		|{n: Prelude.CF_GE_ResponseReceived; t: Types.CF_GE_ResponseReceived_; v: "RS_Next";}
		|{n: Prelude.CF_GE_ResponseReceived; t: Types.CF_GE_ResponseReceived_; v: "RS_Watch";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "B_HrefUrl.url";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "DD_Streaming";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_AboutThisAd";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_AdaptiveFormatItem";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_AdaptiveFormatItem:signatureCipher";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_CardCollection";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_Channel_MD.channelConversionUrl";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_ClientForecastingAd.impressionUrl";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_CommentsHeader";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_CommonConfig.url";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_FormatItem";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_FormatItem:signatureCipher";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_ImpressionCommand:LoggingUrlItem";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "D_PlayerMicroformat";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "RS_Page_Watch";}
		|{n: Prelude.CF_L_TP_Params; t: Types.CF_L_TP_Params_; v: "R_WatchPage_VE3832";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "AD_AccountItem";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "AD_AddChatItem";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "AD_AddToGuideSection";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "AD_ChangeEngagementPanelVisibility";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "AD_Notification";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "AD_ReplayChatItem";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "AD_SendFeedback";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "AD_SetActivePanelItem";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "AD_ShowEngagementPanelScrim";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "AD_Signal";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "AD_SubscribeButton";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "AD_UpdateEngagementPanel";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "AD_UpdateNotificationsUnseenCount";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "AS_PlaylistDescription";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "AS_PlaylistName";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "AS_PlaylistPrivacy";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "AS_PlaylistVideoOrder";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "AU_EngagementPanel";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "AU_ToggleButtonTextData";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "A_AddVideo";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "A_BrowseFeed";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "A_COPY_FROM_PLAYLIST";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "A_CommentsSectionContinuation";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "A_CopyFromPlaylist";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "A_RemoveVideoByVideoId";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "A_SET_PLAYLIST_DESCRIPTION";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "A_SET_PLAYLIST_NAME";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "A_SET_PLAYLIST_PRIVACY";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "A_SetPlaylistVideoOrder";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "A_WatchNext";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "B_Hack";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "B_TagObj";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "CF_H_a";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "C_Executor";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "C_GetSurvey";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "C_ScrollToEngagementPanel";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "C_ShowReloadUi";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "DB_SI_EngagementPanel";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "DC_AddFollowUpSurvey";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "DC_AddToPlaylist";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "DC_AdsControlFlowOpportunityReceived";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "DC_ChangeKeyedMarkersVisibility";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "DC_ChangeMarkersVisibility";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "DC_Continuation";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "DC_Continuation_Browse";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "DC_Continuation_ReelWatchSeq";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "DC_Continuation_WatchNext";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "DC_EngagementPanelHeaderShowNavigationButton";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "DC_Generic_CTP";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "DC_GetPdgBuyFlow";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "DC_Invalidation";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "DC_LiveChat";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "DC_LiveChatReplay";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "DC_LoadMarkers";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "DC_RelatedChip";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "DC_ReloadContinuationItems";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "DC_RepeatChapter";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "DC_ResetChannelUnreadCount";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "DC_ScrollToEngagementPanel";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "DC_SectionList_SearchFeed";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "DC_ShowReloadUi";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "DC_Timed";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "DC_UpdateToggleButtonState";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "DD_Streaming";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "DE_AddToPlaylistService";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "DE_Feedback";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "DE_GetNotificationMenu";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "DE_NotificationOptOut";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "DE_RecordNotificationInteractions";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "DE_ReelWatch";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "DE_ShareEntityService";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "DE_Subscribe";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "DE_SuperThanksSelectedTier";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "DE_UndoFeedback";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "DE_Unsubscribe";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "DE_UserFeedback";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "DE_VE11487";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "DE_VE23462";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "DE_VE3611";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "DE_VE37414_ReelWatch";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "DE_VE3832:playlistSetVideoId:params";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "DE_VE3832:videoId";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "DE_VE3832_Watch";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "DE_VE3854";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "DE_VE42352";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "DE_VE5754";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "DE_VE6827";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "DE_VE83769_Url";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "DE_VE96368";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "DE_WatchPlaylist";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "DMD_AdSlot";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "DMD_Badge";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "DMD_RowContainer";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "DR_DC_EntityBatchUpdate";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "DS_CreatePlaylist";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "DS_EY_MacroMarkersList";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "DS_EY_PlaylistLoop";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "DS_EY_Subscription";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "DS_EY_TranscriptSearchBox";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "DS_EY_TranscriptTrackSelection";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "DU_MutationDelete";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "DU_MutationReplace";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "DU_UrlParams";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_AboutThisAd";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_ActionSetPlaylistVideoOrder";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_ActiveAccountHeader";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_ActiveView";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_AdBreakService";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_AdPlacement";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_AdPlacementConfig";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_AdSlot";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_AdSlotAndLayoutItem";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_AdTimeOffset";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_AdaptiveFormatItem";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_AddToPlaylist";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_AddToPlaylistCreate";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_AlertWithButton";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_AttBgChallenge";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_AudioConfig";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_AudioTrack";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_AudioTrackItem";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_AutoplayContent";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_AutoplaySetItem";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_AutoplaySwitchButton";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_Botguard";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_BrowserMediaSession";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_Button";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_Button:command";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_Button:navigationEndpoint";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_Button:serviceEndpoint";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_Button:style";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_C4TabbedHeader";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_Cache_MD";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_CaptionTrackItem";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_Card";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_CardCollection";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_CarouselLockup";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_ChannelHeaderLinks";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_ChannelSwitcherHeader";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_ChannelSwitcherPage";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_ChannelThumbnailWithLink";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_Channel_MD";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_ChildVideo";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_ChipCloud";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_ChipCloudChip_WithNav";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_ChipCloudChip_WithSelection";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_ChipUniqueId";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_CinematicAnimationConfig";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_CinematicConfig";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_CinematicContainer";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_ClickLocationTarget";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_ClientForecastingAd";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_ClipAdState";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_ClipCreation";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_ClipCreationScrubber";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_ClipCreationTextInput";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_Comment";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_CommentActionButtons";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_CommentReplies";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_CommentSimplebox";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_CommentThread";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_CommentsEntryPointHeader";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_CommentsEntryPointTeaser";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_CommentsHeader";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_CommentsSimplebox";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_CompactLink.Styled.icon";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_CompactLink.Styled:omit";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_CompactLink.icon";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_ConfirmDialog";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_Continuation";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_ContinuationItem";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_CueRangeItem";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_DarkColorPalette:D_MacroMarkersListItem:dark";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_DarkColorPalette:D_PlaylistPanelVideo:dark";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_DarkColorPalette:D_Thumbnail:dark";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_DecoratedPlayerBar";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_DesktopTopbar";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_DesktopWatchAds";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_DismissalFollowUp";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_DisplayAd";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_Dropdown";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_DropdownFormField";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_DynamicReadaheadConfig";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_EY_Offlineability";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_ElementResourceStatus";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_Emoji";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_EmojiImage";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_EmojiPicker";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_EmojiPickerCategory";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_EmojiPickerCategory:Global";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_EmojiPickerCategoryButton";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_EmojiPickerCategoryButton:ForChannel";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_EmojiPickerCategoryButton:targetId";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_EndScreenPlaylist";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_EndScreenVideo";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_Endscreen";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_EndscreenElement";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_EngagementPanelTitleHeader";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_ExpandableSurveyResponse";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_ExpandableTab";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_ExpandableVideoDescriptionBody";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_ExternalChannelId";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_Factoid";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_FancyDismissibleDialog";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_FeaturedChannel";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_FeedFilterChipBar";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_FeedNudge";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_FeedTabbedHeader";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_FeedbackResponseProcessedStatus";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_FormatItem";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_FrameworkUpdates";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_FusionSearchbox";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_GetSurvey";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_GhostGrid";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_GraftedVeItem";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_GuideCollapsibleEntry";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_GuideCollapsibleSectionEntry";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_GuideDownloadsEntry";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_GuideEntry";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_GuideEntryData";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_GuideEntry_WithIcon";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_GuideSection";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_GuideSubscriptionsSection";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_HeartbeatParams";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_HeroPlaylistThumbnail";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_Hint";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_HorizontalCardList";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_HotkeyDialog";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_HotkeyDialogSection";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_HotkeyDialogSectionOption";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_ImpressionCommand";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_InFeedAdLayout";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_InfoRow";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_InlineForm";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_InlineSurvey";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_InstreamVideoAd";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_InvalidationId";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_LearningResource";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_LightColorPalette:D_MacroMarkersListItem:light";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_LightColorPalette:D_PlaylistPanelVideo:light";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_LightColorPalette:D_Thumbnail:light";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_LikeApi";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_LikeButton";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_LikeButton.dislike";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_LikeButton.like";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_LinearAdSequence";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_LiveBroadcastDetails";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_LiveBroadcastingBadge";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_LiveChat";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_LiveChatHeader";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_LiveChatPlaceholderItem";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_LiveChatTextMessage";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_LiveChatViewerEngagementMessage";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_LoggingContext";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_LoggingDirectives";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_MP_MenuNotificationSection";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_MacroMarkersList";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_MacroMarkersListItem";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_MarkerItem";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_MarkersList";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_Menu";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_MenuFlexibleItem";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_MenuNavigationItem";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_MenuServiceItem";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_MenuServiceItem_Omit";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_Menu_WithItems";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_Menu_WithTargetId";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_MerchandiseItem";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_MerchandiseShelf";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_MetadataRow";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_Microformat.ios";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_Microformat.url";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_Microformat_Other";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_Miniplayer";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_ModifiedSetItem";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_MovingThumbnail";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_MovingThumbnail_Thumbnails";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_MusicCarouselShelf";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_MusicQueue";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_MusicShelf";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_MusicThumbnail";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_Notification";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_NotificationMenuPopupMenuItem";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_NotificationMenu_Popup";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_NotificationMenu_PopupItem";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_NotificationText";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_NotificationTopbarButton";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_PageTopAdLayout";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_PaidContentOverlay";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_PdgBuyFlow";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_PdgBuyFlowHeader";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_PdgColorSlider";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_PdgCommentChip";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_PdgCommentOption";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_PdgCommentPreview";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_PivotButton";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_PlayabilityStatus";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_PlayerAnnotationsExpanded";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_PlayerAttestation";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_PlayerCaptionsTracklist";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_PlayerConfig";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_PlayerMicroformat";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_PlayerOverlay";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_PlayerOverlay:autoplay";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_PlayerOverlay:autoplay:decoratedPlayerBarRenderer";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_PlayerOverlay:decoratedPlayerBarRenderer";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_PlayerOverlayVideoDetails";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_PlaylistAddToOption";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_PlaylistContent";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_PlaylistEdit";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_PlaylistHeader";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_PlaylistLoopButton";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_PlaylistLoopButtonState";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_PlaylistPanel";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_PlaylistPanelVideo";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_PlaylistSidebar";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_PlaylistVideoThumbnail";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_Playlist_MD";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_PrimaryLinkItem";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_PrivacyDropdownItem";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_ProductList";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_ProductListItem";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_ProfileColumnStatsEntry";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_ProfileColumnUserInfo";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_ProfilePageHeaderInformation";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_PromotedSparklesWeb";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_QoeLoggingContext";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_Radio";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_RadioShareUrl";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_Range";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_ReelMultimixAttributionLabel";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_ReelPlayerHeader";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_ReelPlayerOverlay";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_ReloadContinuationData";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_RemarketingPing";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_ResourceStatusInResponseCheckData";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_RichGrid";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_RichItem";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_RichListHeader";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_RichMetadataRow";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_RichMetadata_BoxArt";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_RichMetadata_Topic";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_RichSection";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_RichShelf";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_RunAttestation";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_SearchBox";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_SectionList_BrowseFeed_History";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_SectionList_BrowseFeed_Subscriptions";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_SegmentedLikeDislikeButton";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_SerializedSlotAdServingDataEntry";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_SettingsSidebar";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_ShowEngagementPanel";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_SimpleCardTeaser";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_SimpleMenuHeader";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_SortFilterSubMenu";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_SortFilterSubMenu_WithTargetId";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_SortFilterSubMenu_WithTargetId.MenuItem";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_SourcePivotHeader";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_SubFeedOption";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_SubFeedSelector";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_SubscribeButton";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_SubscribeButton_SubscribePrefix";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_SubscribeButton_SubscribedPrefix";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_SubscribeButton_UnsubscribePrefix.unsubscribe";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_SubscribeButton_UnsubscribedPrefix";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_SubscriptionButton";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_SubscriptionNotificationToggleButton";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_SuperVodBuyFlowContent";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_Tab_History";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_Tab_R_MusicQueue";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_Tab_Subscriptions";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_Tab_WhatToWatch";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_Tab_WithEndpoint";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_TemplateUpdate";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_TextHeader";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_TextInputFormField";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_TextRun";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_Thumbnail";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_ThumbnailItem";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_ThumbnailOverlayEndorsement";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_ThumbnailOverlayHoverText";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_ThumbnailOverlayInlineUnplayable";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_ThumbnailOverlaySidePanel";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_ThumbnailOverlayTimeStatus";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_ThumbnailOverlayToggleButton_ToggledPrefix";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_ThumbnailOverlayToggleButton_UntoggledPrefix_1";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_ThumbnailOverlayToggleButton_UntoggledPrefix_2";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_ThumbnailsList";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_TimedTextApi";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_TimestampWithNanos";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_ToggleMenuServiceItem";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_TopbarLogo";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_TopbarMenuButton";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_TopbarMenuButton_MenuItem";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_TopicLink";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_Transcript";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_TranscriptSearchPanel";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_TranscriptSegment";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_TranscriptSegmentList";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_TranslationLanguage";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_TriggerCriteria";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_TwoColumnBrowseResults";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_TwoColumnWatchNextResults";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_UnifiedSharePanel";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_UrlAndElapsedMediaTime";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_VideoDescriptionHeader";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_VideoDescriptionMusicSection";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_VideoDetails";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_VideoOwner";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_VideoOwner:1";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_VideoPlaybackShape";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_VideoPlaybackShape_LS_Params";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_VideoPlaybackShape_Other";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_VideoPlaybackShape_S_Params";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_VideoPrimaryInfo";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_VideoQualityPromo";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_VideoSecondaryInfo";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_VideoViewCount";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_Video_Owner";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_VoiceSearchDialog";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_VssLoggingContext";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_WatchEndpointMusicConfig";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_WatchNextEndScreen";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_WatchNextTabbedResults";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_WatchResults";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_WebPlayerActionsPorting";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_WebPlayerConfig";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_WebPrefetch";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_WebSearchboxConfig";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "D_YtConfig";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "E_LikeDislike";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "E_LikeIndifferent";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "E_LikeLike";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "E_Pinging";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "E_SetSettingAutonavForDesktop";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "E_Settings";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "E_Watch";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "GA_Continuation_CommentRepliesItem";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "GD_RC_SectionList";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "GD_RC_SectionList_p2";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "GM_VE11487_WC";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "GM_VE12924";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "GM_VE23462";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "GM_VE23462_WC";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "GM_VE3611";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "GM_VE37414_WC";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "GM_VE3832";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "GM_VE3854";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "GM_VE42352_WC";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "GM_VE4724";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "GM_VE5754_WC";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "GM_VE6827";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "GM_VE83769_WC";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "GM_VE96368_WC_browse";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "GT_ShortsSurfaceIdentifier";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "G_Action_GetNotificationsMenu_Popup";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "G_ClientSignal";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "G_PR_TrackingObj_f16";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "G_Text";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "G_Watch_ResultsItem";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "G_Watch_SecondaryResults_Contents";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "G_Watch_SecondaryResults_Results";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "MG_AdLayout";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "MP_AccountMenu";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "MP_SystemMenu";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "M_ResolveUrlCommand";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "M_VE3611";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "M_VE3854";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "NotchesItem";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "O_DU_Persistence";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "PD_continuation_params";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "PD_continuation_request_browse_token";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "PR_continuation_params";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "PR_continuation_request_browse_token";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "P_aadc_guidelines_state_entity_key";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "P_ad_layout_ad_serving_data_entry";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "P_ad_slot_logging_data_serialized_slot_ad_serving_data_entry";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "P_continuation_request_reel_watch_sequence_token";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "P_continuation_request_watch_next_token";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "P_create_backstage_post_params";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "P_create_comment_params";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "P_create_playlist_params";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "P_dislike_params";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "P_entity_key";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "P_entity_key_normal";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "P_format_item_xtags";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "P_get_notification_menu_ctoken";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "P_get_pdg_buy_flow_params";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "P_get_report_form_params";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "P_get_transcript_params";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "P_like_params";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "P_load_markers_entity_key";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "P_logging_context_serialized_context_data";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "P_logging_context_serialized_context_data.f1";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "P_macro_marker_repeat_state_entity_key";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "P_notification_opt_out";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "P_notification_record_interactions";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "P_playability_status_context_params";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "P_player_state_entity_key";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "P_playlist_loop_state_entity_key";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "P_reel_params";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "P_reel_player_params";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "P_reel_sequence_params";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "P_remove_like_params";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "P_shorts_source_bp";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "P_subscribe_button_entity_key";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "P_subscribe_params";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "P_subscription_state_key";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "P_transcript_track_selection_entity_key";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "P_transcript_track_selection_serialized_params";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "P_trending_bp";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "P_unsubscribe_params";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "P_ve_6827_params";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "P_watch_params";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "P_watch_player_params";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "P_watch_playlist_params";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "P_ypc_get_offers_params";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "Popup_DL_DismissibleDialog";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "Popup_GetAccountMenu";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "Popup_ShareEntityService";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "RCA_RelevantStateTags";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "RC_ConsistencyTokenJar";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "RC_MainAppWebResponseContext";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "RC_ResponseContext";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "RC_WR_ContextExtension";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "RD_MenuServiceItem";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "REG_AccountSwitcher";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "REG_DatasyncIds";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "RSB_EditPlaylist";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "RSG_GetUnseenCount";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "RSG_NotificationMenu";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "RSG_PdgBuyFlow";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "RSG_SearchSuggestions";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "RSG_SharePanel";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "RSG_SharePanel_Action";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "RSG_Survey";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "RSG_Transcript";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "RSL_Dislike";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "RSL_Like";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "RSL_RemoveLike";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "RSM_ChannelPreference";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "RSU_M";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "RSW_ReelItem";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "RS_AccountMenu";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "RS_AccountsList";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "RS_AttGet";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "RS_Browse";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "RS_Channel";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "RS_Feedback";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "RS_GetAddToPlaylist";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "RS_GetLiveChat";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "RS_Guide";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "RS_Next";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "RS_Page_Browse";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "RS_Page_Watch";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "RS_Player";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "RS_Playlist";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "RS_Reel";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "RS_ReelWatchSequence";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "RS_Search";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "RS_SearchPage";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "RS_SetSetting";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "RS_Settings";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "RS_ShortsPage";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "RS_Subscribe";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "RS_Subscribe_ActionItem_Action";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "RS_Success";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "RS_Unsubscribe";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "RS_Watch";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "R_Obj_f19";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "R_PageTypeBrowse";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "R_PageTypeBrowse_Response";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "R_PageTypeChannel";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "R_PageTypePlaylist";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "R_PageTypeSearch";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "R_PageTypeSettings";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "R_PageTypeShorts";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "R_PageTypeWatch";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "R_PlaylistPage";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "R_SettingsPage";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "R_WatchPage_VE3832";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "SI_DB_EngagementPanel_Ads";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "SI_VE124975_EngagementPanel";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "SI_VE126250_EngagementPanel";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "SI_VE139722_EngagementPanel";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "SI_VE76278_EngagementPanel";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "SI_VE99999_EngagementPanel";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "S_Client_Popup";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "S_GetAccountMenu";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "S_VideoGoodPutShape";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "S_VoiceSearchPopup_Dialog";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "Settings_VE23462";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "Shorts_VE37414";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "Signal_GetNotificationsMenu";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "StateTag";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "TD_ItemSection_2_CommentsEntryPoint";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "TE_Endpoint_2:AU_NotificationsUnseenCount";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "TE_Endpoint_2:A_AddChatItem";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "TE_Endpoint_2:A_AddToGuideSection";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "TE_Endpoint_2:A_AddToToast";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "TE_Endpoint_2:A_AppendContinuationItems";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "TE_Endpoint_2:A_ChangeEngagementPanelVisibility";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "TE_Endpoint_2:A_HideEnclosing";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "TE_Endpoint_2:A_HideEngagementPanelScrim";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "TE_Endpoint_2:A_ReplaceEnclosing";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "TE_Endpoint_2:A_SendFeedback";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "TE_Endpoint_2:A_SetActivePanelItem";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "TE_Endpoint_2:A_ShowEngagementPanelScrim";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "TE_Endpoint_2:A_Signal";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "TE_Endpoint_2:A_UndoFeedback";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "TE_Endpoint_2:CF_TE_Endpoint_2";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "TE_Endpoint_2:C_AddToPlaylist";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "TE_Endpoint_2:C_AdsControlFlowOpportunityReceived";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "TE_Endpoint_2:C_ChangeKeyedMarkersVisibility";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "TE_Endpoint_2:C_ChangeMarkersVisibility";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "TE_Endpoint_2:C_CommandExecutor";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "TE_Endpoint_2:C_EngagementPanelHeaderShowNavigationButton";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "TE_Endpoint_2:C_EntityUpdate";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "TE_Endpoint_2:C_FilterChipTransform";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "TE_Endpoint_2:C_FollowUp";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "TE_Endpoint_2:C_LoadMarkers";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "TE_Endpoint_2:C_Loop";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "TE_Endpoint_2:C_RefreshPlaylist";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "TE_Endpoint_2:C_RelatedChip";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "TE_Endpoint_2:C_ReloadContinuationItems";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "TE_Endpoint_2:C_RepeatChapter";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "TE_Endpoint_2:C_ResetChannelUnreadCount";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "TE_Endpoint_2:C_ShowReelsCommentsOverlay";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "TE_Endpoint_2:C_UpdateToggleButtonState";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "TE_Endpoint_2:E_ShowEngagementPanel";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "TE_Endpoint_2:E_YpcGetOfflineUpsell";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "TE_SignalService_I_0";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "TE_TrackedObj_2:AD_ReelDismissal";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "TE_TrackedObj_2:CF_TE_TrackedObj_2";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "TM_Visibility";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "TR_ItemSection";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "T_Autoplay";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "T_BaseUrl";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "T_Command_TP";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "T_DE_SettingItem.407";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "T_Icon:any:CF_T_Icon_Any";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "T_Icon:any:D_GuideEntry_Icon";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "T_Icon:any:D_GuideEntry_WithIcon:icon";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "T_Icon:any:D_GuideEntry_WithNavEP:icon";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "T_Icon:any:D_Icon_ThumbnailOverlaySidePanel";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "T_OpenPopup_Dialog:T_OpenPopup_Dialog";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "T_OpenPopup_Dialog:any";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "T_OpenPopup_Toast";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "T_Playlist";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "T_SecondaryResults";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "T_Types";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "T_UrlWrappedValue";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "ToggleButton.state";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "V_BinaryTimestamp";}
		|{n: Prelude.CF_M_s; t: Types.CF_M_s_; v: "XP_EntityPayload_Any";}
		|{n: Prelude.CF_M_w; t: Types.CF_M_w_; v: "D_ImpressionCap";}
		|{n: Prelude.CF_M_w; t: Types.CF_M_w_; v: "GM_SendPost";}
		|{n: Prelude.CF_M_w; t: Types.CF_M_w_; v: "GM_UserFeedback";}
		|{n: Prelude.CF_M_w; t: Types.CF_M_w_; v: "G_AdditionalDataItem";}
		|{n: Prelude.CF_M_w; t: Types.CF_M_w_; v: "G_EY_Entity_Any:G_EY_Entity";}
		|{n: Prelude.CF_M_w; t: Types.CF_M_w_; v: "Unpack:T_WCM:CF_T_WCM_Unpack";}
		|{n: Prelude.CF_M_w; t: Types.CF_M_w_; v: "Unpack:T_WCM:MG_Survey_CMD";}
		|{n: Prelude.CF_M_y; t: Types.CF_M_y_; v: "AD_HideEnclosing";}
		|{n: Prelude.CF_M_y; t: Types.CF_M_y_; v: "AD_HideEngagementPanelTargetId";}
		|{n: Prelude.CF_M_y; t: Types.CF_M_y_; v: "AU_ToggleButtonText";}
		|{n: Prelude.CF_M_y; t: Types.CF_M_y_; v: "AU_Viewership";}
		|{n: Prelude.CF_M_y; t: Types.CF_M_y_; v: "AU_ViewershipData";}
		|{n: Prelude.CF_M_y; t: Types.CF_M_y_; v: "B_HrefUrl";}
		|{n: Prelude.CF_M_y; t: Types.CF_M_y_; v: "CD_Invalidation";}
		|{n: Prelude.CF_M_y; t: Types.CF_M_y_; v: "CD_LiveChatReplay";}
		|{n: Prelude.CF_M_y; t: Types.CF_M_y_; v: "CD_Next";}
		|{n: Prelude.CF_M_y; t: Types.CF_M_y_; v: "CD_NextRadio";}
		|{n: Prelude.CF_M_y; t: Types.CF_M_y_; v: "CD_PlayerSeek";}
		|{n: Prelude.CF_M_y; t: Types.CF_M_y_; v: "CD_Reload";}
		|{n: Prelude.CF_M_y; t: Types.CF_M_y_; v: "DC_Continuation";}
		|{n: Prelude.CF_M_y; t: Types.CF_M_y_; v: "DC_Loop";}
		|{n: Prelude.CF_M_y; t: Types.CF_M_y_; v: "DC_PlayerSeek";}
		|{n: Prelude.CF_M_y; t: Types.CF_M_y_; v: "DC_ShowReelsCommentsOverlay";}
		|{n: Prelude.CF_M_y; t: Types.CF_M_y_; v: "DC_ShowReloadUi";}
		|{n: Prelude.CF_M_y; t: Types.CF_M_y_; v: "DE_PlaylistEditor";}
		|{n: Prelude.CF_M_y; t: Types.CF_M_y_; v: "DE_VE5754";}
		|{n: Prelude.CF_M_y; t: Types.CF_M_y_; v: "D_CanShare";}
		|{n: Prelude.CF_M_y; t: Types.CF_M_y_; v: "D_EditableDetails";}
		|{n: Prelude.CF_M_y; t: Types.CF_M_y_; v: "D_InfoCardIcon";}
		|{n: Prelude.CF_M_y; t: Types.CF_M_y_; v: "D_MenuPopup";}
		|{n: Prelude.CF_M_y; t: Types.CF_M_y_; v: "D_PlaylistByline";}
		|{n: Prelude.CF_M_y; t: Types.CF_M_y_; v: "D_PlaylistPanelVideo";}
		|{n: Prelude.CF_M_y; t: Types.CF_M_y_; v: "D_ProfilePageHeaderTitle";}
		|{n: Prelude.CF_M_y; t: Types.CF_M_y_; v: "D_ProfilePageHeaderTitle_Content";}
		|{n: Prelude.CF_M_y; t: Types.CF_M_y_; v: "D_RelatedChipCloud";}
		|{n: Prelude.CF_M_y; t: Types.CF_M_y_; v: "D_StartSeconds";}
		|{n: Prelude.CF_M_y; t: Types.CF_M_y_; v: "D_StreamSelectionConfig";}
		|{n: Prelude.CF_M_y; t: Types.CF_M_y_; v: "D_StructuredDescriptionPlaylistLockup";}
		|{n: Prelude.CF_M_y; t: Types.CF_M_y_; v: "D_Survey_Watch";}
		|{n: Prelude.CF_M_y; t: Types.CF_M_y_; v: "D_ThumbnailOverlayBottomPanel";}
		|{n: Prelude.CF_M_y; t: Types.CF_M_y_; v: "D_ThumbnailOverlayNowPlaying";}
		|{n: Prelude.CF_M_y; t: Types.CF_M_y_; v: "D_ThumbnailOverlayResumePlayback";}
		|{n: Prelude.CF_M_y; t: Types.CF_M_y_; v: "R_ToggleButtonIdData";}
		|{n: Prelude.CF_M_y; t: Types.CF_M_y_; v: "T_Item";}
		|{n: Prelude.CF_M_y; t: Types.CF_M_y_; v: "UA_DateText";}
		|{n: Prelude.CF_M_y; t: Types.CF_M_y_; v: "UA_DateTextData";}
		|{n: Prelude.CF_M_y; t: Types.CF_M_y_; v: "UA_Description";}
		|{n: Prelude.CF_M_y; t: Types.CF_M_y_; v: "UA_Title";}
		|{n: Prelude.CF_M_y; t: Types.CF_M_y_; v: "UA_TitleData";}
		|{n: Prelude.CF_RS_Page_Type1; t: Types.CF_RS_Page_Type1_; v: "RS_Page_Channel";}
		|{n: Prelude.CF_RS_Page_Type1; t: Types.CF_RS_Page_Type1_; v: "R_PageTypeBrowse_Response";}
		|{n: Prelude.CF_TA_OpenPopup; t: Types.CF_TA_OpenPopup_; v: "A_ConfirmDialog";}
		|{n: Prelude.CF_TA_OpenPopup; t: Types.CF_TA_OpenPopup_; v: "A_FancyDismissibleDialog";}
		|{n: Prelude.CF_TA_OpenPopup; t: Types.CF_TA_OpenPopup_; v: "A_GetAccountMenu";}
		|{n: Prelude.CF_TA_OpenPopup; t: Types.CF_TA_OpenPopup_; v: "A_GetSystemMenu";}
		|{n: Prelude.CF_TA_OpenPopup; t: Types.CF_TA_OpenPopup_; v: "DE_ShareEntityService";}
		|{n: Prelude.CF_TA_OpenPopup; t: Types.CF_TA_OpenPopup_; v: "G_Action_GetNotificationsMenu";}
		|{n: Prelude.CF_TA_OpenPopup; t: Types.CF_TA_OpenPopup_; v: "RSG_NotificationMenu_Action";}
		|{n: Prelude.CF_TA_OpenPopup; t: Types.CF_TA_OpenPopup_; v: "RSM_ChannelPreference";}
		|{n: Prelude.CF_TA_OpenPopup; t: Types.CF_TA_OpenPopup_; v: "TA_OpenPopup:R_PdgBuyFlow";}
		|{n: Prelude.CF_TA_OpenPopup; t: Types.CF_TA_OpenPopup_; v: "TA_OpenPopup_Empty";}
		|{n: Prelude.CF_TA_Page; t: Types.CF_TA_Page_; v: "AD_UpdateChannelSwitcherPage";}
		|{n: Prelude.CF_TD_ItemSection; t: Types.CF_TD_ItemSection_; v: "TD_ItemSection_1<any>";}
		|{n: Prelude.CF_TD_ItemSection; t: Types.CF_TD_ItemSection_; v: "TD_ItemSection_3<\"comment-item-section\",\"comments-section\">";}
		|{n: Prelude.CF_TD_ItemSection; t: Types.CF_TD_ItemSection_; v: "TD_ItemSection_3<\"comment-item-section\",\"engagement-panel-comments-section\">";}
		|{n: Prelude.CF_TD_ItemSection; t: Types.CF_TD_ItemSection_; v: "TD_ItemSection_3<\"sid-wn-chips\",\"watch-next-feed\">";}
		|{n: Prelude.CF_TD_Params; t: Types.CF_TD_Params_; v: "DE_CreateBackstagePost";}
		|{n: Prelude.CF_TD_Params; t: Types.CF_TD_Params_; v: "DE_CreateComment";}
		|{n: Prelude.CF_TD_Params; t: Types.CF_TD_Params_; v: "DE_YpcGetCart";}
		|{n: Prelude.CF_TE_Endpoint_2; t: Types.CF_TE_Endpoint_2_; v: "AU_NotificationsUnseenCount";}
		|{n: Prelude.CF_TE_Endpoint_2; t: Types.CF_TE_Endpoint_2_; v: "A_AddChatItem";}
		|{n: Prelude.CF_TE_Endpoint_2; t: Types.CF_TE_Endpoint_2_; v: "A_AddToGuideSection";}
		|{n: Prelude.CF_TE_Endpoint_2; t: Types.CF_TE_Endpoint_2_; v: "A_AddToToast";}
		|{n: Prelude.CF_TE_Endpoint_2; t: Types.CF_TE_Endpoint_2_; v: "A_AppendContinuationItems";}
		|{n: Prelude.CF_TE_Endpoint_2; t: Types.CF_TE_Endpoint_2_; v: "A_ChangeEngagementPanelVisibility";}
		|{n: Prelude.CF_TE_Endpoint_2; t: Types.CF_TE_Endpoint_2_; v: "A_HideEnclosing";}
		|{n: Prelude.CF_TE_Endpoint_2; t: Types.CF_TE_Endpoint_2_; v: "A_HideEngagementPanelScrim";}
		|{n: Prelude.CF_TE_Endpoint_2; t: Types.CF_TE_Endpoint_2_; v: "A_ReplaceEnclosing";}
		|{n: Prelude.CF_TE_Endpoint_2; t: Types.CF_TE_Endpoint_2_; v: "A_SendFeedback";}
		|{n: Prelude.CF_TE_Endpoint_2; t: Types.CF_TE_Endpoint_2_; v: "A_SetActivePanelItem";}
		|{n: Prelude.CF_TE_Endpoint_2; t: Types.CF_TE_Endpoint_2_; v: "A_ShowEngagementPanelScrim";}
		|{n: Prelude.CF_TE_Endpoint_2; t: Types.CF_TE_Endpoint_2_; v: "A_Signal";}
		|{n: Prelude.CF_TE_Endpoint_2; t: Types.CF_TE_Endpoint_2_; v: "A_UndoFeedback";}
		|{n: Prelude.CF_TE_Endpoint_2; t: Types.CF_TE_Endpoint_2_; v: "C_AddToPlaylist";}
		|{n: Prelude.CF_TE_Endpoint_2; t: Types.CF_TE_Endpoint_2_; v: "C_AdsControlFlowOpportunityReceived";}
		|{n: Prelude.CF_TE_Endpoint_2; t: Types.CF_TE_Endpoint_2_; v: "C_ChangeKeyedMarkersVisibility";}
		|{n: Prelude.CF_TE_Endpoint_2; t: Types.CF_TE_Endpoint_2_; v: "C_ChangeMarkersVisibility";}
		|{n: Prelude.CF_TE_Endpoint_2; t: Types.CF_TE_Endpoint_2_; v: "C_CommandExecutor";}
		|{n: Prelude.CF_TE_Endpoint_2; t: Types.CF_TE_Endpoint_2_; v: "C_EngagementPanelHeaderShowNavigationButton";}
		|{n: Prelude.CF_TE_Endpoint_2; t: Types.CF_TE_Endpoint_2_; v: "C_EntityUpdate";}
		|{n: Prelude.CF_TE_Endpoint_2; t: Types.CF_TE_Endpoint_2_; v: "C_FilterChipTransform";}
		|{n: Prelude.CF_TE_Endpoint_2; t: Types.CF_TE_Endpoint_2_; v: "C_FollowUp";}
		|{n: Prelude.CF_TE_Endpoint_2; t: Types.CF_TE_Endpoint_2_; v: "C_LoadMarkers";}
		|{n: Prelude.CF_TE_Endpoint_2; t: Types.CF_TE_Endpoint_2_; v: "C_Loop";}
		|{n: Prelude.CF_TE_Endpoint_2; t: Types.CF_TE_Endpoint_2_; v: "C_RefreshPlaylist";}
		|{n: Prelude.CF_TE_Endpoint_2; t: Types.CF_TE_Endpoint_2_; v: "C_RelatedChip";}
		|{n: Prelude.CF_TE_Endpoint_2; t: Types.CF_TE_Endpoint_2_; v: "C_ReloadContinuationItems";}
		|{n: Prelude.CF_TE_Endpoint_2; t: Types.CF_TE_Endpoint_2_; v: "C_RepeatChapter";}
		|{n: Prelude.CF_TE_Endpoint_2; t: Types.CF_TE_Endpoint_2_; v: "C_ResetChannelUnreadCount";}
		|{n: Prelude.CF_TE_Endpoint_2; t: Types.CF_TE_Endpoint_2_; v: "C_ShowReelsCommentsOverlay";}
		|{n: Prelude.CF_TE_Endpoint_2; t: Types.CF_TE_Endpoint_2_; v: "C_UpdateToggleButtonState";}
		|{n: Prelude.CF_TE_Endpoint_2; t: Types.CF_TE_Endpoint_2_; v: "E_ShowEngagementPanel";}
		|{n: Prelude.CF_TE_Endpoint_2; t: Types.CF_TE_Endpoint_2_; v: "E_YpcGetOfflineUpsell";}
		|{n: Prelude.CF_TE_Endpoint_3; t: Types.CF_TE_Endpoint_3_; v: "C_GetPdgBuyFlow";}
		|{n: Prelude.CF_TE_Endpoint_3; t: Types.CF_TE_Endpoint_3_; v: "E_AddToPlaylistService";}
		|{n: Prelude.CF_TE_Endpoint_3; t: Types.CF_TE_Endpoint_3_; v: "E_CreateBackstagePost";}
		|{n: Prelude.CF_TE_Endpoint_3; t: Types.CF_TE_Endpoint_3_; v: "E_CreateComment";}
		|{n: Prelude.CF_TE_Endpoint_3; t: Types.CF_TE_Endpoint_3_; v: "E_CreatePlaylistService";}
		|{n: Prelude.CF_TE_Endpoint_3; t: Types.CF_TE_Endpoint_3_; v: "E_GetNotificationMenu";}
		|{n: Prelude.CF_TE_Endpoint_3; t: Types.CF_TE_Endpoint_3_; v: "E_GetReportForm";}
		|{n: Prelude.CF_TE_Endpoint_3; t: Types.CF_TE_Endpoint_3_; v: "E_GetTranscript";}
		|{n: Prelude.CF_TE_Endpoint_3; t: Types.CF_TE_Endpoint_3_; v: "E_Like";}
		|{n: Prelude.CF_TE_Endpoint_3; t: Types.CF_TE_Endpoint_3_; v: "E_NotificationOptOut";}
		|{n: Prelude.CF_TE_Endpoint_3; t: Types.CF_TE_Endpoint_3_; v: "E_PlaylistDelete";}
		|{n: Prelude.CF_TE_Endpoint_3; t: Types.CF_TE_Endpoint_3_; v: "E_PlaylistEdit";}
		|{n: Prelude.CF_TE_Endpoint_3; t: Types.CF_TE_Endpoint_3_; v: "E_PlaylistEditor";}
		|{n: Prelude.CF_TE_Endpoint_3; t: Types.CF_TE_Endpoint_3_; v: "E_RecordNotificationInteractions";}
		|{n: Prelude.CF_TE_Endpoint_3; t: Types.CF_TE_Endpoint_3_; v: "E_ShareEntityService";}
		|{n: Prelude.CF_TE_Endpoint_3; t: Types.CF_TE_Endpoint_3_; v: "E_SignalNavigation";}
		|{n: Prelude.CF_TE_Endpoint_3; t: Types.CF_TE_Endpoint_3_; v: "E_Subscribe";}
		|{n: Prelude.CF_TE_Endpoint_3; t: Types.CF_TE_Endpoint_3_; v: "E_UndoFeedback";}
		|{n: Prelude.CF_TE_Endpoint_3; t: Types.CF_TE_Endpoint_3_; v: "E_Unsubscribe";}
		|{n: Prelude.CF_TE_Endpoint_3; t: Types.CF_TE_Endpoint_3_; v: "E_VE11487";}
		|{n: Prelude.CF_TE_Endpoint_3; t: Types.CF_TE_Endpoint_3_; v: "E_VE23462";}
		|{n: Prelude.CF_TE_Endpoint_3; t: Types.CF_TE_Endpoint_3_; v: "E_VE3611";}
		|{n: Prelude.CF_TE_Endpoint_3; t: Types.CF_TE_Endpoint_3_; v: "E_VE37414_ReelWatch";}
		|{n: Prelude.CF_TE_Endpoint_3; t: Types.CF_TE_Endpoint_3_; v: "E_VE42352";}
		|{n: Prelude.CF_TE_Endpoint_3; t: Types.CF_TE_Endpoint_3_; v: "E_VE4724_Search";}
		|{n: Prelude.CF_TE_Endpoint_3; t: Types.CF_TE_Endpoint_3_; v: "E_VE5754";}
		|{n: Prelude.CF_TE_Endpoint_3; t: Types.CF_TE_Endpoint_3_; v: "E_VE83769_Upload";}
		|{n: Prelude.CF_TE_Endpoint_3; t: Types.CF_TE_Endpoint_3_; v: "E_VE83769_Url";}
		|{n: Prelude.CF_TE_Endpoint_3; t: Types.CF_TE_Endpoint_3_; v: "E_VE96368";}
		|{n: Prelude.CF_TE_Endpoint_3; t: Types.CF_TE_Endpoint_3_; v: "E_Watch";}
		|{n: Prelude.CF_TE_Endpoint_3; t: Types.CF_TE_Endpoint_3_; v: "E_WatchPlaylist";}
		|{n: Prelude.CF_TE_Endpoint_3; t: Types.CF_TE_Endpoint_3_; v: "E_YpcGetCart";}
		|{n: Prelude.CF_TE_Endpoint_3; t: Types.CF_TE_Endpoint_3_; v: "E_YpcGetOffers";}
		|{n: Prelude.CF_TE_Endpoint_Opt_3; t: Types.CF_TE_Endpoint_Opt_3_; v: "C_Continuation";}
		|{n: Prelude.CF_TE_TrackedObj_2; t: Types.CF_TE_TrackedObj_2_; v: "AD_ReelDismissal";}
		|{n: Prelude.CF_TR_MultiPageMenu; t: Types.CF_TR_MultiPageMenu_; v: "D_NotificationMenu_PopupItemMenu";}
		|{n: Prelude.CF_TR_MultiPageMenu; t: Types.CF_TR_MultiPageMenu_; v: "P_NotificationMenu_Popup";}
		|{n: Prelude.CF_TR_MultiPageMenu; t: Types.CF_TR_MultiPageMenu_; v: "R_AccountMenu";}
		|{n: Prelude.CF_TR_MultiPageMenu; t: Types.CF_TR_MultiPageMenu_; v: "R_SystemMenu";}
		|{n: Prelude.CF_TR_MultiPageMenu; t: Types.CF_TR_MultiPageMenu_; v: "R_TopbarMenu";}
		|{n: Prelude.CF_TR_MultiPageMenu; t: Types.CF_TR_MultiPageMenu_; v: "TR_MultiPageMenu_Empty";}
		|{n: Prelude.CF_TR_MultiPageMenu; t: Types.CF_TR_MultiPageMenu_; v: "any";}
		|{n: Prelude.CF_T_Commands; t: Types.CF_T_Commands_; v: "DC_CommandExecutor";}
		|{n: Prelude.CF_T_GM; t: Types.CF_T_GM_; v: "GM_AccountMenu";}
		|{n: Prelude.CF_T_GM; t: Types.CF_T_GM_; v: "GM_AddToPlaylistService";}
		|{n: Prelude.CF_T_GM; t: Types.CF_T_GM_; v: "GM_AddUpcomingEventReminder";}
		|{n: Prelude.CF_T_GM; t: Types.CF_T_GM_; v: "GM_Browse";}
		|{n: Prelude.CF_T_GM; t: Types.CF_T_GM_; v: "GM_CreateBackstagePost";}
		|{n: Prelude.CF_T_GM; t: Types.CF_T_GM_; v: "GM_CreateComment";}
		|{n: Prelude.CF_T_GM; t: Types.CF_T_GM_; v: "GM_CreatePlaylist";}
		|{n: Prelude.CF_T_GM; t: Types.CF_T_GM_; v: "GM_Dislike";}
		|{n: Prelude.CF_T_GM; t: Types.CF_T_GM_; v: "GM_EditPlaylist";}
		|{n: Prelude.CF_T_GM; t: Types.CF_T_GM_; v: "GM_Feedback";}
		|{n: Prelude.CF_T_GM; t: Types.CF_T_GM_; v: "GM_FlagGetForm";}
		|{n: Prelude.CF_T_GM; t: Types.CF_T_GM_; v: "GM_GetNotificationMenu";}
		|{n: Prelude.CF_T_GM; t: Types.CF_T_GM_; v: "GM_GetSettingsEditor";}
		|{n: Prelude.CF_T_GM; t: Types.CF_T_GM_; v: "GM_GetSharePanel";}
		|{n: Prelude.CF_T_GM; t: Types.CF_T_GM_; v: "GM_GetTranscript";}
		|{n: Prelude.CF_T_GM; t: Types.CF_T_GM_; v: "GM_GetUnseenNotificationCount";}
		|{n: Prelude.CF_T_GM; t: Types.CF_T_GM_; v: "GM_LikeLike";}
		|{n: Prelude.CF_T_GM; t: Types.CF_T_GM_; v: "GM_Next";}
		|{n: Prelude.CF_T_GM; t: Types.CF_T_GM_; v: "GM_NotificationOptOut";}
		|{n: Prelude.CF_T_GM; t: Types.CF_T_GM_; v: "GM_PlaylistDelete";}
		|{n: Prelude.CF_T_GM; t: Types.CF_T_GM_; v: "GM_RecordInteractions";}
		|{n: Prelude.CF_T_GM; t: Types.CF_T_GM_; v: "GM_RemoveLike";}
		|{n: Prelude.CF_T_GM; t: Types.CF_T_GM_; v: "GM_RemoveUpcomingEventReminder";}
		|{n: Prelude.CF_T_GM; t: Types.CF_T_GM_; v: "GM_SetSetting";}
		|{n: Prelude.CF_T_GM; t: Types.CF_T_GM_; v: "GM_Subscribe";}
		|{n: Prelude.CF_T_GM; t: Types.CF_T_GM_; v: "GM_YpcGetOffers";}
		|{n: Prelude.CF_T_Icon; t: Types.CF_T_Icon_; v: "DMD_Badge_LiveNow";}
		|{n: Prelude.CF_T_Icon; t: Types.CF_T_Icon_; v: "DMD_Badge_MediumGray";}
		|{n: Prelude.CF_T_Icon; t: Types.CF_T_Icon_; v: "DMD_Badge_Verified";}
		|{n: Prelude.CF_T_Icon; t: Types.CF_T_Icon_; v: "DMD_Badge_VerifiedArtist";}
		|{n: Prelude.CF_T_Icon; t: Types.CF_T_Icon_; v: "D_Button.icon";}
		|{n: Prelude.CF_T_Icon; t: Types.CF_T_Icon_; v: "D_Button:command.icon";}
		|{n: Prelude.CF_T_Icon; t: Types.CF_T_Icon_; v: "D_Button:navigationEndpoint.icon";}
		|{n: Prelude.CF_T_Icon; t: Types.CF_T_Icon_; v: "D_Button:serviceEndpoint.icon";}
		|{n: Prelude.CF_T_Icon; t: Types.CF_T_Icon_; v: "D_Button:style.icon";}
		|{n: Prelude.CF_T_Icon; t: Types.CF_T_Icon_; v: "D_EmojiPickerCategoryButton:ForChannel:icon";}
		|{n: Prelude.CF_T_Icon; t: Types.CF_T_Icon_; v: "D_EmojiPickerCategoryButton:icon";}
		|{n: Prelude.CF_T_Icon; t: Types.CF_T_Icon_; v: "D_EmojiPickerCategoryButton:targetId:icon";}
		|{n: Prelude.CF_T_Icon; t: Types.CF_T_Icon_; v: "D_Guide_CollapseIcon";}
		|{n: Prelude.CF_T_Icon; t: Types.CF_T_Icon_; v: "D_Guide_ExpandIcon";}
		|{n: Prelude.CF_T_Icon; t: Types.CF_T_Icon_; v: "D_Icon_Search";}
		|{n: Prelude.CF_T_Icon; t: Types.CF_T_Icon_; v: "D_MixIcon";}
		|{n: Prelude.CF_T_Icon; t: Types.CF_T_Icon_; v: "D_PaidContentOverlay";}
		|{n: Prelude.CF_T_Icon; t: Types.CF_T_Icon_; v: "D_PrivacyDropdownItem";}
		|{n: Prelude.CF_T_Icon; t: Types.CF_T_Icon_; v: "D_PromotedSparklesWeb:icon";}
		|{n: Prelude.CF_T_Icon; t: Types.CF_T_Icon_; v: "D_ReelMultimixAttributionLabel";}
		|{n: Prelude.CF_T_Icon; t: Types.CF_T_Icon_; v: "D_RichMetadata_BoxArt:icon";}
		|{n: Prelude.CF_T_Icon; t: Types.CF_T_Icon_; v: "D_RichMetadata_Topic:icon";}
		|{n: Prelude.CF_T_Icon; t: Types.CF_T_Icon_; v: "D_ThumbnailOverlayToggleButton_ToggledPrefix:icon";}
		|{n: Prelude.CF_T_Icon; t: Types.CF_T_Icon_; v: "D_ThumbnailOverlayToggleButton_UntoggledPrefix_1:icon";}
		|{n: Prelude.CF_T_Icon; t: Types.CF_T_Icon_; v: "D_ThumbnailOverlayToggleButton_UntoggledPrefix_2:icon";}
		|{n: Prelude.CF_T_Icon; t: Types.CF_T_Icon_; v: "D_TopbarLogo:iconImage";}
		|{n: Prelude.CF_T_Icon_Any; t: Types.CF_T_Icon_Any_; v: "D_GuideEntry_Icon";}
		|{n: Prelude.CF_T_Icon_Any; t: Types.CF_T_Icon_Any_; v: "D_GuideEntry_WithIcon:icon";}
		|{n: Prelude.CF_T_Icon_Any; t: Types.CF_T_Icon_Any_; v: "D_GuideEntry_WithNavEP:icon";}
		|{n: Prelude.CF_T_Icon_Any; t: Types.CF_T_Icon_Any_; v: "D_Icon_ThumbnailOverlaySidePanel";}
		|{n: Prelude.CF_T_Items; t: Types.CF_T_Items_; v: "D_ProfileColumn";}
		|{n: Prelude.CF_T_Items_TP; t: Types.CF_T_Items_TP_; v: "R_CompactLink_Items";}
		|{n: Prelude.CF_T_OpenPopup_Dropdown; t: Types.CF_T_OpenPopup_Dropdown_; v: "Popup_DD_SystemMenu";}
		|{n: Prelude.CF_T_SE_Signal; t: Types.CF_T_SE_Signal_; v: "D_GuideEntry_WithIcon.SE_Signal";}
		|{n: Prelude.CF_T_SE_Signal; t: Types.CF_T_SE_Signal_; v: "D_NotificationTopbarButton.U_UnseenCount.T_SE_Signal";}
		|{n: Prelude.CF_T_SE_Signal; t: Types.CF_T_SE_Signal_; v: "D_NotificationTopbarButton.menuRequest.T_SE_Signal";}
		|{n: Prelude.CF_T_SE_Signal; t: Types.CF_T_SE_Signal_; v: "D_TopbarMenuButton.SE_Signal";}
		|{n: Prelude.CF_T_SE_Signal; t: Types.CF_T_SE_Signal_; v: "E_SignalService_SendPost";}
		|{n: Prelude.CF_T_SE_Signal; t: Types.CF_T_SE_Signal_; v: "GC_Button.SE_Signal";}
		|{n: Prelude.CF_T_Signal; t: Types.CF_T_Signal_; v: "DE_SignalNavigation";}
		|{n: Prelude.CF_T_Signal; t: Types.CF_T_Signal_; v: "DE_SubmitFeedback";}
		|{n: Prelude.CF_T_WCM; t: Types.CF_T_WCM_; v: "MC_Continuation";}
		|{n: Prelude.CF_T_WCM; t: Types.CF_T_WCM_; v: "M_AccountMenu";}
		|{n: Prelude.CF_T_WCM; t: Types.CF_T_WCM_; v: "M_AddToPlaylistService";}
		|{n: Prelude.CF_T_WCM; t: Types.CF_T_WCM_; v: "M_AddUpcomingEventReminder";}
		|{n: Prelude.CF_T_WCM; t: Types.CF_T_WCM_; v: "M_Browse";}
		|{n: Prelude.CF_T_WCM; t: Types.CF_T_WCM_; v: "M_CreateBackstagePost";}
		|{n: Prelude.CF_T_WCM; t: Types.CF_T_WCM_; v: "M_CreateComment";}
		|{n: Prelude.CF_T_WCM; t: Types.CF_T_WCM_; v: "M_CreatePlaylist";}
		|{n: Prelude.CF_T_WCM; t: Types.CF_T_WCM_; v: "M_EditPlaylist";}
		|{n: Prelude.CF_T_WCM; t: Types.CF_T_WCM_; v: "M_Feedback";}
		|{n: Prelude.CF_T_WCM; t: Types.CF_T_WCM_; v: "M_FlagGetForm";}
		|{n: Prelude.CF_T_WCM; t: Types.CF_T_WCM_; v: "M_GetNotificationMenu";}
		|{n: Prelude.CF_T_WCM; t: Types.CF_T_WCM_; v: "M_GetPdgBuyFlow";}
		|{n: Prelude.CF_T_WCM; t: Types.CF_T_WCM_; v: "M_GetSettingsEditor";}
		|{n: Prelude.CF_T_WCM; t: Types.CF_T_WCM_; v: "M_GetSharePanel";}
		|{n: Prelude.CF_T_WCM; t: Types.CF_T_WCM_; v: "M_GetTranscript";}
		|{n: Prelude.CF_T_WCM; t: Types.CF_T_WCM_; v: "M_GetUnseenNotificationCount";}
		|{n: Prelude.CF_T_WCM; t: Types.CF_T_WCM_; v: "M_Like";}
		|{n: Prelude.CF_T_WCM; t: Types.CF_T_WCM_; v: "M_Next";}
		|{n: Prelude.CF_T_WCM; t: Types.CF_T_WCM_; v: "M_NotificationOptOut";}
		|{n: Prelude.CF_T_WCM; t: Types.CF_T_WCM_; v: "M_PlaylistDelete";}
		|{n: Prelude.CF_T_WCM; t: Types.CF_T_WCM_; v: "M_RecordInteractions";}
		|{n: Prelude.CF_T_WCM; t: Types.CF_T_WCM_; v: "M_RemoveUpcomingEventReminder";}
		|{n: Prelude.CF_T_WCM; t: Types.CF_T_WCM_; v: "M_SendPost";}
		|{n: Prelude.CF_T_WCM; t: Types.CF_T_WCM_; v: "M_SetSetting";}
		|{n: Prelude.CF_T_WCM; t: Types.CF_T_WCM_; v: "M_Subscribe";}
		|{n: Prelude.CF_T_WCM; t: Types.CF_T_WCM_; v: "M_Unsubscribe";}
		|{n: Prelude.CF_T_WCM; t: Types.CF_T_WCM_; v: "M_UserFeedback";}
		|{n: Prelude.CF_T_WCM; t: Types.CF_T_WCM_; v: "M_VE12924";}
		|{n: Prelude.CF_T_WCM; t: Types.CF_T_WCM_; v: "M_VE37414";}
		|{n: Prelude.CF_T_WCM; t: Types.CF_T_WCM_; v: "M_VE3832";}
		|{n: Prelude.CF_T_WCM; t: Types.CF_T_WCM_; v: "M_VE42352";}
		|{n: Prelude.CF_T_WCM; t: Types.CF_T_WCM_; v: "M_VE4724";}
		|{n: Prelude.CF_T_WCM; t: Types.CF_T_WCM_; v: "M_VE5754";}
		|{n: Prelude.CF_T_WCM; t: Types.CF_T_WCM_; v: "M_VE83769";}
		|{n: Prelude.CF_T_WCM; t: Types.CF_T_WCM_; v: "M_VE96368";}
		|{n: Prelude.CF_T_WCM; t: Types.CF_T_WCM_; v: "M_YpcGetCart";}
		|{n: Prelude.CF_T_WCM; t: Types.CF_T_WCM_; v: "M_YpcGetOffers";}
		|{n: Prelude.CF_T_WCM_Unpack; t: Types.CF_T_WCM_Unpack_; v: "MG_Survey_CMD";}
		|{n: Prelude.CF_add_string_to_map; t: Types.CF_add_string_to_map_; v: "D_ToggleButton";}
		|{n: Prelude.CF_onMissingIcon; t: Types.CF_onMissingIcon_; v: "D_GuideEntry_WithIcon";}
		|{n: Prelude.CF_onMissingIcon; t: Types.CF_onMissingIcon_; v: "D_GuideEntry_WithNavEP";}
		|{n: Prelude.CF_onMissingIcon; t: Types.CF_onMissingIcon_; v: "D_ThumbnailOverlaySidePanel";}
		|{n: Prelude.CF_parse_identifier; t: Types.CF_parse_identifier_; v: "SI_VE126250_Identifier";}
		|{n: Prelude.CF_parse_identifier; t: Types.CF_parse_identifier_; v: "SI_VE76278_Identifier";}
		|{n: Prelude.P_ParamParse; t: Types.P_ParamParse_; v: "aadc_guidelines_state.entity_key";}
		|{n: Prelude.P_ParamParse; t: Types.P_ParamParse_; v: "ad_layout.ad_serving_data_entry";}
		|{n: Prelude.P_ParamParse; t: Types.P_ParamParse_; v: "ad_slot_logging_data.serialized_slot_ad_serving_data_entry";}
		|{n: Prelude.P_ParamParse; t: Types.P_ParamParse_; v: "adaptive_format_item.xtags";}
		|{n: Prelude.P_ParamParse; t: Types.P_ParamParse_; v: "change_markers_visibility.entity.key";}
		|{n: Prelude.P_ParamParse; t: Types.P_ParamParse_; v: "continuation.params";}
		|{n: Prelude.P_ParamParse; t: Types.P_ParamParse_; v: "continuation_request.browse.token";}
		|{n: Prelude.P_ParamParse; t: Types.P_ParamParse_; v: "continuation_request.reel_watch_sequence.token";}
		|{n: Prelude.P_ParamParse; t: Types.P_ParamParse_; v: "continuation_request.watch_next.token";}
		|{n: Prelude.P_ParamParse; t: Types.P_ParamParse_; v: "create_backstage_post.params";}
		|{n: Prelude.P_ParamParse; t: Types.P_ParamParse_; v: "create_comment.params";}
		|{n: Prelude.P_ParamParse; t: Types.P_ParamParse_; v: "create_playlist.params";}
		|{n: Prelude.P_ParamParse; t: Types.P_ParamParse_; v: "dislike.params";}
		|{n: Prelude.P_ParamParse; t: Types.P_ParamParse_; v: "entity.key";}
		|{n: Prelude.P_ParamParse; t: Types.P_ParamParse_; v: "entity_key.normal";}
		|{n: Prelude.P_ParamParse; t: Types.P_ParamParse_; v: "format_item.xtags";}
		|{n: Prelude.P_ParamParse; t: Types.P_ParamParse_; v: "get_notification_menu.ctoken";}
		|{n: Prelude.P_ParamParse; t: Types.P_ParamParse_; v: "get_pdg_buy_flow.params";}
		|{n: Prelude.P_ParamParse; t: Types.P_ParamParse_; v: "get_report_form.params";}
		|{n: Prelude.P_ParamParse; t: Types.P_ParamParse_; v: "get_transcript.params";}
		|{n: Prelude.P_ParamParse; t: Types.P_ParamParse_; v: "instream_video_ad.player_vars";}
		|{n: Prelude.P_ParamParse; t: Types.P_ParamParse_; v: "invalidation.continuation";}
		|{n: Prelude.P_ParamParse; t: Types.P_ParamParse_; v: "like.params";}
		|{n: Prelude.P_ParamParse; t: Types.P_ParamParse_; v: "live_chat_replay.continuation";}
		|{n: Prelude.P_ParamParse; t: Types.P_ParamParse_; v: "load_markers.entity_key";}
		|{n: Prelude.P_ParamParse; t: Types.P_ParamParse_; v: "logging_context.serialized_context_data";}
		|{n: Prelude.P_ParamParse; t: Types.P_ParamParse_; v: "macro_marker_repeat_state.entity_key";}
		|{n: Prelude.P_ParamParse; t: Types.P_ParamParse_; v: "macro_markers_list.entity.key";}
		|{n: Prelude.P_ParamParse; t: Types.P_ParamParse_; v: "next.continuation";}
		|{n: Prelude.P_ParamParse; t: Types.P_ParamParse_; v: "next.queue_context.params";}
		|{n: Prelude.P_ParamParse; t: Types.P_ParamParse_; v: "next_radio.continuation";}
		|{n: Prelude.P_ParamParse; t: Types.P_ParamParse_; v: "notification.opt_out";}
		|{n: Prelude.P_ParamParse; t: Types.P_ParamParse_; v: "notification.record_interactions";}
		|{n: Prelude.P_ParamParse; t: Types.P_ParamParse_; v: "notification_add_upcoming_event_reminder.params";}
		|{n: Prelude.P_ParamParse; t: Types.P_ParamParse_; v: "notification_remove_upcoming_event_reminder.params";}
		|{n: Prelude.P_ParamParse; t: Types.P_ParamParse_; v: "params.click_tracking";}
		|{n: Prelude.P_ParamParse; t: Types.P_ParamParse_; v: "params.tracking";}
		|{n: Prelude.P_ParamParse; t: Types.P_ParamParse_; v: "playability_status.context_params";}
		|{n: Prelude.P_ParamParse; t: Types.P_ParamParse_; v: "player_seek.continuation";}
		|{n: Prelude.P_ParamParse; t: Types.P_ParamParse_; v: "player_state.entity_key";}
		|{n: Prelude.P_ParamParse; t: Types.P_ParamParse_; v: "playlist_edit.params";}
		|{n: Prelude.P_ParamParse; t: Types.P_ParamParse_; v: "playlist_loop_state.entity.key";}
		|{n: Prelude.P_ParamParse; t: Types.P_ParamParse_; v: "reel.params";}
		|{n: Prelude.P_ParamParse; t: Types.P_ParamParse_; v: "reel.player_params";}
		|{n: Prelude.P_ParamParse; t: Types.P_ParamParse_; v: "reel.sequence_params";}
		|{n: Prelude.P_ParamParse; t: Types.P_ParamParse_; v: "reload.continuation";}
		|{n: Prelude.P_ParamParse; t: Types.P_ParamParse_; v: "remove_like.params";}
		|{n: Prelude.P_ParamParse; t: Types.P_ParamParse_; v: "shorts.source.bp";}
		|{n: Prelude.P_ParamParse; t: Types.P_ParamParse_; v: "subscribe.params";}
		|{n: Prelude.P_ParamParse; t: Types.P_ParamParse_; v: "subscribe_button.entity_key";}
		|{n: Prelude.P_ParamParse; t: Types.P_ParamParse_; v: "subscription_state.key";}
		|{n: Prelude.P_ParamParse; t: Types.P_ParamParse_; v: "timed_continuation.data";}
		|{n: Prelude.P_ParamParse; t: Types.P_ParamParse_; v: "transcript_track_selection.entity.key";}
		|{n: Prelude.P_ParamParse; t: Types.P_ParamParse_; v: "transcript_track_selection.serialized_params";}
		|{n: Prelude.P_ParamParse; t: Types.P_ParamParse_; v: "trending.bp";}
		|{n: Prelude.P_ParamParse; t: Types.P_ParamParse_; v: "unsubscribe.params";}
		|{n: Prelude.P_ParamParse; t: Types.P_ParamParse_; v: "ve_3611.params";}
		|{n: Prelude.P_ParamParse; t: Types.P_ParamParse_; v: "ve_6827.params";}
		|{n: Prelude.P_ParamParse; t: Types.P_ParamParse_; v: "watch.params";}
		|{n: Prelude.P_ParamParse; t: Types.P_ParamParse_; v: "watch.player_params";}
		|{n: Prelude.P_ParamParse; t: Types.P_ParamParse_; v: "watch_playlist.params";}
		|{n: Prelude.P_ParamParse; t: Types.P_ParamParse_; v: "ypc_get_cart.transaction_params";}
		|{n: Prelude.P_ParamParse; t: Types.P_ParamParse_; v: "ypc_get_offers.params";}
		|{n: Prelude.P_ParamParse; t: Types.P_ParamParse_; v: "ypc_get_offline_upsell.params";}
		;
}
