version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - Aboukhadijeh
  - bouncingdvdlogo
  - buyables
  - comlen
  - cxlen
  - dddbg
  - decodedata
  - doublequote
  - dslen
  - dvdbouncinglogo
  - dvdlogo
  - Edef
  - Feross
  - idxoff
  - nxfn
  - presfn
  - printf
  - punct
  - sidx
  - singlequote
  - slen
  - sslen
  - sssx
  - stlen
  - symin
  - thecentralscrutinizer
  - trgfs
  - ZWNJ
ignoreWords: []
import: []
