version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - Aboukhadijeh
  - bouncingdvdlogo
  - buyables
  - chunksz
  - citv
  - cmap
  - comlen
  - cxlen
  - dddbg
  - decodedata
  - dname
  - doublequote
  - dslen
  - ducdat
  - dvdbouncinglogo
  - dvdlogo
  - Edef
  - Elems
  - exdo_user
  - expando
  - Feross
  - ffunc
  - fnlist
  - fnname
  - found_objs
  - foward
  - gameiframe
  - genpower
  - googlejs
  - grps
  - idxoff
  - ilen
  - jqts
  - jsfilt
  - jsfout
  - maxall
  - mquery
  - mult
  - mults
  - nxfn
  - objs
  - presfn
  - printf
  - protos
  - punct
  - retcp
  - retv
  - sarr
  - scount
  - sfunc
  - sidx
  - singlequote
  - slen
  - sslen
  - sssx
  - start_objs
  - stlen
  - symin
  - syms
  - thecentralscrutinizer
  - trgfs
  - uerr
  - varg
  - webassembly
  - xmhrp
  - ZWNJ
ignoreWords: []
import: []
