version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - Aboukhadijeh
  - absl
  - abslbin
  - absldec
  - achi
  - adsbygoogle
  - aend
  - akadd
  - alens
  - allspec
  - analyse
  - anid
  - argsar
  - arrmap
  - astart
  - asya
  - asyfn
  - atomepersecond
  - atomsinvest
  - autobuy
  - autobuyer
  - bouncingdvdlogo
  - Breit
  - buyables
  - cbfn
  - checkspec
  - chunksz
  - cint
  - citv
  - cloneable
  - cmap
  - comlen
  - constexpr
  - cres
  - cstruct
  - cxlen
  - dbgln
  - dddbg
  - Debuggable
  - decodedata
  - decpart
  - decreaseSpawnCooldown
  - deref
  - desync
  - dname
  - dofn
  - DONT_CONSUME_NEXT_INPUT_CHARACTER
  - doublequote
  - dslen
  - ducdat
  - dups
  - dvdbouncinglogo
  - dvdlogo
  - Edef
  - Elems
  - evaler
  - exdo_user
  - expando
  - externref
  - Feross
  - ffunc
  - fmar
  - fmnb
  - fmstr
  - fnlist
  - fnname
  - FormattableTypes
  - found_objs
  - foward
  - froms
  - fstr
  - gameiframe
  - genfunc
  - genpower
  - genret
  - genworkertime
  - gitdir
  - googlejs
  - grps
  - hostch
  - idents
  - idxoff
  - ilen
  - jqts
  - jsfilt
  - jsfout
  - lazyload
  - lightgray
  - lightreset
  - maxall
  - milli
  - milli_acc
  - milli_len
  - millis
  - mkadd
  - mlis
  - mnum
  - monospace
  - mquery
  - mult
  - mults
  - newcp
  - nocheckin
  - nodenext
  - noframe
  - noti
  - nthis
  - nuxt_visitor
  - nvitr
  - nxfn
  - objs
  - odarr
  - oncontextlost
  - oncontextrestored
  - onformdata
  - onslotchange
  - onwebkitanimationend
  - onwebkitanimationiteration
  - onwebkitanimationstart
  - onwebkittransitionend
  - outar
  - Paran
  - parsejs
  - percentgencur
  - plen
  - plurials
  - precreate
  - presfn
  - primordials
  - printf
  - probj
  - protos
  - proxied
  - punct
  - raquo
  - RAWTEXT
  - RCDATA
  - realpath
  - rebuildtheuniverse
  - reconsume
  - regs
  - reqs
  - resa
  - retcp
  - retpr
  - retv
  - rewalk
  - sandboxed
  - sargs
  - sarr
  - scount
  - sfunc
  - sidx
  - singlequote
  - slen
  - specialclick
  - specialsbought
  - sslen
  - sssx
  - start_objs
  - stid
  - stlen
  - symin
  - syms
  - tampermonkey
  - targets_achi
  - tarl
  - thecentralscrutinizer
  - timeout_milli
  - timeplayed
  - tkey
  - tlele
  - tlen
  - tlis
  - tobj
  - tonext
  - totalAchi
  - totalAtome
  - treeverse
  - trgfs
  - Typecheck
  - typechecked
  - uerr
  - undebug
  - Unforgeable
  - Unregisters
  - updateprogress
  - Userland
  - userscript
  - varg
  - verifymethod
  - webassembly
  - Wipfli
  - workch
  - xarray
  - xmhrp
  - ZWNJ
ignoreWords: []
import: []
