import {Accessibility} from "../../_/a/Accessibility.js";
import {MenuRendererH} from "../../_/m/MenuRendererH.js";
import {MetadataBadgeRenderers} from "../../_/m/MetadataBadgeRenderers.js";
import {NavigationEndpoint} from "../n/NavigationEndpoint.js";
import {SimpleTextFixmeValueNeeded} from "../s/SimpleText.js";
import {TextRuns} from "../t/TextRuns.js";
import {ThumbnailH} from "../t/ThumbnailH.js";
import {ThumbnailOverlay} from "../t/ThumbnailOverlay.js";
import {ThumbnailsList} from "../t/ThumbnailsList.js";
import {TrackingParams} from "../t/TrackingParams.js";
import {RichThumbnail} from "../../rich/RichThumbnail.js";

export interface CompactVideoRenderer extends TrackingParams {
	accessibility: Accessibility<string>;
	badges?: MetadataBadgeRenderers[];
	channelThumbnail: ThumbnailH;
	lengthText: SimpleTextFixmeValueNeeded;
	longBylineText: TextRuns;
	menu: MenuRendererH;
	navigationEndpoint: NavigationEndpoint;
	ownerBadges?: MetadataBadgeRenderers[];
	publishedTimeText: SimpleTextFixmeValueNeeded;
	richThumbnail?: RichThumbnail;
	shortBylineText: TextRuns;
	shortViewCountText: SimpleTextFixmeValueNeeded;
	thumbnail: ThumbnailsList;
	thumbnailOverlays: ThumbnailOverlay[];
	title: SimpleTextFixmeValueNeeded;
	trackingParams: string;
	videoId: string;
	viewCountText: SimpleTextFixmeValueNeeded;
};
