type R_Player={
	responseContext: RC$ResponseContext;
	playabilityStatus: D__PlayabilityStatus;
	streamingData?: D__StreamingData;
	heartbeatParams?: D__HeartbeatParams;
	playerAds?: R_DesktopWatchAds[];
	playbackTracking?: D__PlaybackTracking;
	captions?: R_PlayerCaptionsTracklist;
	videoDetails?: D__VideoDetails;
	playerConfig?: D__PlayerConfig;
	storyboards?: R_PlayerStoryboardSpec|R_PlayerLiveStoryboardSpec;
	microformat?: R_PlayerMicroformat;
	cards?: R_CardCollection;
	trackingParams: string;
	attestation?: R_PlayerAttestation;
	videoQualityPromoSupportedRenderers?: R_VideoQualityPromo;
	adPlacements?: Maybe<R_AdPlacement>[];
	frameworkUpdates: A_FrameworkUpdates;
	endscreen?: R_Endscreen;
	paidContentOverlay?: {};
	annotations?: R_PlayerAnnotationsExpanded[];
}