type R$Player={
	responseContext: RC$ResponseContext;
	playabilityStatus: D__PlayabilityStatus;
	streamingData?: D__StreamingData;
	heartbeatParams?: D__HeartbeatParams;
	playerAds?: R$DesktopWatchAds[];
	playbackTracking?: D__PlaybackTracking;
	captions?: R$PlayerCaptionsTracklist;
	videoDetails?: D__VideoDetails;
	playerConfig?: D__PlayerConfig;
	storyboards?: R$PlayerStoryboardSpec|R$PlayerLiveStoryboardSpec;
	microformat?: R$PlayerMicroformat;
	cards?: R$CardCollection;
	trackingParams: string;
	attestation?: R$PlayerAttestation;
	videoQualityPromoSupportedRenderers?: R$VideoQualityPromo;
	adPlacements?: Maybe<R$AdPlacement>[];
	frameworkUpdates: A$FrameworkUpdates;
	endscreen?: R$Endscreen;
	paidContentOverlay?: {};
	annotations?: R$PlayerAnnotationsExpanded[];
}