//#region Renderer
export type R_AboutThisAd={aboutThisAdRenderer: D_AboutThisAd;};
export type R_AccountItem={accountItemRenderer: D_AccountItem;};
export type R_AccountItemSection={accountItemSectionRenderer: D_AccountItemSection;};
export type R_AccountLinkButton={accountLinkButtonRenderer: D_AccountLinkButton;};
export type R_AccountSectionList={accountSectionListRenderer: Record<"contents",R_AccountItemSection[]>;};
export type R_ActionCompanionAd={actionCompanionAdRenderer: D_ActionCompanionAd;};
export type R_AdActionInterstitial={adActionInterstitialRenderer: D_AdActionInterstitial;};
export type R_AdBreakService={adBreakServiceRenderer: D_AdBreakService;};
export type R_AddToPlaylist={addToPlaylistRenderer: D_AddToPlaylist;};
export type R_AddToPlaylistCreate={addToPlaylistCreateRenderer: D_AddToPlaylistCreate;};
export type R_AdHoverTextButton={adHoverTextButtonRenderer: D_AdHoverTextButton;};
export type R_AdPlacement={adPlacementRenderer: D_AdPlacement;};
export type R_AdPlacementConfig={adPlacementConfig: D_AdPlacementConfig;};
export type R_AdsEngagementPanelContent={adsEngagementPanelContentRenderer: B_Hack;};
export type R_AdSlot={adSlotRenderer: D_AdSlot;};
export type R_AlertWithButton={alertWithButtonRenderer: D_AlertWithButton;};
export type R_AutomixPreviewVideo={automixPreviewVideoRenderer: D_AutomixPreviewVideo;};
export type R_AutoplaySwitchButton={autoplaySwitchButtonRenderer: D_AutoplaySwitchButton;};
export type R_BrowseEndpointContextMusicConfig={browseEndpointContextMusicConfig: D_BrowseEndpointContextMusicConfig;};
export type R_BrowseFeedActions={browseFeedActionsRenderer: D_BrowseFeedActions;};
export type R_BrowserMediaSessionRenderer={browserMediaSessionRenderer: D_BrowserMediaSessionRenderer;};
export type R_C4TabbedHeader={c4TabbedHeaderRenderer: D_C4TabbedHeader;};
export type R_Card={cardRenderer: D_Card;};
export type R_CardCollection={cardCollectionRenderer: D_CardCollection;};
export type R_CarouselLockup={carouselLockupRenderer: D_CarouselLockup;};
export type R_Channel_MD={channelMetadataRenderer: D_Channel_MD;};
export type R_ChannelHeaderLinks={channelHeaderLinksRenderer: D_ChannelHeaderLinks;};
export type R_ChannelOptions={channelOptionsRenderer: D_ChannelOptions;};
export type R_ChannelSwitcherHeader={channelSwitcherHeaderRenderer: D_ChannelSwitcherHeader;};
export type R_ChannelSwitcherPage={channelSwitcherPageRenderer: D_ChannelSwitcherPage;};
export type R_ChannelThumbnailWithLink={channelThumbnailWithLinkRenderer: D_ChannelThumbnailWithLink;};
export type R_Chapter={chapterRenderer: D_Chapter;};
export type R_CheckboxSurveyOption={checkboxSurveyOptionRenderer: D_CheckboxSurveyOption;};
export type R_ChildVideo={childVideoRenderer: D_ChildVideo;};
export type R_ChipCloud={chipCloudRenderer: D_ChipCloud;};
export type R_ChipCloudChip={chipCloudChipRenderer: D_ChipCloudChip;};
export type R_CinematicContainer={cinematicContainerRenderer: D_CinematicContainer;};
export type R_ClientForecastingAd={clientForecastingAdRenderer: D_ClientForecastingAd;};
export type R_ClipAdState={clipAdStateRenderer: D_ClipAdState;};
export type R_ClipCreation={clipCreationRenderer: D_ClipCreation;};
export type R_ClipCreationScrubber={clipCreationScrubberRenderer: D_ClipCreationScrubber;};
export type R_ClipCreationTextInput={clipCreationTextInputRenderer: D_ClipCreationTextInput;};
export type R_ClipSection={clipSectionRenderer: D_ClipSection;};
export type R_Comment={commentRenderer: D_Comment;};
export type R_CommentActionButtons={commentActionButtonsRenderer: D_CommentActionButtons;};
export type R_CommentsEntryPointHeader={commentsEntryPointHeaderRenderer: D_CommentsEntryPointHeader;};
export type R_CommentsEntryPointTeaser={commentsEntryPointTeaserRenderer: D_CommentsEntryPointTeaser;};
export type R_CommentsHeader={commentsHeaderRenderer: D_CommentsHeader;};
export type R_CommentSimplebox={commentSimpleboxRenderer: D_CommentSimplebox;};
export type R_CommentThread={commentThreadRenderer: D_CommentThread;};
export type R_CommonConfig={commonConfig: D_CommonConfig;};
export type R_CompactLink={compactLinkRenderer: D_CompactLink;};
export type R_CompactPlaylist={compactPlaylistRenderer: D_CompactPlaylist;};
export type R_CompactRadio={compactRadioRenderer: D_CompactRadio;};
export type R_CompactVideo={compactVideoRenderer: D_CompactVideo;};
export type R_ConfirmDialog={confirmDialogRenderer: D_ConfirmDialog;};
export type R_ConnectedApp={connectedAppRenderer: D_ConnectedApp;};
export type R_ContinuationItem={continuationItemRenderer: D_ContinuationItem;};
export type R_CopyLink={copyLinkRenderer: D_CopyLink;};
export type R_DecoratedPlayerBar={decoratedPlayerBarRenderer: D_DecoratedPlayerBar;};
export type R_DefaultButton={buttonRenderer: D_Button;};
export type R_DescriptionChaptersItem=T_MapEntry<"DESCRIPTION_CHAPTERS",D_DescriptionChapters>;
export type R_DesktopTopbar={desktopTopbarRenderer: D_DesktopTopbar;};
export type R_DesktopWatchAds={playerLegacyDesktopWatchAdsRenderer: D_DesktopWatchAds;};
export type R_DisplayAd={displayAdRenderer: D_DisplayAd;};
export type R_Dropdown={dropdownRenderer: D_Dropdown_Privacy;};
export type R_ElementUpdate={updates: D_ElementUpdate[];};
export type R_EmojiPicker={emojiPickerRenderer: D_EmojiPicker;};
export type R_Endscreen={endscreenRenderer: D_Endscreen;};
export type R_EndscreenElement={endscreenElementRenderer: D_EndscreenElement;};
export type R_EndScreenPlaylist={endScreenPlaylistRenderer: D_EndScreenPlaylist;};
export type R_EndScreenVideo={endScreenVideoRenderer: D_EndScreenVideo;};
export type R_EngagementPanelSectionList={engagementPanelSectionListRenderer: D_EngagementPanelSectionList;};
export type R_EngagementPanelTitleHeader={engagementPanelTitleHeaderRenderer: D_EngagementPanelTitleHeader;};
export type R_ExpandableSurveyResponse={expandableSurveyResponseRenderer: D_ExpandableSurveyResponse;};
export type R_ExpandableTab={expandableTabRenderer: D_ExpandableTab;};
export type R_ExpandableVideoDescriptionBody={expandableVideoDescriptionBodyRenderer: D_ExpandableVideoDescriptionBody;};
export type R_Factoid={factoidRenderer: D_Factoid;};
export type R_FancyDismissibleDialog={fancyDismissibleDialogRenderer: D_FancyDismissibleDialog;};
export type R_FeedFilterChipBar={feedFilterChipBarRenderer: D_FeedFilterChipBar;};
export type R_FeedNudge={feedNudgeRenderer: D_FeedNudge;};
export type R_FeedTabbedHeader={feedTabbedHeaderRenderer: D_FeedTabbedHeader;};
export type D_FulfilledLayout_Item=R_FulfilledLayoutContent|R_FulfillmentLayoutContent;
export type R_FulfilledLayout={fulfilledLayout: D_FulfilledLayout_Item;};
export type R_FulfilledLayoutContent=R_PageTopAdLayout;
export type R_FulfillmentLayoutContent=R_InFeedAdLayout;
export type R_FusionSearchbox={fusionSearchboxRenderer: D_FusionSearchbox;};
export type R_General=R_SettingsSidebar;
export type R_GhostGrid={ghostGridRenderer: D_GhostGrid;};
export type R_GuideCollapsibleEntry={guideCollapsibleEntryRenderer: D_GuideCollapsibleEntry;};
export type R_GuideCollapsibleSectionEntry={guideCollapsibleSectionEntryRenderer: D_GuideCollapsibleSectionEntry;};
export type R_GuideDownloadsEntry={guideDownloadsEntryRenderer: D_GuideDownloadsEntry;};
export type R_GuideEntry={guideEntryRenderer: D_GuideEntry;};
export type R_GuideEntryData={guideEntryData: D_GuideEntryData;};
export type R_GuideSection={guideSectionRenderer: D_GuideSection;};
export type R_GuideSubscriptionsSection={guideSubscriptionsSectionRenderer: D_GuideSubscriptionsSection;};
export type R_Heatmap={heatmapRenderer: D_Heatmap;};
export type R_HeatSeekerItem=T_MapEntry<"HEATSEEKER",D_HeatSeekerItemData>;
export type R_HeroPlaylistThumbnail={heroPlaylistThumbnailRenderer: D_HeroPlaylistThumbnail;};
export type R_Hint={hintRenderer: D_Hint;};
export type R_HorizontalCardList={horizontalCardListRenderer: D_HorizontalCardList;};
export type R_HotkeyDialog={hotkeyDialogRenderer: D_HotkeyDialog;};
export type R_HotkeyDialogSection={hotkeyDialogSectionRenderer: D_HotkeyDialogSection;};
export type R_HotkeyDialogSectionOption={hotkeyDialogSectionOptionRenderer: D_HotkeyDialogSectionOption;};
export type R_Html5PlaybackOnesieConfig={html5PlaybackOnesieConfig: R_CommonConfig;};
export type R_InFeedAdLayout={inFeedAdLayoutRenderer: D_InFeedAdLayout;};
export type R_InfoCardIcon={infoCardIconRenderer: D_InfoCardIcon;};
export type D_InfoCardIcon=D_TrackingParams;
export type R_InfoRow={infoRowRenderer: D_InfoRow;};
export type R_InlineSurvey={inlineSurveyRenderer: D_InlineSurvey;};
export type R_InstreamVideoAd={instreamVideoAdRenderer: D_InstreamVideoAd;};
export type R_ItemSectionHeader={itemSectionHeaderRenderer: D_ItemSectionHeader;};
export type R_LikeButton={likeButtonRenderer: D_LikeButton;};
export type R_LinearAdSequence={linearAdSequenceRenderer: D_LinearAdSequence;};
export type R_LiveChatAuthorBadge={liveChatAuthorBadgeRenderer: D_LiveChatAuthorBadge;};
export type R_LiveChatHeader={liveChatHeaderRenderer: D_LiveChatHeader;};
export type R_LiveChatItemList={liveChatItemListRenderer: D_LiveChatItemList;};
export type R_LiveChatMessageInput={liveChatMessageInputRenderer: D_LiveChatMessageInput;};
export type R_LiveChatParticipantsList={liveChatParticipantsListRenderer: D_LiveChatParticipantsList;};
export type R_LiveChatPlaceholderItem={liveChatPlaceholderItemRenderer: D_LiveChatPlaceholderItem;};
export type R_LiveChatTextMessage={liveChatTextMessageRenderer: D_LiveChatTextMessage;};
export type R_LiveChatTicker={liveChatTickerRenderer: D_LiveChatTicker;};
export type R_LiveChatViewerEngagementMessage={liveChatViewerEngagementMessageRenderer: D_LiveChatViewerEngagementMessage;};
export type R_MacroMarkersList={macroMarkersListRenderer: D_MacroMarkersList;};
export type R_MacroMarkersListItem={macroMarkersListItemRenderer: D_MacroMarkersListItem;};
export type R_Menu={menuRenderer: D_Menu;};
export type R_MenuFlexibleItem={menuFlexibleItemRenderer: DT_MenuFlexibleItem;};
export type R_MenuNavigationItem={menuNavigationItemRenderer: D_MenuNavigationItem;};
export type R_MenuServiceItem={menuServiceItemRenderer: RD_MenuServiceItem;};
export type R_MerchandiseItem={merchandiseItemRenderer: D_MerchandiseItem;};
export type R_MerchandiseShelf={merchandiseShelfRenderer: D_MerchandiseShelf;};
export type R_Message={messageRenderer: D_Message;};
export type R_MetadataRow={metadataRowRenderer: D_MetadataRow;};
export type R_MicroformatData={microformatDataRenderer: D_Microformat;};
export type R_Miniplayer={miniplayerRenderer: D_Miniplayer;};
export type R_MovingThumbnail={movingThumbnailRenderer: D_MovingThumbnail;};
export type R_MultiMarkersPlayerBar={multiMarkersPlayerBarRenderer: D_MultiMarkersPlayerBar;};
export type R_MusicCarouselShelf={musicCarouselShelfRenderer: D_MusicCarouselShelf;};
export type R_MusicHeader={musicHeaderRenderer: {};};
export type R_MusicQueue={musicQueueRenderer: D_MusicQueue;};
export type R_MusicResponsiveListItem={musicResponsiveListItemRenderer: D_MusicResponsiveListItem;};
export type R_MusicShelf={musicShelfRenderer: D_MusicShelf;};
export type R_MusicShelfDivider={musicShelfDividerRenderer: D_MusicShelfDivider;};
export type R_MusicThumbnail={musicThumbnailRenderer: D_MusicThumbnail;};
export type R_Notification={notificationRenderer: D_Notification;};
export type R_NotificationText={notificationTextRenderer: D_NotificationText;};
export type R_NotificationTopbarButton={notificationTopbarButtonRenderer: D_NotificationTopbarButton;};
export type R_Page={trackingParams: string; contents: R_TwoColumnBrowseResults[];};
export type R_PageIntroduction={pageIntroductionRenderer: D_PageIntroduction;};
export type R_PageTopAdLayout={pageTopAdLayoutRenderer: D_PageTopAdLayout;};
export type R_PdgBuyFlow={pdgBuyFlowRenderer: D_PdgBuyFlow;};
export type R_PdgBuyFlowHeader={pdgBuyFlowHeaderRenderer: D_PdgBuyFlowHeader;};
export type R_PdgColorSlider={pdgColorSliderRenderer: D_PdgColorSlider;};
export type R_PdgCommentChip={pdgCommentChipRenderer: D_PdgCommentChip;};
export type R_PdgCommentOption={pdgCommentOptionRenderer: D_PdgCommentOption;};
export type R_PdgCommentPreview={pdgCommentPreviewRenderer: D_PdgCommentPreview;};
export type R_PivotButton={pivotButtonRenderer: D_PivotButton;};
export type R_PlayerAnnotationsExpanded={playerAnnotationsExpandedRenderer: D_PlayerAnnotationsExpanded;};
export type R_PlayerAttestation={playerAttestationRenderer: D_PlayerAttestation;};
export type R_PlayerCaptionsTracklist={playerCaptionsTracklistRenderer: D_PlayerCaptionsTracklist;};
export type R_PlayerLiveStoryboardSpec={playerLiveStoryboardSpecRenderer: D_PlayerLiveStoryboardSpec;};
export type R_PlayerMicroformat={playerMicroformatRenderer: D_PlayerMicroformat;};
export type R_PlayerOverlay={playerOverlayRenderer: D_PlayerOverlay;};
export type R_PlayerOverlayAutoplay={playerOverlayAutoplayRenderer: D_PlayerOverlayAutoplay;};
export type R_PlayerOverlayVideoDetails={playerOverlayVideoDetailsRenderer: D_PlayerOverlayVideoDetails;};
export type R_PlayerStoryboardSpec={playerStoryboardSpecRenderer: D_PlayerStoryboardSpec;};
export type R_Playlist_MD={playlistMetadataRenderer: D_Playlist_MD;};
export type R_PlaylistAddToOption={playlistAddToOptionRenderer: D_PlaylistAddToOption;};
export type R_PlaylistByline={playlistBylineRenderer: D_PlaylistByline;};
export type R_PlaylistContent={trackingParams: string; contents: R_TwoColumnBrowseResults[];};
export type R_PlaylistHeader={playlistHeaderRenderer: D_PlaylistHeader;};
export type R_PlaylistPanel={playlistPanelRenderer: D_PlaylistPanel;};
export type R_PlaylistPanelVideo={playlistPanelVideoRenderer: D_PlaylistPanelVideo;};
export type R_PlaylistSidebar={playlistSidebarRenderer: D_PlaylistSidebar;};
export type R_PlaylistSidebarPrimaryInfo={playlistSidebarPrimaryInfoRenderer: D_PlaylistSidebarPrimaryInfo;};
export type D_PlaylistSidebarPrimaryInfo={
	thumbnailRenderer: R_PlaylistVideoThumbnail;
	title?: G_Text;
	stats: G_Text[];
	menu: R_Menu;
	thumbnailOverlays: G_ThumbnailOverlayItem[];
	navigationEndpoint: E_Watch;
	badges?: RMD_Badge[];
	description?: {};
	showMoreText: G_Text;
	titleForm?: R_InlineForm;
	descriptionForm?: R_InlineForm;
	privacyForm?: R_DropdownFormField;
};
type R_PlaylistSidebarSecondaryInfo={playlistSidebarSecondaryInfoRenderer: D_PlaylistSidebarSecondaryInfo;};
type R_PlaylistVideoList={playlistVideoListRenderer: D_PlaylistVideoList;};
type R_PlaylistVideoThumbnail={playlistVideoThumbnailRenderer: D_PlaylistVideoThumbnail;};
type R_PrefetchHintConfig={prefetchHintConfig: D_PrefetchHintConfig;};
type R_PrivacyDropdownItem={privacyDropdownItemRenderer: D_PrivacyDropdownItem;};
type R_ProductList={productListRenderer: D_ProductList;};
type R_ProductListItem={productListItemRenderer: D_ProductListItem;};
type R_ProfileColumn={profileColumnRenderer: D_ProfileColumn;};
type R_ProfileColumnStats={profileColumnStatsRenderer: D_ProfileColumnStats;};
type R_ProfileColumnStatsEntry={profileColumnStatsEntryRenderer: D_ProfileColumnStatsEntry;};
type R_ProfileColumnUserInfo={profileColumnUserInfoRenderer: D_ProfileColumnUserInfo;};
type R_ProfilePageHeaderButtonRowViewModel={profilePageHeaderButtonRowViewModel: {};};
type R_ProfilePageHeaderInformationViewModel={profilePageHeaderInformationViewModel: D_ProfilePageHeaderInformation;};
type R_ProfilePageHeaderMetadataViewModel={profilePageHeaderMetadataViewModel: {};};
type R_ProfilePageHeaderThumbnailViewModel={profilePageHeaderThumbnailViewModel: {};};
type R_ProfilePageHeaderTitleViewModel={profilePageHeaderTitleViewModel: D_ProfilePageHeaderTitle;};
type R_PromotedSparklesWeb={promotedSparklesWebRenderer: D_PromotedSparklesWeb;};
type R_Radio={radioRenderer: D_Radio;};
type R_RadioButtonSurveyOption={radioButtonSurveyOptionRenderer: D_RadioButtonSurveyOption;};
type R_RatingSurvey={ratingSurveyRenderer: D_RatingSurvey;};
type R_RatingSurveyOption={ratingSurveyOptionRenderer: D_RatingSurveyOption;};
type R_ReelItem={reelItemRenderer: D_ReelItem;};
type R_ReelMultimixAttributionLabel={reelMultimixAttributionLabelRenderer: D_ReelMultimixAttributionLabel;};
type R_ReelPlayerHeader={reelPlayerHeaderRenderer: D_ReelPlayerHeader;};
type R_ReelPlayerOverlay={reelPlayerOverlayRenderer: D_ReelPlayerOverlay;};
type R_ReelShelf={reelShelfRenderer: D_ReelShelf;};
type R_RelatedChipCloud={relatedChipCloudRenderer: D_RelatedChipCloud;};
type R_ReportFormModal={reportFormModalRenderer: D_ReportFormModal;};
type R_ResourceStatusInResponseCheck={resourceStatusInResponseCheck: D_ResourceStatusInResponseCheck;};
type R_RichGrid={richGridRenderer: D_RichGrid;};
type R_RichItem={richItemRenderer: D_RichItem;};
type R_RichListHeader={richListHeaderRenderer: D_RichListHeader;};
type R_RichMetadata={richMetadataRenderer: D_RichMetadata;};
type R_RichMetadataRow={richMetadataRowRenderer: D_RichMetadataRow;};
type R_RichSection={richSectionRenderer: D_RichSection;};
type R_RichShelf={richShelfRenderer: D_RichShelf;};
type R_RichThumbnail={movingThumbnailRenderer: D_MovingThumbnail;};
type R_SampledThumbnailColor={sampledThumbnailColor: D_ThumbnailColor;};
type R_SearchBox={searchBoxRenderer: D_SearchBox;};
type R_SearchPyv={searchPyvRenderer: D_SearchPyv;};
type R_SearchResultsTab={tabRenderer: D_SearchResultsTab;};
type R_SectionList={sectionListRenderer: GD_RC_SectionList;};
type R_SegmentedLikeDislikeButton={segmentedLikeDislikeButtonRenderer: D_SegmentedLikeDislikeButton;};
type R_SettingsCheckbox={settingsCheckboxRenderer: D_SettingsCheckbox;};
type R_SettingsOption={settingsOptionsRenderer: D_SettingsOptions;};
type R_SettingsRadioOption={settingsRadioOptionRenderer: D_SettingsRadioOption;};
type R_SettingsSidebar={settingsSidebarRenderer: D_SettingsSidebar;};
type R_SettingsSwitch={settingsSwitchRenderer: D_SettingsSwitch;};
type R_SimpleMenuHeader={simpleMenuHeaderRenderer: D_SimpleMenuHeader;};
type R_SingleColumnMusicWatchNextResults={singleColumnMusicWatchNextResultsRenderer: R_Tabbed;};
type R_SortFilterSubMenu={sortFilterSubMenuRenderer: D_SortFilterSubMenu;};
type R_SourcePivotHeader={sourcePivotHeaderRenderer: D_SourcePivotHeader;};
type R_StructuredDescriptionContent={structuredDescriptionContentRenderer: D_StructuredDescriptionContent;};
type R_SubFeedOption={subFeedOptionRenderer: D_SubFeedOption;};
type R_SubFeedSelector={subFeedSelectorRenderer: D_SubFeedSelector;};
type R_SubscribeButton={subscribeButtonRenderer: D_SubscribeButton;};
type R_SubscriptionNotificationToggleButton={subscriptionNotificationToggleButtonRenderer: D_SubscriptionNotificationToggleButton;};
type R_SuperVodBuyFlowContent={superVodBuyFlowContentRenderer: D_SuperVodBuyFlowContent;};
type R_Tab={tabRenderer: D_Tab;};
type R_Tabbed={tabbedRenderer: R_WatchNextTabbedResults;};
type R_TabbedSearchResults={tabbedSearchResultsRenderer: D_TabbedSearchResults;};
type R_TemplateUpdate={templateUpdate: D_TemplateUpdate;};
type R_TextInputFormField={textInputFormFieldRenderer: D_TextInputFormField;};
type R_ThumbnailOverlayBottomPanel={thumbnailOverlayBottomPanelRenderer: D_ThumbnailOverlayBottomPanel;};
type R_ThumbnailOverlayEndorsement={thumbnailOverlayEndorsementRenderer: D_ThumbnailOverlayEndorsement;};
type R_ThumbnailOverlayHoverText={thumbnailOverlayHoverTextRenderer: D_ThumbnailOverlayHoverText;};
type R_ThumbnailOverlayLoadingPreview={thumbnailOverlayLoadingPreviewRenderer: D_ThumbnailOverlayLoadingPreview;};
type R_ThumbnailOverlayNowPlaying={thumbnailOverlayNowPlayingRenderer: D_ThumbnailOverlayNowPlaying;};
type R_ThumbnailOverlayResumePlayback={thumbnailOverlayResumePlaybackRenderer: D_ThumbnailOverlayResumePlayback;};
type R_ThumbnailOverlaySidePanel={thumbnailOverlaySidePanelRenderer: D_ThumbnailOverlaySidePanel;};
type R_ThumbnailOverlayTimeStatus={thumbnailOverlayTimeStatusRenderer: D_ThumbnailOverlayTimeStatus;};
type R_ThumbnailOverlayToggleButton={thumbnailOverlayToggleButtonRenderer: D_ThumbnailOverlayToggleButton;};
type R_ToggleButton={toggleButtonRenderer: D_ToggleButton;};
type R_ToggleMenuServiceItem={toggleMenuServiceItemRenderer: D_ToggleMenuServiceItem;};
type R_TopbarLogo={topbarLogoRenderer: D_TopbarLogo;};
type R_TopbarMenuButton={topbarMenuButtonRenderer: D_TopbarMenuButton;};
type R_TopicLink={topicLinkRenderer: D_TopicLink;};
type R_Transcript={transcriptRenderer: D_Transcript;};
type R_TranscriptFooter={transcriptFooterRenderer: D_TranscriptFooter;};
type R_TranscriptSearchPanel={transcriptSearchPanelRenderer: D_TranscriptSearchPanel;};
type R_TranscriptSegment={transcriptSegmentRenderer: D_TranscriptSegment;};
type R_TranscriptSegmentList={transcriptSegmentListRenderer: D_TranscriptSegmentList;};
type R_TwoColumnBrowseResults={twoColumnBrowseResultsRenderer: D_TwoColumnBrowseResults;};
type R_TwoColumnSearchResults={twoColumnSearchResultsRenderer: D_TwoColumnSearchResults;};
type R_UnifiedSharePanel={unifiedSharePanelRenderer: D_UnifiedSharePanel;};
type R_Video={videoRenderer: D_Video;};
type R_VideoDescriptionHeader={videoDescriptionHeaderRenderer: D_VideoDescriptionHeader;};
type R_VideoDescriptionMusicSection={videoDescriptionMusicSectionRenderer: D_VideoDescriptionMusicSection;};
type R_VideoMastheadAdV3={videoMastheadAdV3Renderer: D_VideoMastheadAdV3;};
type R_VideoOwner={videoOwnerRenderer: D_VideoOwner;};
type R_VideoPrimaryInfo={videoPrimaryInfoRenderer: D_VideoPrimaryInfo;};
type R_VideoQualityPromo={videoQualityPromoRenderer: D_VideoQualityPromo;};
type R_VideoSecondaryInfo={videoSecondaryInfoRenderer: D_VideoSecondaryInfo;};
type R_VideoViewCount={videoViewCountRenderer: D_VideoViewCount;};
type R_VoiceSearchDialog={voiceSearchDialogRenderer: D_VoiceSearchDialog;};
type R_VssLoggingContext={vssLoggingContext: D_VssLoggingContext;};
type R_WatchEndpointMusicConfig={watchEndpointMusicConfig: D_WatchEndpointMusicConfig;};
type R_WatchNextEndScreen={watchNextEndScreenRenderer: D_WatchNextEndScreen;};
type R_WatchNextTabbedResults={watchNextTabbedResultsRenderer: D_WatchNextTabbedResults;};
type R_WebSearchboxConfig={webSearchboxConfig: D_WebSearchboxConfig;};
//#endregion
//#region {pageType:string}
type NavFinishDetail_Watch={
	pageType: "watch";
	endpoint: E_Watch;
	response: G_RS_WatchPage;
	fromHistory: boolean;
	navigationDoneMs: number;
};
type G_RS_Page_Browse=RS_VE6827_BrowsePage|RS_VE96368_BrowsePage|RS_Page_Browse;
type RS_VE6827_BrowsePage={
	rootVe: 6827;
	url: "/feed/library";
	endpoint: E_VE6827;
	page: "browse";
	response: {
		responseContext: RC_ResponseContext;
		contents: R_TwoColumnBrowseResults;
		header: R_FeedTabbedHeader;
		trackingParams: string;
		topbar: R_DesktopTopbar;
	};
	expirationTime: number;
}|{
	page: "browse";
	endpoint: E_VE6827;
	response: {
		responseContext: RC_ResponseContext;
		contents: R_TwoColumnBrowseResults;
		header: R_C4TabbedHeader;
		trackingParams: string;
		topbar: R_DesktopTopbar;
	};
	url: `/feed/trending?bp=${string}`;
	expirationTime: number;
}|{
	page: "browse";
	endpoint: E_VE6827;
	response: {
		responseContext: RC_ResponseContext;
		contents: R_TwoColumnBrowseResults;
		header: R_FeedTabbedHeader;
		trackingParams: string;
		topbar: R_DesktopTopbar;
	};
	url: "/feed/library";
	expirationTime: number;
}|{
	page: "browse";
	endpoint: E_VE6827;
	response: {
		responseContext: RC_ResponseContext;
		contents: R_TwoColumnBrowseResults;
		trackingParams: string;
		topbar: R_DesktopTopbar;
	};
	url: "/feed/history";
	expirationTime: number;
};

type RS_VE96368_BrowsePage={
	rootVe: 96368;
	url: "/feed/subscriptions";
	endpoint: E_VE96368;
	page: "browse";
	response: {
		responseContext: RC_ResponseContext;
		contents: R_TwoColumnBrowseResults;
		header: R_FeedTabbedHeader;
		trackingParams: string;
		topbar: R_DesktopTopbar;
		observedStateTags: {
			stateTag: 3;
			instruction: "STATE_TAG_BROWSE_INSTRUCTION_MARK_AS_DIRTY";
		}[];
		cacheMetadata: D_IsCacheHit;
	};
	expirationTime: number;
}|{
	page: "browse";
	endpoint: E_VE96368;
	response: {
		responseContext: RC_ResponseContext;
		contents: R_TwoColumnBrowseResults;
		header: R_FeedTabbedHeader;
		trackingParams: string;
		topbar: R_DesktopTopbar;
		observedStateTags: {
			stateTag: 3;
			instruction: "STATE_TAG_BROWSE_INSTRUCTION_MARK_AS_DIRTY";
		}[];
	};
	url: "/feed/subscriptions";
	expirationTime: number;
};
type RS_VE3854_BrowsePage={
	page: "browse";
	endpoint: E_VE3854;
	response: RS_Browse;
	url: "/";
	previousCsn: string;
	expirationTime: number;
}|{
	rootVe: 3854;
	url: "/";
	endpoint: E_VE3854;
	page: "browse";
	response: RS_Browse;
	expirationTime: number;
}|{
	page: "browse";
	endpoint: E_VE3854;
	response: RS_Browse;
	url: "/";
	expirationTime?: number;
}|{
	page: "browse";
	endpoint: E_VE3854;
	response: RS_Browse;
	url: "/";
	expirationTime: number;
	graftedVes: D_GraftedVeItem[];
	csn: string;
};
type G_ResponseBrowse=
	|RS_VE3854_BrowsePage
	|RS_VE6827_BrowsePage
	|RS_VE96368_BrowsePage
	;
;
type G_RS_ByPageType=G_RS_WatchPage|RS_ChannelPage|G_RS_Page_Playlist|G_RS_SettingsPage|RS_SearchPage|RS_Page_Browse|G_RS_ShortsPage|RS_VE6827_BrowsePage|RS_VE96368_BrowsePage;
//#endregion
//#region RA_
type RA_Notification={notificationActionRenderer: AD_Notification;};
type RA_NotificationMulti={notificationMultiActionRenderer: AD_NotificationMulti;};
type RA_ReelDismissal={reelDismissalActionRenderer: AD_ReelDismissal;};
//#endregion
//#region RC_
//#region Continuation Renderer
type RC_LiveChat={liveChatContinuation: DC_LiveChat;};
type RC_MusicShelf={musicShelfContinuation: DC_MusicShelf;};
type RC_PlaylistPanel={playlistPanelContinuation: DC_PlaylistPanel;};
type RC_SectionList={sectionListContinuation: GD_RC_SectionList;};
//#endregion
//#region RC
type RC_ConsistencyTokenJar={encryptedTokenJarContents: string; expirationSeconds: `${D_TokenJarDefaultExpirationSeconds}`;};
type RC_CsiServiceC={key: "c"; value: RC_ECatcherClientName['value'];};
type RC_CsiServiceCVer={key: "cver"; value: string;};
type RC_CsiVarMap={
	yt_li: "1";
	yt_ad: "1";
	yt_fn: D_BrowseEndpointPages;
	[x: T_RidFormat<string>]: `0x${string}`;
};
type RC_CsiVarTypes={cver: Extract<DRC_CsiVarKV,{key: "cver";}>['value'];};
type RC_Csi_SPs={
	service: "CSI",
	params: DRC_CsiVarKV[];
};
type RC_ECatcherClientName={key: "client.name"; value: "WEB"|"WEB_REMIX";};
type RC_ECatcherClientVersion={key: "client.version"; value: RC_SomeVer<RC_CsiVarTypes['cver']>;};
type RC_ECatcherServiceType={["client.fexp"]: `${number}`|`${number},${number}`|`${number},${number},${string}`;};
type RC_ECatcher_ParamItem=RC_ECatcherClientName|RC_ECatcherClientVersion;
type RC_ECatcher_SPs={service: "ECATCHER"; params: (RC_ECatcher_ParamItem|ToKeyValue<RC_ECatcherServiceType>)[];};
type RC_GFeedback_SPs={service: "GFEEDBACK"; params: SP_GFeedbackServiceParams[];};
type RC_GoogleHelp_SPs={service: "GOOGLE_HELP"; params: ToKeyValue<SP_GoogleHelpServiceObj>[];};
type RC_MainAppWebResponseContext={
	datasyncId: `${number}||${number}`;
	loggedOut: boolean;
	trackingParam?: string;
};
type RC_ResponseContext={
	mainAppWebResponseContext?: RC_MainAppWebResponseContext;
	serviceTrackingParams?: GRC_ServiceTrackingParams[];
	webResponseContextExtensionData?: RC_WR_ContextExtension;
	consistencyTokenJar?: RC_ConsistencyTokenJar;
	maxAgeSeconds?: number;
	stateTags?: RCA_RelevantStateTags;
};
type RC_ResponseContext_1={
	mainAppWebResponseContext: RC_MainAppWebResponseContext;
	serviceTrackingParams: GRC_ServiceTrackingParams[];
	webResponseContextExtensionData: RC_WR_ContextExtension;
};
type RC_SomeVer<T extends string>=T extends `${infer V0}.${infer V1}.${string}.${string}`? `${V0}.${V1}`:T;
type ToKeyValue<T>={[U in keyof T]: {key: U; value: T[U];};}[keyof T];
type RC_WR_ContextExtension={
	hasDecorated?: boolean;
	ytConfigData?: D_YtConfig;
	webPrefetchData?: D_WebPrefetch;
};
//#endregion
//#endregion
