type RS_Browse={
	responseContext: RC$ResponseContext;
	contents?: G$BrowseContents;
	continuationContents?: C_SectionList;
	header?: G$BrowseHeader;
	alerts?: R_AlertWithButton[];
	metadata?: G_BrowseMetadata;
	trackingParams: string;
	topbar?: R_DesktopTopbar;
	microformat?: R_MicroformatData;
	frameworkUpdates?: R_EntityBatchUpdate;
	// ?
	maxAgeStoreSeconds?: number;
	background?: R_MusicThumbnail;
	// ?
	onResponseReceivedActions?: A_ResponseReceived[];
	sidebar?: G_BrowseSidebar;
	observedStateTags?: B$StateTag[];
	cacheMetadata?: CacheMetadata;
};
