type RS_Player={
	responseContext: RC_ResponseContext;
	playabilityStatus: D_PlayabilityStatus;
	streamingData?: DD_Streaming;
	heartbeatParams?: D_HeartbeatParams;
	playerAds?: R_DesktopWatchAds[];
	playbackTracking?: D_PlaybackTracking;
	captions?: R_PlayerCaptionsTracklist;
	videoDetails?: D_VideoDetails;
	playerConfig?: D_PlayerConfig;
	storyboards?: R_PlayerStoryboardSpec|R_PlayerLiveStoryboardSpec;
	microformat?: R_PlayerMicroformat;
	cards?: R_CardCollection;
	trackingParams: string;
	attestation?: R_PlayerAttestation;
	videoQualityPromoSupportedRenderers?: R_VideoQualityPromo;
	adPlacements?: Maybe<R_AdPlacement>[];
	frameworkUpdates: A_FrameworkUpdates;
	endscreen?: R_Endscreen;
	paidContentOverlay?: {};
	annotations?: R_PlayerAnnotationsExpanded[];
}