import {Accessibility} from "../a/Accessibility.js";
import {MenuRendererH} from "../m/MenuRendererH.js";
import {MetadataBadgeRenderers} from "../m/MetadataBadgeRenderers.js";
import {NavigationEndpoint} from "../n/NavigationEndpoint.js";
import {SimpleText} from "../s/SimpleText.js";
import {TextRuns} from "../t/TextRuns.js";
import {ThumbnailH} from "../t/ThumbnailH.js";
import {ThumbnailOverlay} from "../t/ThumbnailOverlay.js";
import {ThumbnailsH} from "../t/ThumbnailsH.js";
import {TrackingParams} from "../t/TrackingParams.js";
import {RichThumbnail} from "../_rich/RichThumbnail.js";

export interface CompactVideoRenderer extends TrackingParams {
	accessibility: Accessibility;
	badges?: MetadataBadgeRenderers[];
	channelThumbnail: ThumbnailsH;
	lengthText: SimpleText;
	longBylineText: TextRuns;
	menu: MenuRendererH;
	navigationEndpoint: NavigationEndpoint;
	publishedTimeText: SimpleText;
	richThumbnail?: RichThumbnail;
	shortBylineText: TextRuns;
	shortViewCountText: SimpleText;
	thumbnail: ThumbnailH;
	thumbnailOverlays: ThumbnailOverlay[];
	title: SimpleText;
	ownerBadges?: MetadataBadgeRenderers[];
	videoId: string;
	viewCountText: SimpleText;
};
