type E_PerformCommentAction={performCommentActionEndpoint: {};};
type D_Button_DefServiceEP=C_CommandExecutor|E_PerformCommentAction;
type D_ToggleButton={
	accessibility: D_Label;
	accessibilityData: D_Accessibility;
	defaultIcon: T_Icon<"DISLIKE"|"LIKE"|"LOOP"|"SHUFFLE">;
	defaultServiceEndpoint: E_SignalService_SendPost|E_PerformCommentAction|C_RepeatChapter|C_CommandExecutor;
	defaultText: G_Text;
	defaultTooltip: string;
	isDisabled: false;
	isToggled: boolean;
	size: T_SizeType<"SIZE_DEFAULT">;
	style: T_StyleType<"STYLE_TEXT"|"STYLE_GREY_TEXT"|"STYLE_DEFAULT_ACTIVE">;
	targetId: "watch-dislike"|"watch-like";
	toggleButtonSupportedData: R_ToggleButtonIdData;
	toggledAccessibilityData: D_Accessibility;
	toggledServiceEndpoint: E_SignalService_SendPost|E_PerformCommentAction|E_Like|C_CommandExecutor;
	toggledStyle: T_StyleType<"STYLE_DEFAULT_ACTIVE"|"STYLE_BLUE_TEXT">;
	toggledText: G_Text;
	toggledTooltip: string;
	trackingParams: string;
};
