type D_UrlFormat=
	|"/"
	|"/channel_switcher"
	|"/upload"
	|"android-app://com.google.android.youtube/http/youtube.com/premium"
	|`/@${string}`
	|`/@${string}${""|`/${ChannelSubUrlFormat}`}`
	|D_ApiPathFormat_1
	|`/account${""|`_${G_AccountPageSettingsSections}`}`
	|`/api/stats/ads?${string}`
	|`/channel/UC${string}`
	|`/feed/${D_BrowseEndpointPages}`
	|`/feed/trending?${string}`
	|`/gaming`
	|`/playlist?${string}`
	|`/premium`
	|`/reporthistory`
	|`/results?${string}`
	|`/shorts/${string}`
	|`/watch?${string}`
	|`http://www.youtube.com/watch?${string}`
	|`https://support.google.com/youtube/answer/${number}`
	|`https://www.youtube.com/watch?${string}`
	|NonNullable<D_Channel_MD["channelConversionUrl"]>
	|D_Youtube_Streaming_ProbeUrl
	|D_ExternalUrlFormat
	|GU_VE6827_Url
	|YTExternalUrl
	|NonNullable<D_AdaptiveFormatItem["url"]>
	|NonNullable<D_FormatItem["url"]>
	|TP_ParseUrlSearchParams<D_FormatItem_signatureCipher>["url"]
	|D_MicroformatEmbed["flashSecureUrl"]
	|D_MicroformatEmbed["flashUrl"]
	|D_MicroformatEmbed["iframeUrl"]
	|`/embed/${string}`
	|`/v/${string}?version=3&autohide=1`
	|D_PlayerMicroformat["ownerProfileUrl"]
	|`https://www.youtube.com/pagead/adview?${string}`
	|DE_VE83769_Url_1["url"]
	;
;
