type D_UrlFormat=
	|"/channel_switcher"
	|"/upload"
	|"android-app://com.google.android.youtube/http/youtube.com/premium"
	|`/@${string}`
	|`/@${string}${""|`/${ChannelSubUrlFormat}`}`
	|`/@${string}${ChannelSubUrlFormat}`
	|`/account${""|`_${G_AccountPageSettingsSections}`}`
	|`/account${""|`_${G_AccountPageSettingsSections}`}`
	|`/api/stats/ads?${string}`
	|`/channel/UC${string}`
	|`/embed/${string}`
	|`/feed/${D_BrowseEndpointPages}`
	|`/feed/${D_BrowseEndpointPages}`
	|`/feed/trending?${string}`
	|`/feed/trending?bp=${string}`
	|`/gaming`
	|`/playlist?${D_PlaylistUrlParams}`
	|`/playlist?${string}`
	|`/premium`
	|`/reporthistory`
	|`/results?${string}`
	|`/results?search_query=${string}`
	|`/shorts/${string}`
	|`/shorts/${string}`
	|`/v/${string}?version=3&autohide=1`
	|`/watch?${D_WatchUrlStr}`
	|`/watch?${string}`
	|S_YtUrlHttp_Watch
	|`https://www.youtube.com/pagead/adview?${string}`
	|`https://www.youtube.com/watch?${string}`
	|D_ApiPathFormat_1
	|D_ExternalUrlFormat
	|D_MicroformatEmbed["flashSecureUrl"]
	|D_MicroformatEmbed["flashUrl"]
	|D_MicroformatEmbed["iframeUrl"]
	|D_PlayerMicroformat["ownerProfileUrl"]
	|D_Youtube_Streaming_ProbeUrl
	|DE_VE83769_Url_1["url"]
	|GM_VE3854["url"]
	|GU_VE3611_Url
	|GU_VE6827_Url
	|NonNullable<D_AdaptiveFormatItem["url"]>
	|NonNullable<D_Channel_MD["channelConversionUrl"]>
	|NonNullable<D_FormatItem["url"]>
	|TP_ParseUrlSearchParams<D_FormatItem_signatureCipher>["url"]
	|YTExternalUrl
	;
;
