type G_BoxedIdObj=
	|DSS_ABJ_Browse_MP
	|DSS_Browse_SP
	|DSS_Browse_SP
	|DSS_Browse_VL_LL
	|DSS_Browse_VL_PL
	|DSS_Browse_VL_UC
	|DSS_Browse_VL_WL
	|DSS_User_Id
	|DST_Browse_FE
	|DST_Channel_UC
	|DST_GuideEntry_LL
	|DST_GuideEntry_PL
	|DST_GuideEntry_UC
	|DST_GuideEntry_VL_LL
	|DST_GuideEntry_WL
	|DST_HashtagId
	|DST_KeySection
	|DST_LoadId
	|DST_Playlist_LL
	|DST_Playlist_PL
	|DST_Playlist_RD
	|DST_Playlist_RD_MM
	|DST_Playlist_WL
	|DST_Playlist_WL
	|DST_PlayNext
	|DST_SaveId
	|DST_UpdateId
	|DST_Video_Id
	|DST_Video_Id
	|DST_VideoTime
	|GST_DSS
	;
;