type G_BoxedIdObj=
	|DST_Channel_UC
	|DST_GuideEntry_LL
	|DST_GuideEntry_PL
	|DST_GuideEntry_UC
	|DST_GuideEntry_WL
	|DST_KeySection
	|DST_Playlist_LL
	|DST_Playlist_PL
	|DST_Playlist_RD
	|DST_Playlist_RD_MM
	|DST_Playlist_WL
	|DST_Playlist_WL
	|DST_Video_Id
	|DST_Video_Id
	|GST_Simple
	|GST_Browse_Id
	;
;