type I_KnownLoaded=
	|DST_Channel_UC
	|DST_Key_StartRadio
	|DST_Playlist_RD
	|DST_Playlist_RD_MM
	|DST_Playlist_WL
	|DST_Browse_FE
	|DST_Browse_MP
	|DST_Browse_SP
	|DST_Browse_VL_WL
	|DST_Browse_VL_LL
	|DST_Browse_VL_PL
	|DST_GuideEntry_LL
	|DST_GuideEntry_WL
	|DST_GuideEntry_PL
	|DST_Playlist_LL
	|DST_Playlist_PL
	|DST_HashtagId
	|DST_PlayNext
	|DST_User_Id
	|DST_Video_Id
	|DST_VideoTime
	|DST_LoadId
	|DST_SaveId
	|DST_UpdateId
	;
;