type I_KnownLoaded=
	|D_Boxed_Channel_UC
	|D_BX_KeySection
	|D_BX_Playlist_RD
	|D_BX_Playlist_RD_MM
	|D_BX_Playlist_WL
	|D_Boxed_Browse_FE
	|D_Boxed_Browse_MP
	|D_Boxed_Browse_SP
	|D_Boxed_Browse_VL_WL
	|D_Boxed_Browse_VL_LL
	|D_Boxed_Browse_VL_PL
	|D_Boxed_GuideEntry_LL
	|D_Boxed_GuideEntry_WL
	|D_Boxed_GuideEntry_PL
	|D_Boxed_Playlist_LL
	|D_Boxed_Playlist_PL
	|D_BoxedHashtagId
	|D_BoxedPlayNext
	|D_BoxedUserId
	|D_Boxed_Video_Id
	|D_BoxedVideoTime
	|D_BoxedLoadId
	|D_BoxedSaveId
	|D_BoxedUpdateId
	;
;