type D_Comment={
	authorText: G_Text;
	authorThumbnail: R_Thumbnail;
	authorEndpoint: {};
	contentText: G_Text;
	publishedTimeText: G_Text;
	isLiked: boolean;
	actionMenu: R_Menu;
	commentId: string;
	actionButtons: R_CommentActionButtons;
	authorIsChannelOwner: boolean;
	currentUserReplyThumbnail: R_Thumbnail;
	voteStatus: "INDIFFERENT";
	trackingParams: string;
	voteCount: G_Text;
	expandButton: R_Button;
	collapseButton: R_Button;
	loggingDirectives: D_LoggingDirectives;
};