type D_CompactPlaylist={
	playlistId: `PL${string}`;
	thumbnail: R_Thumbnail;
	title: G_Text;
	shortBylineText: G_Text;
	videoCountText: G_Text;
	navigationEndpoint: E_Watch;
	publishedTimeText?: G_Text;
	videoCountShortText: G_Text;
	trackingParams: string;
	sidebarThumbnails: R_Thumbnail[];
	thumbnailText: G_Text;
	ownerBadges?: RMD_Badge[];
	menu: R_Menu;
	shareUrl: `https://www.youtube.com/watch?v=${string}&playnext=1&list=RDCMUC${string}`;
	thumbnailRenderer: R_PlaylistVideoThumbnail;
	longBylineText: G_Text;
	thumbnailOverlays: G_ThumbnailOverlayItem[];
};