type D_PlayerMicroformat={
	thumbnail: D_Thumbnail;
	embed: D_MicroformatEmbed;
	title: G_Text;
	description?: G_Text;
	lengthSeconds: `${number}`;
	ownerProfileUrl: `http://www.youtube.com/channel/UC${string}`;
	externalChannelId: ChannelId;
	isFamilySafe: boolean;
	availableCountries: string[];
	isUnlisted: boolean;
	hasYpcMetadata: boolean;
	viewCount: `${number}`;
	category: D_VideoCategory;
	publishDate: string;
	ownerChannelName: string;
	liveBroadcastDetails?: D_LiveBroadcastDetails;
	uploadDate: string;
};