type D_VideoDetails={
	videoId: string;
	title: string;
	lengthSeconds: `${number}`;
	keywords?: string[];
	channelId: `UC${string}`;
	isOwnerViewing: false;
	shortDescription: string;
	isCrawlable: true;
	thumbnail: D_Thumbnail;
	allowRatings: boolean;
	viewCount?: `${number}`;
	author: string;
	isLowLatencyLiveStream?: false;
	isPrivate: false;
	isUnpluggedCorpus: false;
	latencyClass?: "MDE_STREAM_OPTIMIZATIONS_RENDERER_LATENCY_NORMAL";
	isLiveContent: false;
};
