import {AsyncFunctionBox} from "../box/AsyncFunctionBox.ts";
import {Box} from "../box/Box.ts";
import {CastOperandTarget} from "./CastOperandTarget.ts";
import {VMBlockTraceOperand} from "./VMBlockTraceOperand.ts";

export type InstructionMap={
	append: ["append"];
	breakpoint: ["breakpoint"];
	call: ["call",number];
	cast: ["cast",CastOperandTarget];
	construct: ["construct",number];
	drop: ["drop"];
	dup: ["dup"];
	get: ["get"];
	halt: ["halt"];
	je: ["je",number];
	jmp: ["jmp",number];
	modify_operand: ["modify_operand",number,number];
	nop: ["nop"];
	peek: ["peek",number];
	push_window_object: ["push_window_object"];
	push: ["push",Box];
	return: ["return"];
	vm_block_trace: ["vm_block_trace",VMBlockTraceOperand];
	vm_call: ["vm_call",number];
	vm_push_args: ["vm_push_args"];
	vm_push_ip: ["vm_push_ip"];
	vm_push_self: ["vm_push_self"];
	vm_return: ["vm_return"];
	dom_exec: ["dom_exec",number];
	dom_peek: ["dom_peek",number,number];
	dom_new: ["dom_new",typeof CSSStyleSheet,[],AsyncFunctionBox,[string]];
	dom_get: ["dom_get",string];
	dom_create_element: ["dom_create_element","div",string,string];
	dom_create_element_with_props: ["dom_create_element_with_props","div",string,{id: string;}];
};
