import {EngagementPanelSectionShortsComments} from "./EngagementPanelSectionShortsComments";
import {EngagementPanelStructuredDescription} from "./EngagementPanelStructuredDescription";

export type EngagementPanelSectionListRendererOpt=EngagementPanelSectionShortsComments|EngagementPanelStructuredDescription;
