import {SymbolRef} from "./types/SymbolRef";
import {AutoBuy} from "./types/AutoBuy";
import {ProxyHandlers} from "./types/ProxyHandlers";
import {ScriptStateHost} from "./types/ScriptStateHost";
import {find_all_scripts_using_string_apis} from "./types/find_all_scripts_using_string_apis_helper";
import {UniqueIdGenerator} from "./types/UniqueIdGenerator";
import {TimerApi} from "types/TimerApi";
import {SimpleStackVMParser} from "./SimpleStackVMParser";
import {calc_ratio} from "./calc_ratio";
import {reload_if_def} from "./reload_if_def";
import {main} from "./main";

export const TIMER_SINGLE = 1;
export const TIMER_REPEATING = 2;
export const TIMER_TAG_COUNT = 3;
export const AUDIO_ELEMENT_VOLUME = 0.58;
export const cint_arr: string[] = [];
export const WorkerAsyncMessage = 1;
export const TimeoutFireS = 101;
export const TimeoutFireR = 102;
export const WorkerUpdateMessageHandler = 201;
export const TimeoutMessageR = 202;
export const TimeoutSetS = 203;
export const TimeoutSetR = 204;
export const TimeoutClearS = 205;
export const TimeoutClearR = 206;
export const TimeoutClearA = 207;
export const WorkerDestroyMessage = 300;
export const WorkerUpdateMessageHandlerReply = 301;
export const WorkerReadyReply = 302;
export const ReplySetSingle = 303;
export const ReplySetRepeating = 304;
export const ReplyClearSingle = 305;
export const ReplyClearRepeating = 306;
export const ReplyClearAny = 307;
export const ReplyMessage1 = 401;
export const ReplyMessage2 = 402;
export const ReplyFromWorker = 500;
export const ReplyToWorker = 600;
export const TimeoutSingleReply = 700;
export const TimeoutRepeatingReply = 701;
export const TimeoutSetTypes = 1001;
export const TimeoutSetStringS = "setTimeout";
export const TimeoutSetStringR = "setInterval";
export const TimeoutClearStringS = "clearTimeout";
export const TimeoutClearStringR = "clearInterval";
let g_timer_api = new TimerApi;
export let message_types = g_timer_api.msg_types;
export var is_in_ignored_from_src_fn = {flag:false};
export var is_in_userscript_fn = {flag:false};
export var is_in_userscript = {flag:true};
export let cur_event_fns: (CallableFunction | NewableFunction)[] = [];
export const [weak_scripts, register_obj_with_registry] = find_all_scripts_using_string_apis();
export let seen_elements = new WeakSet;
export const local_logging_level = 3;
export const LOG_LEVEL_ERROR = 1;
export const LOG_LEVEL_WARN = 2;
export const LOG_LEVEL_INFO = 3;
export const LOG_LEVEL_VERBOSE = 4;
export const LOG_LEVEL_TRACE = 5;
SimpleStackVMParser.match_regex = /(.+?)(;|$)/gm;
console.assert(calc_ratio([0, 0]) === 0, "calc ratio of array full of zeros does not divide by zero");
export const debug_id_gen = new UniqueIdGenerator;
export const debug_id_syms: WeakRef<SymbolRef>[] = [];
export const auto_buy_obj = new AutoBuy;
export default function entry_point() {
	main();
	ScriptStateHost.event_target.dispatchEvent({type: 'userscript', state: 'done'});
}
