import {ACTION_ADD_VIDEO} from "./ACTION_ADD_VIDEO";
import {ACTION_REMOVE_VIDEO_BY_VIDEO_ID} from "./ACTION_REMOVE_VIDEO_BY_VIDEO_ID";

export type _ACTIONS=ACTION_ADD_VIDEO|ACTION_REMOVE_VIDEO_BY_VIDEO_ID;
