type G_BoxedInner=[1,any];
	;
;
type U1=Ret_w_dst[2];
type GUnBoxLvl1<T extends TShape_Successor<any>>=[T['z'][0],T];
type GUnBoxLvl2<T extends TShape_SuccessorX2<any>>=[T['z'][0]['z'][0],...GUnBoxLvl1<T>];
type GUnBoxLvl3<T extends TShape_SuccessorX3<any>>=[TZ_SuccessorX3<T>,...GUnBoxLvl2<T>];
type GUnBoxLvl4<T extends TShape_SuccessorX3<any>>=[TZ_SuccessorX4<T>,...GUnBoxLvl3<T>];
type X3_data=TZ_SuccessorX3<Extract<G_BoxedDatabaseData,TShape_SuccessorX3<{}>>>;
type X4_data=TZ_Successor<Extract<X3_data,TShape_Successor<any>>>;
type X4_box=Extract<X4_data,TShape_Successor<any>>;
type X5_data=X4_box["z"][0];
