type G_UrlInfo=
	|DIG_BrowseId
	|DI_ChannelUrl
	|DI_HashtagId
	|DI_VideoTime
	|DI_Playlist_LL
	|DI_Playlist_PL
	|DI_Playlist_RD
	|DI_Playlist_UU
	|DI_Playlist_WL
	|DI_Playlist_RD
	|DI_Playlist_RD_CM_UC
	|DI_Playlist_RD_GM_EM
	|DI_Playlist_RD_MM
	|DI_Playlist_UU
	|DI_PlayNext
	|DI_VideoId
	|DI_UserId
	;
;
