type G_UrlInfo=
	|DIG_BrowseIdInfo
	|D_ChannelUrlInfo
	|D_InfoHashtagId
	|D_InfoVideoTime
	|D_PlaylistInfo_LL
	|D_PlaylistInfo_LL
	|D_PlaylistInfo_PL
	|D_PlaylistInfo_RD
	|D_PlaylistInfo_UU
	|D_PlaylistInfo_WL
	|D_PlaylistInfo_RD
	|D_PlaylistInfo_RD_CM_UC
	|D_PlaylistInfo_RD_GM_EM
	|D_PlaylistInfo_RD_MM
	|D_PlaylistInfo_UU
	|D_PlayNextUrlInfo
	|DI_VideoId
	|DI_UserId
	;
;
