type D_CF_y_str=[
	"AD_HideEnclosing",
	"B_HrefUrl",
	"CD_Reload",
	"D_CanShare",
	"D_EditableDetails",
	"D_PlaylistByline",
	"D_RelatedChipCloud",
	"D_ThumbnailOverlayBottomPanel",
	"D_ThumbnailOverlayNowPlaying",
	"D_ThumbnailOverlayResumePlayback",
	"D_YpcGetCart",
	"DE_CreateBackstagePost",
	"DE_PlaylistEditor",
	"T_Item",
][number];
