type YtTargetIdType=[
	G_AppendContinuationItems['targetId'],
	TA_Continuation<"browse-feedFEwhat_to_watch",R_BrowseFeed>['targetId'],
	"comments-section",
	D_EngagementPanelSectionTargetId,
	D_SearchFeedSectionList['targetId'],
	D_ScrollToEngagementPanel['targetId'],
	RS_Search['targetId'],
	D_TranscriptSearchPanel['targetId'],
	D_UpdateEngagementPanel['targetId'],
	A_WatchNextContinuation['targetId'],
	ChipCloudChip_tid['targetId'],
	`shopping_panel_for_entry_point_${"5"|"22"}`,
	"clip-info-button",
	"sponsorships-button",
	D_Menu$targetId,
	GenericEngagementPanelSectionItem['targetId'],
][number];
