type AdaptiveFormatItem={
	itag: number;
	url: string;
	mimeType: string;
	bitrate: number;
	width: number;
	height: number;
	initRange: YtRange;
	indexRange: YtRange;
	lastModified: string;
	contentLength: string;
	quality: FormatQuality;
	fps: FormatFps;
	qualityLabel: "2160p50";
	projectionType: "RECTANGULAR";
	averageBitrate: number;
	colorInfo: FormatColorInfo;
	approxDurationMs: `${number}`;
};