type CommentData={
	authorText: D$TextWithRuns;
	authorThumbnail: D$Thumbnail;
	authorEndpoint: {};
	contentText: D$TextWithRuns;
	publishedTimeText: D$TextWithRuns;
	isLiked: boolean;
	actionMenu: R$MenuRenderer;
	commentId: string;
	actionButtons: CommentActionButtonsRenderer;
	authorIsChannelOwner: boolean;
	currentUserReplyThumbnail: D$Thumbnail;
	voteStatus: "INDIFFERENT";
	trackingParams: string;
	voteCount: D$TextWithRuns;
	expandButton: R$ButtonRenderer;
	collapseButton: R$ButtonRenderer;
	loggingDirectives: A$LoggingDirectives;
};