type CommentData={
	authorText: TextWithRuns;
	authorThumbnail: Thumbnail;
	authorEndpoint: {};
	contentText: TextWithRuns;
	publishedTimeText: TextWithRuns;
	isLiked: boolean;
	actionMenu: MenuRenderer;
	commentId: string;
	actionButtons: CommentActionButtonsRenderer;
	authorIsChannelOwner: boolean;
	currentUserReplyThumbnail: Thumbnail;
	voteStatus: "INDIFFERENT";
	trackingParams: string;
	voteCount: TextWithRuns;
	expandButton: ButtonRenderer;
	collapseButton: ButtonRenderer;
	loggingDirectives: LoggingDirectives;
};