type D$Comment={
	authorText: D$TextWithRuns;
	authorThumbnail: D$Thumbnail;
	authorEndpoint: {};
	contentText: D$TextWithRuns;
	publishedTimeText: D$TextWithRuns;
	isLiked: boolean;
	actionMenu: R$Menu;
	commentId: string;
	actionButtons: R$CommentActionButtons;
	authorIsChannelOwner: boolean;
	currentUserReplyThumbnail: D$Thumbnail;
	voteStatus: "INDIFFERENT";
	trackingParams: string;
	voteCount: D$TextWithRuns;
	expandButton: R$Button;
	collapseButton: R$Button;
	loggingDirectives: A$LoggingDirectives;
};