type D$MultiPageMenu$style={
	style: "MULTI_PAGE_MENU_STYLE_TYPE_SWITCHER";
}|{
	style: "MULTI_PAGE_MENU_STYLE_TYPE_CREATION";
}|{
	style: "MULTI_PAGE_MENU_STYLE_TYPE_NOTIFICATIONS";
}|{
	style: "MULTI_PAGE_MENU_STYLE_TYPE_ACCOUNT";
};