type endpoint_data_handler_names={
	continuationCommand: "ContinuationCommand";
	commandMetadata: "CommandMetadata";
	watchEndpoint: "WatchEndpointData_1";
	browseEndpoint: "BrowseEndpointData";
	searchEndpoint: "SearchEndpointData";
	setSettingEndpoint: "SetSettingEndpointData";
	signalServiceEndpoint: "SignalServiceEndpointData";
	urlEndpoint: "UrlEndpointData";
	signalNavigationEndpoint: "SignalNavigationEndpointData";
	signOutEndpoint: "SignOutEndpointData";
	getAccountsListInnertubeEndpoint: "GetAccountsListInnertubeEndpointData";
	loadMarkersCommand: "LoadMarkersCommand";
	changeKeyedMarkersVisibilityCommand: "ChangeKeyedMarkersVisibilityCommand";
	createCommentEndpoint: "CreateCommentEndpointData";
	confirmDialogEndpoint: "ConfirmDialogEndpointData";
	reloadContinuationItemsCommand: "ReloadContinuationItemsCommandData";
	appendContinuationItemsAction: "AppendContinuationItemsAction";
	liveChatItemContextMenuEndpoint: "LiveChatItemContextMenuEndpointData";
	openPopupAction: "OpenPopupActionData",
};