type EngagementPanelSectionList=
	|GenericEngagementPanelSectionItem
	|VE_t2_EngagementPanelSectionItem
	|VE_t1_EngagementPanelSectionItem
	|VE124975_EngagementPanelSectionItem
	|VE_t3_EngagementPanelSectionItem
	|VE139722_EngagementPanelSectionItem
	;
;