type ItemSectionItem=[
	CommentsEntryPointHeaderRenderer,
	CompactPlaylistRenderer,
	CompactRadioRenderer,
	CompactVideoRenderer,
	ConnectedAppRenderer,
	ContinuationItemRenderer,
	PageIntroductionRenderer,
	PlaylistVideoListRenderer,
	ReelShelfRenderer,
	SearchPyvRenderer,
	SettingsOptionRenderer,
	ShelfRenderer,
	VideoRenderer,
][number];