type P$known$param=[
	"click.trackingParams.f19.f2"|"report.params.f25"|"report.params.f26"|"report.params.f28"|
	"report.params.f28.f1"|"watch.params.f56"|"report.params.f28.f1.f1"|"report.params.f28.f1.f1.f1"|
	"report.params.f28.f1.f1.f1.f1"|"report.params.f28.f1.f1.f1.f1.f4"|
	"report.params.f28.f1.f3",
	PathRoot_Gen.CX2<PathRoot_Gen.X$CU>,
	PathRoot_Gen.CX2<PathRoot_Gen.X$CU2>,
	"createBackstagePost.param.f2"|"createBackstagePost.param.f1",
	"entity_key.f4"|"entity_key.f5"|"entity_key.f2",
	"subscribe.params.f2.f1"|"subscribe.params.f2"|"subscribe.params.f3"|"subscribe.params.f4",
	P$tracking$param<"click"|"tracking">,
	P$browse$param,
	P$create_playlist$param,
	P$get_transcript$param,
	P$record_notification_interactions$param,
	P$reel$player_param,
	P$report$param,
	P$watch$param,
	P$watch$player_param,
][number];