type P$unknown$param=[
	"browse.params",
	"createBackstagePost.param",
	"entity_key",
	"get_transcript.params",
	"like.likeParams",
	"like.remove_like_params",
	"next.queue_context_params",
	"playlist_edit.params",
	"reel.sequence_params",
	"report.params",
	"subscribe.params",
	"tracking.parentTrackingParams",
	"watch_page_url.pp",
	"watch_playlist.params",
	"ypc_get_offers.params",
	Extract<P$category$param,`reel.${string}`>,
][number];