type ParamsSection=
	string
	|"Next"
	|"SubscribeEndpoint"
	|"AE_Browse"
	|"CommonConfigData"
	|"CreatePlaylist"
	|"GeneratedWCM"
	|"Generic_WatchPageResponse"
	|"GetReportForm"
	|"GetTranscript"
	|"HrefUrl"
	|"PlaylistContent"
	|"PlaylistEdit"
	|"RecordNotificationInteractions"
	|"ReelWatch"
	|"UnknownWebCommandMetadata"
	|"WatchEndpoint"
	|"WatchPageResponse"
	|"WatchPlaylist"
	|"YpcGetOffers"
	;
;