type PlaylistContent={
	title: string;
	contents: PlaylistPanelVideoRenderer[];
	currentIndex: number;
	playlistId: PlaylistId;
	ownerName: SimpleText;
	isInfinite: boolean;
	playlistShareUrl: `http://www.youtube.com/watch?v=${string}&list=${string}`;
	shortBylineText: TextT;
	longBylineText: TextT;
	trackingParams: string;
	titleText: SimpleText;
	isEditable: true;
	menu: MenuRenderer;
	localCurrentIndex: 25;
	playlistButtons: MenuRenderer;
	isCourse: false;
	nextVideoLabel: SimpleText;
};