type ResponseReceivedEndpointItem=SignalServiceEndpoint|ChangeKeyedMarkersVisibilityCommand|LoadMarkersCommand;
type ChangeKeyedMarkersVisibilityCommand={
	clickTrackingParams: string;
	changeKeyedMarkersVisibilityCommand: ChangeKeyedMarkersVisibilityCommandData;
};