type _ResponseTypes=
	|WB_GenericResponseType
	|WD_account_account_menu_t
	|WD_account_set_setting_t
	|WD_accounts_list_t
	|WD_att_get_t
	|WD_att_log_t
	|WD_browse_edit_playlist_t
	|WD_browse_t
	|WD_feedback_t
	|WD_get_notification_menu_t
	|WD_get_transcript_t
	|WD_get_survey_t
	|WD_GetAccountSwitcherEndpoint_t
	|WD_getDatasyncIdsEndpoint_t
	|WD_guide_t
	|WD_like_dislike_t
	|WD_like_like_t
	|WD_like_removelike_t
	|WD_live_chat_get_live_chat_replay_t
	|WD_live_chat_get_live_chat_t
	|WD_music_get_search_suggestions_t
	|WD_next_t
	|WD_notification_get_unseen_count_t
	|WD_notification_modify_channel_preference_t
	|WD_notification_record_interactions
	|WD_pdg_get_pdg_buy_flow_t
	|WD_player_t
	|WD_playlist_get_add_to_playlist_t
	|WD_reel_reel_item_watch_t
	|WD_reel_reel_watch_sequence_t
	|WD_search_t
	|WD_share_get_share_panel_t
	|WD_subscription_subscribe_t
	|WD_subscription_unsubscribe_t
	|WD_update_metadata_t
	;
;