type SubscribeButtonData={
	buttonText: TextT;
	subscribed: false;
	enabled: true;
	type: "FREE";
	channelId: `UC${string}`;
	showPreferences: false;
	subscribedButtonText: TextT;
	unsubscribedButtonText: TextT;
	trackingParams: string;
	unsubscribeButtonText: TextT;
	subscribeAccessibility: Accessibility;
	unsubscribeAccessibility: Accessibility;
	notificationPreferenceButton: SubscriptionNotificationToggleButtonRenderer;
	targetId: "watch-subscribe";
	subscribedEntityKey: string;
	onSubscribeEndpoints: {}[];
	onUnsubscribeEndpoints: {}[];
};