type unknown$param=[
	"browse.params",
	"createBackstagePost.param",
	"entity_key",
	"get_transcript.params",
	"like.likeParams",
	"like.remove_like_params",
	"next.queue_context_params",
	"playlist_edit.params",
	"reel.sequence_params",
	"report.params",
	"subscribe.params",
	"tracking.parentTrackingParams",
	"watch_page_url.pp",
	"watch_playlist.params",
	"ypc_get_offers.params",
][number];
type tracking$param<T extends string>=[
	`${T}.trackingParams.f1`,
	`${T}.trackingParams.f2`,
	`${T}.trackingParams.f3`,
	`${T}.trackingParams.f4.f1`,
	`${T}.trackingParams.f4.f2`,
	`${T}.trackingParams.f4.f3`,
	`${T}.trackingParams.f4`,
	`${T}.trackingParams.f6`,
	`${T}.trackingParams`,
][number];