interface WatchResponsePlayer {
	responseContext: ResponseContext;
	playabilityStatus: PlayabilityStatus;
	streamingData: StreamingData;
	playerAds: DesktopWatchAdsRenderer[];
	playbackTracking: PlaybackTracking;
	captions?: CaptionsRenderer;
	videoDetails: VideoDetails;
	playerConfig: PlayerConfig;
	storyboards: PlayerStoryboardSpecRenderer;
	microformat: PlayerMicroformatRenderer;
	cards: CardCollectionRenderer;
	trackingParams: string;
	attestation: PlayerAttestationRenderer;
	videoQualityPromoSupportedRenderers: VideoQualityPromoRenderer;
	adPlacements?: {}[];
	frameworkUpdates: FrameworkUpdates;
	endscreen?: EndscreenRenderer;
	paidContentOverlay?: PaidContentOverlay;
	annotations: PlayerAnnotationsExpandedRenderer[];
};