type YtTargetIdType=[
	G$AppendContinuationItems['targetId'],
	T$A$Continuation<"browse-feedFEwhat_to_watch",R$BrowseFeed>['targetId'],
	"comments-section",
	EngagementPanelSectionTargetId,
	D$SearchFeedSectionList['targetId'],
	D$ScrollToEngagementPanel['targetId'],
	R$Search['targetId'],
	D$TranscriptSearchPanel['targetId'],
	D$UpdateEngagementPanel['targetId'],
	A$WatchNextContinuation['targetId'],
	ChipCloudChip_tid['targetId'],
	`shopping_panel_for_entry_point_${"5"|"22"}`,
	"clip-info-button",
	"sponsorships-button",
	D$Menu$targetId,
	GenericEngagementPanelSectionItem['targetId'],
][number];
