type YtTargetIdType=[
	D$AppendContinuationItemsAction['targetId'],
	BrowseFeedAction['targetId'],
	CommentsSectionContinuationAction['targetId'],
	EngagementPanelSectionTargetId,
	D$SearchFeedSectionList['targetId'],
	D$ScrollToEngagementPanel['targetId'],
	R$Search['targetId'],
	D$TranscriptSearchPanel['targetId'],
	D$UpdateEngagementPanel['targetId'],
	WatchNextContinuationAction['targetId'],
	ChipCloudChip_tid['targetId'],
	`shopping_panel_for_entry_point_${"5"|"22"}`,
	"clip-info-button",
	"sponsorships-button",
	D$Menu$targetId,
	GenericEngagementPanelSectionItem['targetId'],
][number];
