type YtUrlFormat=[
	"/",
	"/channel_switcher",
	`/@${string}${""|`/${ChannelSubUrlFormat}`}`,
	`/${ApiUrlFormat}`,
	`/account${""|`_${AccountPageSettingsSections}`}`,
	`/channel/UC${string}`,
	`/feed/${YtFeedSubSections}`,
	`/feed/trending?bp=${string}`,
	`/gaming`,
	`/playlist?${YtPlaylistUrlParamsFormat}`,
	`/premium`,
	`/reporthistory`,
	`/results?search_query=${string}`,
	`/shorts/${string}`,
	`/watch?${YtWatchUrlParamsFormat}`,
	`${YtDomain|""}/api/stats/ads?${ApiStatsAdsArgs}`,
	`https://${YtExternalUrlFormat}`,
	ParsableBaseUrlFormat,
][number];
// spell:ignore nx57ynsd trackclk aclk
type YtExternalUrlFormat=[
	`ad.doubleclick.net/ddm/trackclk/${string}`,
	`i.ytimg.com/vi/${string}/maxresdefault.jpg`,
	`music.youtube.com${"/"|""}`,
	`rr5---sn-nx57ynsd.googlevideo.com/initplayback?${string}`,
	`studio.youtube.com${"/"|""}`,
	`tv.youtube.com/?utm_source=youtube_web&utm_medium=ep&utm_campaign=home&ve=34273`,
	`www.google.com/get/videoqualityreport/`,
	`www.googleadservices.com/pagead/aclk?${string}`,
	`www.youtube.com/api/stats/ads?${ApiStatsAdsArgs}`,
	`www.youtubekids.com${"/"|""}?source=youtube_web`,
	`yt${number}.ggpht.com/${string}=s88-c-k-c0x00ffffff-no-rj`,
][number];