type GE_ResponseReceived=A_AppendContinuationItems|
	C_AdsControlFlowOpportunityReceived|
	C_ChangeKeyedMarkersVisibility|
	C_LoadMarkers|
	C_ReloadContinuationItems|
	C_ReloadContinuationItems|
	E_SignalService_SendPost;
