import {ACTION_ADD_VIDEO} from "../a/ACTION_ADD_VIDEO";
import {ACTION_REMOVE_VIDEO_BY_VIDEO_ID} from "../a/ACTION_REMOVE_VIDEO_BY_VIDEO_ID";
import {ACTION_SET_PLAYLIST_VIDEO_ORDER} from "./ACTION_SET_PLAYLIST_VIDEO_ORDER";

export type ENUM_ACTIONS=ACTION_ADD_VIDEO|ACTION_REMOVE_VIDEO_BY_VIDEO_ID|ACTION_SET_PLAYLIST_VIDEO_ORDER;
