import {ACTION_ADD_VIDEO} from "../a/ACTION_ADD_VIDEO";
import {ACTION_REMOVE_VIDEO_BY_VIDEO_ID} from "../a/ACTION_REMOVE_VIDEO_BY_VIDEO_ID";

export type ENUM_ACTIONS=ACTION_ADD_VIDEO|ACTION_REMOVE_VIDEO_BY_VIDEO_ID;
