export type InstructionOpcodesList=[
	append: "append",
	breakpoint: "breakpoint",
	call: "call",
	cast: "cast",
	construct: "construct",
	drop: "drop",
	dup: "dup",
	get: "get",
	halt: "halt",
	je: "je",
	jump: "jmp",
	modify_operand: "modify_operand",
	nop: "nop",
	peek: "peek",
	push_window_object: "push_window_object",
	push: "push",
	return_: "return",
	vm_block_trace: "vm_block_trace",
	vm_call: "vm_call",
	vm_push_args: "vm_push_args",
	vm_push_ip: "vm_push_ip",
	vm_push_self: "vm_push_self",
	vm_return: "vm_return",
]
