type R_Browse={
	responseContext: RC$ResponseContext;
	contents?: G$BrowseContents;
	continuationContents?: C$SectionList;
	header?: G$BrowseHeader;
	alerts?: R_AlertWithButton[];
	metadata?: G$BrowseMetadata;
	trackingParams: string;
	topbar?: R_DesktopTopbar;
	microformat?: R_MicroformatData;
	frameworkUpdates?: R_EntityBatchUpdate;
	// ?
	maxAgeStoreSeconds?: number;
	background?: R_MusicThumbnail;
	// ?
	onResponseReceivedActions?: ResponseReceivedAction[];
	sidebar?: G$BrowseSidebar;
	observedStateTags?: B$StateTag[];
	cacheMetadata?: CacheMetadata;
};
