import {SymbolRef} from "types/SymbolRef";
import {AutoBuy} from "types/AutoBuy";
import {ScriptStateHost} from "types/ScriptStateHost";
import {find_all_scripts_using_string_apis} from "types/find_all_scripts_using_string_apis_helper";
import {UniqueIdGenerator} from "types/UniqueIdGenerator";
import {SimpleStackVMParser} from "types/SimpleStackVMParser";
import {calc_ratio} from "types/calc_ratio";
import {rebuild_auto_main} from "types/main";
import {TimerApi} from "types/TimerApi.js";

const TIMER_SINGLE = 1;
const TIMER_REPEATING = 2;
const TIMER_TAG_COUNT = 3;
const AUDIO_ELEMENT_VOLUME = 0.58;
const cint_arr: string[] = [];
const WorkerAsyncMessage = 1;
const TimeoutFireS = 101;
const TimeoutFireR = 102;
const WorkerUpdateMessageHandler = 201;
const TimeoutMessageR = 202;
const TimeoutSetS = 203;
const TimeoutSetR = 204;
const TimeoutClearS = 205;
const TimeoutClearR = 206;
const TimeoutClearA = 207;
const WorkerDestroyMessage = 300;
const WorkerUpdateMessageHandlerReply = 301;
const WorkerReadyReply = 302;
const ReplySetSingle = 303;
const ReplySetRepeating = 304;
const ReplyClearSingle = 305;
const ReplyClearRepeating = 306;
const ReplyClearAny = 307;
const ReplyMessage1 = 401;
const ReplyMessage2 = 402;
const ReplyFromWorker = 500;
const ReplyToWorker = 600;
const TimeoutSingleReply = 700;
const TimeoutRepeatingReply = 701;
const TimeoutSetTypes = 1001;
const TimeoutSetStringS = "setTimeout";
const TimeoutSetStringR = "setInterval";
const TimeoutClearStringS = "clearTimeout";
const TimeoutClearStringR = "clearInterval";
let g_timer_api = new TimerApi;
let message_types = g_timer_api.msg_types;
var is_in_ignored_from_src_fn = {flag:false};
var is_in_userscript_fn = {flag:false};
var is_in_userscript = {flag:true};
let cur_event_fns: (CallableFunction | NewableFunction)[] = [];
const [weak_scripts, register_obj_with_registry] = find_all_scripts_using_string_apis();
let seen_elements = new WeakSet;
const local_logging_level = 3;
const LOG_LEVEL_ERROR = 1;
const LOG_LEVEL_WARN = 2;
const LOG_LEVEL_INFO = 3;
const LOG_LEVEL_VERBOSE = 4;
const LOG_LEVEL_TRACE = 5;
SimpleStackVMParser.match_regex = /(.+?)(;|$)/gm;
console.assert(calc_ratio([0, 0]) === 0, "calc ratio of array full of zeros does not divide by zero");
const debug_id_gen = new UniqueIdGenerator;
const debug_id_syms: WeakRef<SymbolRef>[] = [];
const auto_buy_obj = new AutoBuy;
export default function entry_point() {
	rebuild_auto_main();
	ScriptStateHost.event_target.dispatchEvent({type: 'userscript', state: 'done'});
}
