export const instruction_descriptor_arr_type=[
	['append',InstructionAppendImpl],
	['breakpoint',InstructionBreakpointImpl],
	['call',InstructionCallImpl],
	['cast',InstructionCastImpl],
	['construct',InstructionConstructImpl],
	['drop',InstructionDropImpl],
	['dup',InstructionDupImpl],
	['get',InstructionGetImpl],
	['halt',InstructionHaltImpl],
	['je',InstructionJeImpl],
	['jmp',InstructionJmpImpl],
	['modify_operand',InstructionModifyOpImpl],
	['nop',InstructionNopImpl],
	['peek',InstructionPeekImpl],
	['push_window_object',InstructionPushWindowObjectImpl],
	['push',InstructionPushImpl],
	['return',InstructionReturnImpl],
	['vm_block_trace',InstructionBlockTraceImpl],
	['vm_call',InstructionVMCallImpl],
	['vm_push_args',InstructionPushArgsImpl],
	['vm_push_ip',InstructionVMPushIPImpl],
	['vm_push_self',InstructionPushVMObjImpl],
	['vm_return',InstructionVMReturnImpl],
] as const;